import React,{useEffect,useState}from'react';
import ClubCrest from'./ClubCrest';
import PlayerIcon from'./PlayerIcon';
import NationalityFlag from'./NationalityFlag';
import{supabase,supabaseConfigError}from'./supabase';
import'./ManagerDebutantsTable.css';

type DebutRow={debut_number:number;match_id:number;match_date:string;player_id:number;player_name:string;player_profile_image_url:string|null;opponent_id:number;opponent_name:string;opponent_crest_url:string|null;leeds_score:number;opponent_score:number;result:string;venue_type:string;competition:string;started:boolean;substitute:boolean;age_years:number|null;age_days:number|null;declared_nation:string|null;scored:boolean;sent_off:boolean};

function formatDate(value:string){const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?value:d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
function venueLabel(value:string){return value==='H'?'Home':value==='A'?'Away':value==='N'?'Neutral':'—'}
function wdl(result:string){return result==='Won'?'W':result==='Draw'?'D':result==='Lost'?'L':'—'}
function wdlClass(result:string){return result==='Won'?'win':result==='Draw'?'draw':result==='Lost'?'loss':''}
function ageLabel(years:number|null,days:number|null){return years==null||days==null?'—':`${years}-${days}`}

export default function ManagerDebutantsTable({managerId}:{managerId:number}){
 const[rows,setRows]=useState<DebutRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);const{data,error}=await supabase.rpc('get_manager_debutants_detail',{p_manager_id:managerId});if(cancelled)return;if(error){setError(error.message);setRows([])}else setRows((data??[])as DebutRow[]);setLoading(false)})();return()=>{cancelled=true}},[managerId]);
 return <section className="card manager-debutants-table-card"><div className="player-profile-panelhead manager-debutants-head"><div><span className="section-kicker">Player development</span><h2>Debutants</h2></div><div className="section-kicker">{loading?'…':`${rows.length} ${rows.length===1?'Debutant':'Debutants'}`}</div></div>
  {loading?<div className="lb-loading">Loading debutants…</div>:error?<div className="lb-loading">Debutants unavailable</div>:rows.length?<div className="lb-table-wrap manager-debutants-wrap"><table className="lb-table manager-debutants-table"><thead><tr><th className="debut-number-col">Debut #</th><th className="debut-date-col">Date</th><th className="debut-player-icon-col" aria-label="Player icon"></th><th className="debut-player-col">Player</th><th className="debut-opponent-icon-col" aria-label="Opponent crest"></th><th className="debut-opponent-col">Opponent</th><th className="debut-score-col">Score</th><th className="debut-wdl-col">WDL</th><th className="debut-result-col">Result</th><th className="debut-role-col">Started/Sub</th><th className="debut-venue-col">H/A/N</th><th className="debut-competition-col">Competition</th><th className="debut-age-col">Age (Y-D)</th><th className="debut-flag-col" aria-label="Flag"></th><th className="debut-nation-col">Declared Nation</th><th className="debut-event-col">Event</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.match_id}-${r.player_id}`}><td className="debut-number-col"><span className="manager-debut-number">{r.debut_number}</span></td><td className="debut-date-col">{formatDate(r.match_date)}</td><td className="debut-player-icon-col"><PlayerIcon name={r.player_name} src={r.player_profile_image_url}/></td><td className="debut-player-col"><span className="team-name">{r.player_name}</span></td><td className="debut-opponent-icon-col"><ClubCrest crestUrl={r.opponent_crest_url} name={r.opponent_name}/></td><td className="debut-opponent-col">{r.opponent_name}</td><td className="debut-score-col"><strong>{r.leeds_score}–{r.opponent_score}</strong></td><td className="debut-wdl-col"><span className={`manager-debut-wdl ${wdlClass(r.result)}`}>{wdl(r.result)}</span></td><td className="debut-result-col">{r.result}</td><td className="debut-role-col">{r.started?'Started':'Sub'}</td><td className="debut-venue-col">{venueLabel(r.venue_type)}</td><td className="debut-competition-col">{r.competition}</td><td className="debut-age-col">{ageLabel(r.age_years,r.age_days)}</td><td className="debut-flag-col"><NationalityFlag nation={r.declared_nation}/></td><td className="debut-nation-col">{r.declared_nation??'—'}</td><td className="debut-event-col"><span className="manager-debut-events">{r.scored&&<img src="/appicons/Goal2.png" alt="Scored" title="Scored on debut"/>}{r.sent_off&&<img src="/appicons/Red Card Icon2.png" alt="Sent off" title="Sent off on debut"/>}{!r.scored&&!r.sent_off&&<span>—</span>}</span></td></tr>)}</tbody></table></div>:<div className="lb-empty">No debutants found for this manager.</div>}
 </section>;
}
