import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,CalendarDays,Clock3,MapPin,Users}from'lucide-react';
import{supabase,supabaseConfigError}from'./supabase';
import ClubCrest from'./ClubCrest';
import'./MatchCentre.css';
import'./MatchCentreSquad.css';
import'./MatchCentreDetails.css';

type Summary={match_id:number;match_date:string;season:string|null;opponent:string;opponent_crest_url:string|null;competition:string;round:string|null;venue_type:string;leeds_score:number;opponent_score:number;result:string;half_time_leeds_score:number|null;half_time_opponent_score:number|null;stadium:string|null;attendance:number|null;referee:string|null;kickoff_time:string|null;formation:string|null;milestones_events:string|null;opponent_scorers_raw:string|null;opposition_manager_name:string|null;leeds_manager:string|null;captain_player_id:number|null;captain:string|null;motm_player_id:number|null;man_of_the_match:string|null};
type PlayerMatch={player_match_id:number;player_id:number;started:boolean;substitute:boolean;lineup_order:number|null;source_slot:string|null};
type Player={player_id:number;display_name:string};
type PlayerFact={player_id:number;date_of_birth:string|null;appearance_number:number|null};
type ManagerFact={manager_id:number;manager_name:string;date_of_birth:string|null;manager_match_number:number|null};
type Goal={goal_id:number;minute_raw:string|null;minute_normalised:number|null;leeds_player_id:number|null;scorer_name_raw:string|null;assist_player_id:number|null;assisted_by_raw:string|null;goal_type:string|null;location:string|null;body_part:string|null;is_own_goal:boolean};
type Sub={substitution_id:number;minute_raw:string|null;minute_base:number|null;stoppage_minute:number|null;player_off_id:number|null;player_on_id:number|null};
type OppRed={opposition_red_card_id:number;recipient_raw:string;minute_raw:string|null;minute_base:number|null;stoppage_minute:number|null};
type Milestone={milestone_category:string;person_name:string;milestone:string;milestone_number:number;category_sort:number;milestone_sort:number};
type TimelineEvent={key:string;minute:number;minuteLabel:string;kind:'goal-leeds'|'goal-opponent'|'sub'|'red'|'kickoff'|'half-time'|'full-time';title:string;detail?:string;tag:string};

const dateLabel=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const minuteValue=(raw:string|null|undefined)=>{if(!raw)return 999;const m=raw.match(/(\d+)(?:\+(\d+))?/);return m?Number(m[1])+Number(m[2]||0)/100:999};
const minuteLabel=(raw:string|null,base:number|null)=>`${String(raw??base??'—').replace(/'+$/,'')}'`;
const iconPath=(name:string)=>`/appicons/${encodeURIComponent(name)}`;
const ageYearsDays=(dob:string|null|undefined,onDate:string)=>{if(!dob)return'—';const birth=new Date(`${dob}T00:00:00Z`),on=new Date(`${onDate}T00:00:00Z`);let years=on.getUTCFullYear()-birth.getUTCFullYear();let anniversary=new Date(Date.UTC(on.getUTCFullYear(),birth.getUTCMonth(),birth.getUTCDate()));if(anniversary>on){years-=1;anniversary=new Date(Date.UTC(on.getUTCFullYear()-1,birth.getUTCMonth(),birth.getUTCDate()))}const days=Math.floor((on.getTime()-anniversary.getTime())/86400000);return`${years}-${days}`};
const ageDecimal=(dob:string|null|undefined,onDate:string)=>{if(!dob)return null;const birth=new Date(`${dob}T00:00:00Z`),on=new Date(`${onDate}T00:00:00Z`);return Math.max(0,(on.getTime()-birth.getTime())/86400000/365.2425)};

function parseOpponentGoals(raw:string|null,opponent:string):TimelineEvent[]{
 if(!raw)return[];
 const parsed:TimelineEvent[]=[];
 let previousScorer='';
 raw.split(/[,;]\s*/).forEach((sourcePart,i)=>{
  const part=sourcePart.trim().replace(/[’]/g,"'");
  const repeated=part.match(/^(?:penalty\s+)?(\d+(?:\+\d+)?)'?$/i);
  if(repeated&&previousScorer){const minute=repeated[1];parsed.push({key:`opp-goal-${i}`,minute:minuteValue(minute),minuteLabel:`${minute}'`,kind:'goal-opponent',title:previousScorer,detail:`${opponent} goal`,tag:'GOAL'});return}
  const full=part.match(/^(.*?)\s+(\d+(?:\+\d+)?)'?$/);
  if(!full)return;
  previousScorer=full[1].trim();
  parsed.push({key:`opp-goal-${i}`,minute:minuteValue(full[2]),minuteLabel:`${full[2]}'`,kind:'goal-opponent',title:previousScorer,detail:`${opponent} goal`,tag:'GOAL'});
 });
 return parsed;
}
function redCardDetail(raw:string|null,recipient:string){if(!raw)return'Opposition red card';const line=raw.split('\n').find(v=>v.includes('Opposition Red Card:')&&v.includes(recipient));const m=line?.match(/\((.*?)\)\s*$/);return m?.[1]?.trim()||'Opposition red card'}

export default function MatchCentre({matchId,onBack}:{matchId:number;onBack:()=>void}){
 const[match,setMatch]=useState<Summary|null>(null),[playerMatches,setPlayerMatches]=useState<PlayerMatch[]>([]),[players,setPlayers]=useState<Player[]>([]),[playerFacts,setPlayerFacts]=useState<PlayerFact[]>([]),[managerFact,setManagerFact]=useState<ManagerFact|null>(null),[goals,setGoals]=useState<Goal[]>([]),[subs,setSubs]=useState<Sub[]>([]),[oppReds,setOppReds]=useState<OppRed[]>([]),[milestones,setMilestones]=useState<Milestone[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;(async()=>{setLoading(true);setError(null);const[{data:m,error:me},{data:pm,error:pme},{data:g,error:ge},{data:s,error:se},{data:r,error:re},{data:pf,error:pfe},{data:mf,error:mfe},{data:ms,error:mse}]=await Promise.all([
  supabase!.from('match_centre_summary').select('*').eq('match_id',matchId).single(),
  supabase!.from('player_matches').select('player_match_id,player_id,started,substitute,lineup_order,source_slot').eq('match_id',matchId).order('lineup_order'),
  supabase!.from('goals').select('goal_id,minute_raw,minute_normalised,leeds_player_id,scorer_name_raw,assist_player_id,assisted_by_raw,goal_type,location,body_part,is_own_goal').eq('match_id',matchId).order('minute_normalised'),
  supabase!.from('match_substitutions').select('substitution_id,minute_raw,minute_base,stoppage_minute,player_off_id,player_on_id').eq('match_id',matchId).order('minute_base'),
  supabase!.from('opposition_red_cards').select('opposition_red_card_id,recipient_raw,minute_raw,minute_base,stoppage_minute').eq('match_id',matchId).order('minute_base'),
  supabase!.from('match_centre_player_facts').select('player_id,date_of_birth,appearance_number').eq('match_id',matchId),
  supabase!.from('match_centre_manager_facts').select('manager_id,manager_name,date_of_birth,manager_match_number').eq('match_id',matchId).maybeSingle(),
  supabase!.rpc('get_match_centre_milestones',{p_match_id:matchId})
 ]);const firstError=me||pme||ge||se||re||pfe||mfe||mse;if(firstError){if(!cancelled){setError(firstError.message);setLoading(false)}return}const ids=Array.from(new Set([...(pm??[]).map(x=>Number(x.player_id)),...(g??[]).flatMap(x=>[x.leeds_player_id,x.assist_player_id].filter(Boolean).map(Number)),...(s??[]).flatMap(x=>[x.player_off_id,x.player_on_id].filter(Boolean).map(Number))]));let playerRows:Player[]=[];if(ids.length){const{data:p,error:pe}=await supabase!.from('players').select('player_id,display_name').in('player_id',ids);if(pe){if(!cancelled){setError(pe.message);setLoading(false)}return}playerRows=(p??[])as Player[]}if(!cancelled){setMatch(m as Summary);setPlayerMatches((pm??[])as PlayerMatch[]);setGoals((g??[])as Goal[]);setSubs((s??[])as Sub[]);setOppReds((r??[])as OppRed[]);setPlayerFacts((pf??[])as PlayerFact[]);setManagerFact((mf??null)as ManagerFact|null);setMilestones((ms??[])as Milestone[]);setPlayers(playerRows);setLoading(false)}})();return()=>{cancelled=true}},[matchId]);
 const names=useMemo(()=>new Map(players.map(p=>[Number(p.player_id),p.display_name])),[players]);
 const facts=useMemo(()=>new Map(playerFacts.map(f=>[Number(f.player_id),f])),[playerFacts]);
 const events=useMemo<TimelineEvent[]>(()=>{if(!match)return[];const leeds=goals.map(g=>({key:`goal-${g.goal_id}`,minute:g.minute_normalised??minuteValue(g.minute_raw),minuteLabel:`${g.minute_raw??g.minute_normalised??''}'`,kind:'goal-leeds' as const,title:names.get(Number(g.leeds_player_id))||g.scorer_name_raw||'Leeds scorer',detail:[g.assist_player_id?`Assist: ${names.get(Number(g.assist_player_id))||g.assisted_by_raw}`:null,g.goal_type,g.location,g.body_part].filter(Boolean).join(' · '),tag:'GOAL'}));const changes=subs.map(s=>({key:`sub-${s.substitution_id}`,minute:(s.minute_base??minuteValue(s.minute_raw))+(s.stoppage_minute??0)/100,minuteLabel:minuteLabel(s.minute_raw,s.minute_base),kind:'sub' as const,title:`${names.get(Number(s.player_on_id))||'Player on'} for ${names.get(Number(s.player_off_id))||'Player off'}`,detail:'Leeds United substitution',tag:'SUB'}));const reds=oppReds.map(r=>({key:`red-${r.opposition_red_card_id}`,minute:(r.minute_base??minuteValue(r.minute_raw))+(r.stoppage_minute??0)/100,minuteLabel:r.minute_raw?`${r.minute_raw}'`:`${r.minute_base??''}'`,kind:'red' as const,title:r.recipient_raw,detail:redCardDetail(match.milestones_events,r.recipient_raw),tag:'RED'}));const phases:TimelineEvent[]=[{key:'kickoff',minute:-1,minuteLabel:'0′',kind:'kickoff',title:'Kick-off',tag:'START'},{key:'half-time',minute:45.99,minuteLabel:'HT',kind:'half-time',title:'Half-Time',detail:`${match.opponent} ${match.half_time_opponent_score??'—'}–${match.half_time_leeds_score??'—'} Leeds United`,tag:'HT'},{key:'full-time',minute:9999,minuteLabel:'FT',kind:'full-time',title:'Full-Time',detail:`${match.opponent} ${match.opponent_score}–${match.leeds_score} Leeds United`,tag:'FT'}];return[...phases,...leeds,...parseOpponentGoals(match.opponent_scorers_raw,match.opponent),...reds,...changes].sort((a,b)=>a.minute-b.minute)},[match,goals,subs,oppReds,names]);
 if(loading)return <div className="card mc-state">Loading Match Centre…</div>;
 if(error||!match)return <div className="card mc-state"><strong>Match Centre could not load.</strong><span>{error||`Match #${matchId} was not found.`}</span></div>;

 const starters=playerMatches.filter(p=>p.started),usedSubs=playerMatches.filter(p=>p.substitute);
 const averageAge=(rows:PlayerMatch[])=>{const ages=rows.map(p=>ageDecimal(facts.get(Number(p.player_id))?.date_of_birth,match.match_date)).filter((v):v is number=>v!=null);return ages.length?(ages.reduce((sum,v)=>sum+v,0)/ages.length).toFixed(1):'—'};
 const starterAverageAge=averageAge(starters),subsAverageAge=averageAge(usedSubs);
 const leedsScorers=goals.map(g=>`${names.get(Number(g.leeds_player_id))||g.scorer_name_raw||'Leeds scorer'} ${g.minute_raw??g.minute_normalised??''}'`).join(' · ');
 const opponentScorers=parseOpponentGoals(match.opponent_scorers_raw,match.opponent).map(e=>`${e.title} ${e.minuteLabel}`).join(' · ');
 const subByPlayerOn=new Map(subs.map(s=>[Number(s.player_on_id),s])),subByPlayerOff=new Map(subs.map(s=>[Number(s.player_off_id),s]));
 const goalsByPlayer=new Map<number,Goal[]>(),assistsByPlayer=new Map<number,Goal[]>();
 goals.forEach(g=>{if(g.leeds_player_id){const id=Number(g.leeds_player_id);goalsByPlayer.set(id,[...(goalsByPlayer.get(id)||[]),g])}if(g.assist_player_id){const id=Number(g.assist_player_id);assistsByPlayer.set(id,[...(assistsByPlayer.get(id)||[]),g])}});
 const squadRow=(p:PlayerMatch,kind:'starter'|'sub')=>{const id=Number(p.player_id),playerGoals=goalsByPlayer.get(id)||[],playerAssists=assistsByPlayer.get(id)||[],off=subByPlayerOff.get(id),on=subByPlayerOn.get(id),isMotm=id===Number(match.motm_player_id),isCaptain=id===Number(match.captain_player_id),fact=facts.get(id);return <div className={`mc-squad-row${isMotm?' mc-squad-row-motm':''}`} key={p.player_match_id}><span className="mc-squad-number">{p.lineup_order??'—'}</span><div className="mc-squad-identity"><strong className="mc-squad-name">{names.get(id)||`Player ${id}`}</strong>{isCaptain&&<img className="mc-squad-icon mc-squad-captain-icon" src={iconPath('Captain Icon3.png')} alt="Captain"/>}</div><div className="mc-squad-events">{playerGoals.map(g=><span className="mc-squad-chip mc-squad-chip-goal" key={`g-${g.goal_id}`}><img className="mc-squad-icon" src={iconPath('Goal2.png')} alt="Goal"/> {minuteLabel(g.minute_raw,g.minute_normalised)}</span>)}{playerAssists.map(g=><span className="mc-squad-chip mc-squad-chip-assist" key={`a-${g.goal_id}`}><img className="mc-squad-icon" src={iconPath('Assist3.png')} alt="Assist"/> {minuteLabel(g.minute_raw,g.minute_normalised)}</span>)}{kind==='starter'&&off&&<span className="mc-squad-chip mc-squad-chip-off">▼ {minuteLabel(off.minute_raw,off.minute_base)}</span>}{kind==='sub'&&on&&<span className="mc-squad-chip mc-squad-chip-on">▲ {minuteLabel(on.minute_raw,on.minute_base)}</span>}{isMotm&&<span className="mc-squad-chip mc-squad-chip-motm">POTM</span>}</div><span className="mc-squad-fact">{ageYearsDays(fact?.date_of_birth,match.match_date)}</span><span className="mc-squad-fact">{fact?.appearance_number??'—'}</span></div>};

 return <div className="mc-page">
  <button type="button" className="mc-back" onClick={onBack}><ArrowLeft size={14}/> Back to Matches</button>
  <section className="card mc-hero"><div className="mc-hero-top"><div><div className="mc-kicker">{match.competition}{match.round?` · ${match.round}`:''}</div><div className="mc-date"><CalendarDays size={14}/>{dateLabel(match.match_date)} · {match.season}</div></div><div className={`mc-result mc-result-${match.result.toLowerCase()}`}>{match.result}</div></div><div className="mc-scoreboard"><div className="mc-team mc-team-home"><div className="mc-crest-shell"><ClubCrest crestUrl={match.opponent_crest_url} name={match.opponent}/></div><strong>{match.opponent}</strong><span className="mc-scorers">{opponentScorers||'—'}</span></div><div className="mc-score"><div className="mc-score-main"><span>{match.opponent_score}</span><b>–</b><span>{match.leeds_score}</span></div><small>FULL TIME</small><em>HT {match.half_time_opponent_score??'—'}–{match.half_time_leeds_score??'—'}</em></div><div className="mc-team mc-team-away"><div className="mc-crest-shell"><img src="/Leeds.png" alt="Leeds United" className="club-crest"/></div><strong>Leeds United</strong><span className="mc-scorers">{leedsScorers||'—'}</span></div></div><div className="mc-meta"><span className="mc-match-id">MATCH #{match.match_id}</span><span><MapPin size={15}/>{match.stadium??'—'}</span><span><Users size={15}/>{match.attendance==null?'—':match.attendance.toLocaleString('en-GB')}</span><span><Clock3 size={15}/>{match.kickoff_time??'—'}</span><span><img className="mc-referee-whistle-img" src={iconPath('whistleicon.png')} alt="Referee"/>{match.referee??'—'}</span></div></section>
  <section className="card mc-panel mc-events-panel"><div className="mc-panel-head"><div><span className="section-kicker">Match events</span><h2>Timeline</h2></div><span className="mc-event-count">{events.length} EVENTS</span></div><div className="mc-timeline">{events.map(e=><div className={`mc-event ${e.kind}`} key={e.key}><span className="mc-minute">{e.minuteLabel}</span>{e.kind==='goal-leeds'?<span className="mc-dot mc-goal-crest"><img src="/Leeds.png" alt="Leeds United"/></span>:e.kind==='goal-opponent'?<span className="mc-dot mc-goal-crest"><ClubCrest crestUrl={match.opponent_crest_url} name={match.opponent}/></span>:<span className="mc-dot"/>}<div className="mc-event-copy"><div className="mc-event-title"><strong>{e.title}</strong><span>{e.kind==='red'?<><img className="mc-timeline-icon" src={iconPath('Red Card Icon2.png')} alt="Red card"/> RED</>:e.tag}</span></div>{e.detail&&<small>{e.detail}</small>}</div></div>)}</div></section>
  {milestones.length>0&&<section className="card mc-panel mc-milestones"><div className="mc-panel-head"><div><span className="section-kicker">Leeds United</span><h2>Milestones</h2></div><span className="mc-event-count">{milestones.length} MILESTONES</span></div><div className="mc-milestone-table"><div className="mc-milestone-head"><span>Milestone Category</span><span>Player/Manager</span><span>Milestone</span></div>{milestones.map((row,i)=><div className="mc-milestone-row" key={`${row.milestone_category}-${row.person_name}-${row.milestone}-${i}`}><span className="mc-milestone-category">{row.milestone_category}</span><strong>{row.person_name}</strong><span>{row.milestone}</span></div>)}</div></section>}
  <section className="card mc-squad-panel"><div className="mc-squad-head"><div className="mc-squad-summary"><div className="mc-squad-summary-row"><span>Formation:</span><span className="mc-formation">{match.formation??'—'}</span></div><div>Average Starting XI Age: <strong>{starterAverageAge}</strong></div><div>Average Subs Used Age: <strong>{subsAverageAge}</strong></div></div></div><div className="mc-squad-sheet"><div className="mc-squad-section"><div className="mc-squad-section-title mc-squad-section-title-columns"><h3>Starting XI</h3><div className="mc-squad-columns"><span>Age</span><span>App #</span></div></div>{starters.map(p=>squadRow(p,'starter'))}</div><div className="mc-squad-section"><div className="mc-squad-section-title"><h3>Substitutes Used</h3><span>{usedSubs.length} used</span></div>{usedSubs.map(p=>squadRow(p,'sub'))}</div><div className="mc-manager-straps"><div className="mc-manager-strap"><div className="mc-manager-crest"><img src="/Leeds.png" alt="Leeds United" className="club-crest"/></div><div className="mc-manager-copy"><small>LEEDS MANAGER</small><strong>{managerFact?.manager_name||match.leeds_manager||'—'}</strong></div><div className="mc-manager-facts"><span><small>MATCH</small>{managerFact?.manager_match_number??'—'}</span><span><small>AGE</small>{ageYearsDays(managerFact?.date_of_birth,match.match_date)}</span></div></div><div className="mc-manager-strap mc-manager-strap-opposition"><div className="mc-manager-crest"><ClubCrest crestUrl={match.opponent_crest_url} name={match.opponent}/></div><div className="mc-manager-copy"><small>OPPOSITION MANAGER</small><strong>{match.opposition_manager_name??'—'}</strong></div></div></div></div></section>
 </div>;
}
