import React,{useEffect,useState}from'react';
import PlayerIcon from'./PlayerIcon';
import ManagerIcon from'./ManagerIcon';
import ClubCrest from'./ClubCrest';
import{supabase,supabaseConfigError}from'./supabase';
import'./PlayerOpponentWidgets.css';

type Row={id:number|null;name:string;image?:string|null;appearances?:number;wins?:number;winPct?:number;goals?:number;gpg?:number;matches?:number;draws?:number;losses?:number;redCards?:number;hatTricks?:number;maxGoals?:number;cleanSheets?:number;rate?:number;recipientType?:string};
type Data={appearances:Row[];goals:Row[];leedsManagers:Row[];managersFaced:Row[];redCards:Row[];hatTricks:Row[];cleanSheets:Row[]};
type IconKind='player'|'manager'|'opponent';
function ScopeToggle({all,onChange}:{all:boolean;onChange:(v:boolean)=>void}){return <div className="player-opponent-scope"><button className={!all?'active':''} onClick={()=>onChange(false)}>Top 5</button><button className={all?'active':''} onClick={()=>onChange(true)}>All</button></div>}
function initials(name:string){return name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function Avatar({row,kind,opponentName,opponentCrest}:{row:Row;kind:IconKind;opponentName:string;opponentCrest:string|null}){let content:React.ReactNode;if(kind==='opponent')content=<ClubCrest crestUrl={opponentCrest} name={opponentName}/>;else if(kind==='manager'||row.recipientType==='Manager')content=<ManagerIcon name={row.name} src={row.image??null}/>;else content=row.image?<PlayerIcon name={row.name} src={row.image}/>:<span className="opponent-widget-player-fallback">{initials(row.name)}</span>;return <span className="opponent-widget-avatar-slot">{content}</span>}
function Widget({title,rows,primary,secondary,maxValue,kind='player',opponentName,opponentCrest}:{title:string;rows:Row[];primary:(r:Row)=>string;secondary:(r:Row)=>React.ReactNode;maxValue:(r:Row)=>number;kind?:IconKind;opponentName:string;opponentCrest:string|null}){const[all,setAll]=useState(false),shown=all?rows:rows.slice(0,5),max=Math.max(1,...rows.map(maxValue));return <section className={`card player-opponent-widget opponent-profile-ranking-widget${!all?' top-five':''}`}><div className="player-opponent-widget-head"><div><span className="section-kicker">Opposition analysis</span><h2>{title}</h2></div><ScopeToggle all={all} onChange={setAll}/></div><div className="player-opponent-widget-list">{shown.map((r,i)=><div className="player-opponent-widget-row" key={`${r.id??r.name}-${i}`}><div className="player-opponent-widget-club opponent-widget-entity"><Avatar row={r} kind={kind} opponentName={opponentName} opponentCrest={opponentCrest}/><div className="opponent-widget-copy"><strong>{r.name}</strong><span>{secondary(r)}</span></div></div><div className="player-opponent-widget-value player-opponent-widget-value-emphasis"><strong>{primary(r)}</strong></div><div className="player-opponent-widget-track"><i style={{width:`${maxValue(r)/max*100}%`}}/></div></div>)}</div></section>}
export default function OpponentProfileWidgets({clubId,opponentName,opponentCrest}:{clubId:number;opponentName:string;opponentCrest:string|null}){const[data,setData]=useState<Data|null>(null),[error,setError]=useState<string|null>(supabaseConfigError);useEffect(()=>{if(!supabase)return;let off=false;(async()=>{const{data:raw,error:rpcError}=await supabase!.rpc('opponent_profile_widgets_v1',{p_club_id:clubId});if(off)return;if(rpcError){setError(rpcError.message);return}const next=raw as Data;const playerRedIds=(next.redCards??[]).filter(r=>r.recipientType==='Player'&&r.id!=null).map(r=>r.id as number);if(playerRedIds.length){const{data:players,error:playerError}=await supabase!.from('players').select('player_id,profile_image_url').in('player_id',playerRedIds);if(off)return;if(playerError){setError(playerError.message);return}const images=new Map((players??[]).map((p:any)=>[Number(p.player_id),p.profile_image_url as string|null]));next.redCards=next.redCards.map(r=>r.recipientType==='Player'&&r.id!=null?{...r,image:images.get(Number(r.id))??null}:r)}setData(next)})();return()=>{off=true}},[clubId]);if(error)return <div className="card lb-loading">Opponent widgets unavailable</div>;if(!data)return <div className="card lb-loading">Loading opponent analysis…</div>;
return <div className="opponent-widget-grid">
<Widget title={`Most Appearances vs ${opponentName}`} rows={data.appearances} primary={r=>`${r.appearances} apps`} secondary={r=><><b>{r.wins}</b> wins / {r.appearances} appearances</>} maxValue={r=>r.appearances??0} opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Most Goals vs ${opponentName}`} rows={data.goals} primary={r=>`${r.goals} ${r.goals===1?'goal':'goals'}`} secondary={r=><>{r.goals} goals / {r.appearances} appearances</>} maxValue={r=>r.goals??0} opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Leeds Managers Record vs ${opponentName}`} rows={data.leedsManagers} primary={r=>`${r.matches} matches`} secondary={r=><><b>{r.wins}</b> wins / {r.matches} matches · {Number(r.winPct??0).toFixed(1)}% win rate</>} maxValue={r=>r.matches??0} kind="manager" opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Managers Faced vs ${opponentName}`} rows={data.managersFaced} primary={r=>`${r.matches} ${r.matches===1?'match':'matches'}`} secondary={r=><>{opponentName} manager appearances</>} maxValue={r=>r.matches??0} kind="opponent" opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Red Cards vs ${opponentName}`} rows={data.redCards} primary={r=>`${r.redCards} RC`} secondary={r=><>{r.recipientType||'Leeds recipient'}</>} maxValue={r=>r.redCards??0} opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Most Hat-Tricks vs ${opponentName}`} rows={data.hatTricks} primary={r=>`${r.hatTricks} ${r.hatTricks===1?'hat-trick':'hat-tricks'}`} secondary={r=><>Best return: {r.maxGoals} goals</>} maxValue={r=>r.hatTricks??0} opponentName={opponentName} opponentCrest={opponentCrest}/>
<Widget title={`Most Clean Sheets vs ${opponentName}`} rows={data.cleanSheets} primary={r=>`${r.cleanSheets} CS`} secondary={r=><>{r.appearances} apps · {Number(r.rate??0).toFixed(1)}% clean-sheet rate</>} maxValue={r=>r.cleanSheets??0} opponentName={opponentName} opponentCrest={opponentCrest}/>
</div>}
