import React,{useEffect,useState}from'react';
import{ArrowLeft,CalendarDays}from'lucide-react';
import{supabase,supabaseConfigError}from'./supabase';
import ClubCrest from'./ClubCrest';
import OpponentProfileWidgets from'./OpponentProfileWidgets';
import'./OpponentPage.css';

type Club={club_id:number;display_name:string|null;canonical_name:string;crest_url:string|null;country:string|null;founded_year:number|null;nickname:string|null};
type Summary={club_id:number;opponent:string;crest_url:string|null;played:number;won:number;drawn:number;lost:number;goals_for:number;goals_against:number;goal_diff:number;win_pct:number|string;first_meeting:string|null;last_meeting:string|null};
type MatchRow={match_id:number;match_date:string;season:string|null;competition:string|null;venue_type:string|null;leeds_score:number;opponent_score:number;result:string|null;stadium:string|null;attendance:number|null;round:string|null;red_cards?:number;red_cards_against?:number};
type RedCardRow={match_id:number;side:string};
type Analysis={scope:string;competition:string|null;matches_played:number;won:number;drawn:number;lost:number;goals_for:number;goals_against:number;goal_difference:number;clean_sheets:number;failed_to_score:number;win_rate:number|string;loss_rate:number|string;red_cards:number;red_cards_against:number};
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00Z`)):'—';
const venueLabel=(v:string|null)=>v==='H'?'Home':v==='A'?'Away':v==='N'?'Neutral':v||'—';
const fmt=(v:number|string,pct=false)=>pct?`${Number(v).toFixed(1)}%`:Number(v).toLocaleString('en-GB');
function EventIcon({count,label}:{count:number;label:string}){return <span className="player-match-event" title={label} aria-label={label}><img src="/appicons/Red%20Card%20Icon2.png" alt="" aria-hidden="true"/>{count>1?<span className="player-match-event-count">×{count}</span>:null}</span>}
export default function OpponentPage({clubId,onBack}:{clubId:number;onBack:()=>void}){
 const[club,setClub]=useState<Club|null>(null),[summary,setSummary]=useState<Summary|null>(null),[matches,setMatches]=useState<MatchRow[]>([]),[analysis,setAnalysis]=useState<Analysis[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;(async()=>{setLoading(true);setError(null);const[{data:c,error:ce},{data:s,error:se},{data:m,error:me},{data:a,error:ae}]=await Promise.all([supabase!.from('clubs').select('club_id,display_name,canonical_name,crest_url,country,founded_year,nickname').eq('club_id',clubId).single(),supabase!.from('opponent_profile_summary').select('*').eq('club_id',clubId).single(),supabase!.from('opponent_match_history').select('match_id,match_date,season,competition,venue_type,leeds_score,opponent_score,result,stadium,attendance,round').eq('club_id',clubId).order('match_date',{ascending:false}),supabase!.rpc('opponent_profile_analysis_v1',{p_club_id:clubId})]);const firstError=ce||se||me||ae;if(firstError){if(!cancelled){setError(firstError.message);setLoading(false)}return}const matchRows=(m??[])as MatchRow[],matchIds=matchRows.map(r=>r.match_id);let redCards:RedCardRow[]=[];if(matchIds.length){const{data:r,error:re}=await supabase!.from('red_card_events').select('match_id,side').in('match_id',matchIds);if(re){if(!cancelled){setError(re.message);setLoading(false)}return}redCards=(r??[])as RedCardRow[]}const cardCounts=new Map<number,{for:number;against:number}>();for(const card of redCards){const current=cardCounts.get(card.match_id)??{for:0,against:0};if(card.side==='Leeds')current.for++;if(card.side==='Opponent')current.against++;cardCounts.set(card.match_id,current)}const enriched=matchRows.map(row=>({...row,red_cards:cardCounts.get(row.match_id)?.for??0,red_cards_against:cardCounts.get(row.match_id)?.against??0}));if(!cancelled){setClub(c as Club);setSummary(s as Summary);setMatches(enriched);setAnalysis((a??[])as Analysis[]);setLoading(false)}})();return()=>{cancelled=true}},[clubId]);
 if(loading)return <div className="card opponent-profile-state">Loading opponent profile…</div>;if(error||!club||!summary)return <div className="card opponent-profile-state"><strong>Opponent profile could not load.</strong><span>{error||'Opponent not found.'}</span><button onClick={onBack}>Back to Opponents</button></div>;
 const name=club.display_name||club.canonical_name||summary.opponent,overall=analysis.find(a=>a.scope==='overall'),competitions=analysis.filter(a=>a.scope==='competition').sort((a,b)=>Number(b.matches_played)-Number(a.matches_played));
 const metrics=overall?[['Matches Played',overall.matches_played],['Won',overall.won],['Drawn',overall.drawn],['Lost',overall.lost],['Goals',overall.goals_for],['Conceded',overall.goals_against],['Goal Difference',`${Number(overall.goal_difference)>0?'+':''}${overall.goal_difference}`],['Clean Sheets',overall.clean_sheets],["Failed to Score ('0' For)",overall.failed_to_score],['Win Rate',fmt(overall.win_rate,true)],['Loss Rate',fmt(overall.loss_rate,true)],['Red Cards',overall.red_cards],['Red Cards Against',overall.red_cards_against]]:[];
 return <div className="opponent-profile-page"><button type="button" className="opponent-back" onClick={onBack}><ArrowLeft size={14}/> Back to Opponents</button><section className="card opponent-hero"><div className="opponent-hero-identity"><div className="opponent-hero-crest"><ClubCrest crestUrl={club.crest_url||summary.crest_url} name={name}/></div><div><span className="section-kicker">Opponent Profile</span><h1>{name}</h1><div className="opponent-identity-meta"><span className="opponent-country-meta">{club.country?<img className="nationality-flag opponent-country-flag" src={`/flags/${encodeURIComponent(club.country)}.png`} alt={`${club.country} flag`}/>:null}{club.country||'Country unknown'}</span><span>Founded {club.founded_year??'—'}</span><span>{club.nickname||'Nickname unknown'}</span></div></div></div><div className="opponent-record"><small>LEEDS RECORD</small><strong className="opponent-record-line"><span className="opponent-record-w">W{summary.won}</span><span className="opponent-record-d">D{summary.drawn}</span><span className="opponent-record-l">L{summary.lost}</span></strong><span>W - D - L</span></div></section>
 <section className="opponent-analysis-grid"><div className="card opponent-career"><div className="opponent-analysis-head"><span className="section-kicker">Career Overview</span><h2>Leeds Record Metrics</h2></div>{metrics.map(([label,value],i)=><div className="opponent-metric-row" key={String(label)}><div className="opponent-metric-label">{label}</div><div className="opponent-metric-line"><span className={`opponent-metric-fill ${i===11?'danger':''}`} style={{width:`${Math.max(1,Math.min(100,Number(typeof value==='string'?value.replace(/[+%]/g,''):value)/Math.max(1,Number(overall?.matches_played))*100))}%`}}/></div><strong>{value}</strong></div>)}</div><div className="card opponent-competition"><div className="opponent-analysis-head competition"><div><span className="section-kicker">Career Analysis</span><h2>Competition Breakdown</h2></div><span className="section-kicker">{competitions.length} Competitions</span></div>{competitions.map(c=><div className="opponent-comp-row" key={c.competition||'Unknown'}><div className="opponent-comp-top"><strong>{c.competition||'Unknown'}</strong><b>{fmt(c.win_rate,true)}</b></div><div className="opponent-comp-sub">{c.matches_played} matches · {c.won} won · {c.drawn} drawn · {c.lost} lost · {c.goals_for}-{c.goals_against} goals</div><div className="opponent-comp-rate"><span style={{width:`${Math.max(1,Number(c.win_rate))}%`}}/></div><small>Win rate</small></div>)}</div></section>
 <OpponentProfileWidgets clubId={clubId} opponentName={name} opponentCrest={club.crest_url||summary.crest_url}/>
 <section className="card opponent-meetings player-match-log"><div className="player-profile-panelhead player-match-log-head"><div><span className="section-kicker">Head to head</span><h2>Competitive Meetings</h2></div><div className="opponent-meeting-range"><span><CalendarDays size={13}/> First {dateLabel(summary.first_meeting)}</span><span>Last {dateLabel(summary.last_meeting)}</span></div></div><div className="lb-table-wrap"><table className="lb-table player-match-log-table opponent-match-log-table"><thead><tr><th>Date</th><th>Season</th><th>Competition</th><th>Venue</th><th>Score</th><th>Result</th><th>Round</th><th className="col-stat" title="Leeds red cards">RC</th><th className="col-stat" title="Opponent red cards">RC Against</th></tr></thead><tbody>{matches.map(row=><tr key={row.match_id}><td className="player-match-date">{dateLabel(row.match_date)}</td><td className="player-match-season">{row.season||'—'}</td><td>{row.competition||'—'}</td><td><span className="player-match-venue" title={venueLabel(row.venue_type)}>{row.venue_type||'—'}</span></td><td className="player-match-score">{row.leeds_score}–{row.opponent_score}</td><td><span className={`player-match-result ${row.result==='Won'?'win':row.result==='Lost'?'loss':'draw'}`}>{row.result==='Won'?'W':row.result==='Lost'?'L':'D'}</span></td><td>{row.round||'—'}</td><td className="col-stat player-match-event-cell">{row.red_cards?<EventIcon count={row.red_cards} label={`${row.red_cards} Leeds red card${row.red_cards===1?'':'s'}`}/>:<span className="player-match-event-empty">—</span>}</td><td className="col-stat player-match-event-cell">{row.red_cards_against?<EventIcon count={row.red_cards_against} label={`${row.red_cards_against} opponent red card${row.red_cards_against===1?'':'s'}`}/>:<span className="player-match-event-empty">—</span>}</td></tr>)}</tbody></table></div></section></div>;
}
