import React,{useEffect,useMemo,useState}from'react';
import{supabase,supabaseConfigError}from'./supabase';
import'./PlayerSeasonLog.css';

type PlayerMatch={match_id:number;started:boolean;substitute:boolean};
type MatchRow={match_id:number;match_date:string;season_id:number|null;competition_id:number|null;competition_name_id:number|null;result:string};
type SeasonRow={season_id:number;display_name:string;start_year:number};
type CompetitionRow={competition_id:number;canonical_name:string};
type CompetitionNameRow={competition_name_id:number;display_name:string};
type GoalRow={match_id:number;leeds_player_id:number|null;assist_player_id:number|null;is_own_goal:boolean};
type SubRow={match_id:number;player_off_id:number|null;player_on_id:number|null};
type SeasonStat={seasonId:number;season:string;startYear:number;apps:number;starts:number;subbedOn:number;subbedOff:number;goals:number;assists:number|null;wins:number;draws:number;losses:number;winPct:number;gpg:number};

const ASSIST_DATA_START='1989-08-19';

export default function PlayerSeasonLog({playerId}:{playerId:number}){
 const[rows,setRows]=useState<SeasonStat[]>([]),[competitions,setCompetitions]=useState<{id:number;name:string}[]>([]),[selected,setSelected]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);
  const{data:pm,error:pmError}=await supabase.from('player_matches').select('match_id,started,substitute').eq('player_id',playerId);if(pmError){if(!cancelled){setError(pmError.message);setLoading(false)}return}const playerMatches=(pm??[])as PlayerMatch[];const matchIds=playerMatches.map(r=>r.match_id);if(!matchIds.length){if(!cancelled){setRows([]);setCompetitions([]);setLoading(false)}return}
  const[{data:matches,error:matchError},{data:scored,error:scoredError},{data:assisted,error:assistedError},{data:subOff,error:subOffError},{data:subOn,error:subOnError}]=await Promise.all([
   supabase.from('matches').select('match_id,match_date,season_id,competition_id,competition_name_id,result').in('match_id',matchIds),
   supabase.from('goals').select('match_id,leeds_player_id,assist_player_id,is_own_goal').eq('leeds_player_id',playerId).eq('is_own_goal',false).in('match_id',matchIds),
   supabase.from('goals').select('match_id,leeds_player_id,assist_player_id,is_own_goal').eq('assist_player_id',playerId).in('match_id',matchIds),
   supabase.from('match_substitutions').select('match_id,player_off_id,player_on_id').eq('player_off_id',playerId).in('match_id',matchIds),
   supabase.from('match_substitutions').select('match_id,player_off_id,player_on_id').eq('player_on_id',playerId).in('match_id',matchIds)
  ]);const firstError=matchError??scoredError??assistedError??subOffError??subOnError;if(firstError){if(!cancelled){setError(firstError.message);setLoading(false)}return}
  const matchRows=(matches??[])as MatchRow[],seasonIds=Array.from(new Set(matchRows.map(m=>m.season_id).filter((v):v is number=>v!=null))),competitionIds=Array.from(new Set(matchRows.map(m=>m.competition_id).filter((v):v is number=>v!=null))),competitionNameIds=Array.from(new Set(matchRows.map(m=>m.competition_name_id).filter((v):v is number=>v!=null)));
  const[{data:seasonData,error:seasonError},{data:competitionData,error:competitionError},{data:competitionNameData,error:competitionNameError}]=await Promise.all([
   seasonIds.length?supabase.from('seasons').select('season_id,display_name,start_year').in('season_id',seasonIds):Promise.resolve({data:[],error:null}),
   competitionIds.length?supabase.from('competitions').select('competition_id,canonical_name').in('competition_id',competitionIds):Promise.resolve({data:[],error:null}),
   competitionNameIds.length?supabase.from('competition_names').select('competition_name_id,display_name').in('competition_name_id',competitionNameIds):Promise.resolve({data:[],error:null})
  ]);const metaError=seasonError??competitionError??competitionNameError;if(metaError){if(!cancelled){setError(metaError.message);setLoading(false)}return}
  const seasonMap=new Map(((seasonData??[])as SeasonRow[]).map(s=>[s.season_id,s])),competitionMap=new Map(((competitionData??[])as CompetitionRow[]).map(c=>[c.competition_id,c.canonical_name])),competitionNameMap=new Map(((competitionNameData??[])as CompetitionNameRow[]).map(c=>[c.competition_name_id,c.display_name])),pmMap=new Map(playerMatches.map(p=>[p.match_id,p]));
  const goalCount=new Map<number,number>();for(const g of(scored??[])as GoalRow[])goalCount.set(g.match_id,(goalCount.get(g.match_id)??0)+1);const assistCount=new Map<number,number>();for(const g of(assisted??[])as GoalRow[])assistCount.set(g.match_id,(assistCount.get(g.match_id)??0)+1);const offSet=new Set(((subOff??[])as SubRow[]).map(s=>s.match_id)),onSet=new Set(((subOn??[])as SubRow[]).map(s=>s.match_id));
  const availableCompetitions=competitionIds.map(id=>({id,name:competitionMap.get(id)??`Competition ${id}`})).sort((a,b)=>a.name.localeCompare(b.name));
  const build=(competitionId:number|null)=>{const grouped=new Map<number,{matches:MatchRow[]}>();for(const m of matchRows){if(m.season_id==null||(competitionId!=null&&m.competition_id!==competitionId))continue;const current=grouped.get(m.season_id)??{matches:[]};current.matches.push(m);grouped.set(m.season_id,current)}return Array.from(grouped.entries()).map(([seasonId,g])=>{const season=seasonMap.get(seasonId),apps=g.matches.length,starts=g.matches.filter(m=>pmMap.get(m.match_id)?.started).length,subbedOn=g.matches.filter(m=>onSet.has(m.match_id)||pmMap.get(m.match_id)?.substitute).length,subbedOff=g.matches.filter(m=>offSet.has(m.match_id)).length,goals=g.matches.reduce((n,m)=>n+(goalCount.get(m.match_id)??0),0),wins=g.matches.filter(m=>m.result==='Won').length,draws=g.matches.filter(m=>m.result==='Draw').length,losses=apps-wins-draws,hasAssistCoverage=g.matches.some(m=>m.match_date>=ASSIST_DATA_START),assists=hasAssistCoverage?g.matches.reduce((n,m)=>n+(assistCount.get(m.match_id)??0),0):null;return{seasonId,season:season?.display_name??String(seasonId),startYear:season?.start_year??0,apps,starts,subbedOn,subbedOff,goals,assists,wins,draws,losses,winPct:apps?wins/apps*100:0,gpg:apps?goals/apps:0}}).sort((a,b)=>b.startYear-a.startYear)};
  const chosen=selected==='all'?null:Number(selected);if(!cancelled){setCompetitions(availableCompetitions);setRows(build(chosen));setLoading(false)}})();return()=>{cancelled=true}},[playerId,selected]);
 const selectedCompetition=useMemo(()=>selected==='all'?'All Competitions':competitions.find(c=>String(c.id)===selected)?.name??'Competition',[selected,competitions]);
 return <section className="card player-profile-panel player-season-log"><div className="player-profile-panelhead"><div><span className="section-kicker">Leeds United Career Chronology</span><h2>Season Log</h2></div><select className="lb-filter-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="all">All Competitions</option>{competitions.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{loading?<div className="lb-loading">Loading season log…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:<div className="lb-table-wrap"><table className="lb-table player-season-table"><thead><tr><th>Season</th><th>Club</th><th>Competition</th><th className="col-stat">Apps</th><th className="col-stat">Starts</th><th className="col-stat">Subbed On</th><th className="col-stat">Subbed Off</th><th className="col-stat">Goals</th><th className="col-stat">Assists</th><th className="col-stat">GPG</th><th className="col-stat">W</th><th className="col-stat">D</th><th className="col-stat">L</th><th className="col-metric">Win %</th></tr></thead><tbody>{rows.map(r=><tr key={r.seasonId}><td><span className="team-name">{r.season}</span></td><td><span className="player-season-club"><img src="/Leeds.png" alt="Leeds United"/> <strong>Leeds</strong></span></td><td><span className="player-season-competition">{selectedCompetition}</span></td><td className="col-stat player-stat-value">{r.apps}</td><td className="col-stat player-stat-value">{r.starts}</td><td className="col-stat player-stat-value">{r.subbedOn}</td><td className="col-stat player-stat-value">{r.subbedOff}</td><td className="col-stat player-stat-value">{r.goals}</td><td className="col-stat player-stat-value">{r.assists??'—'}</td><td className="col-stat player-stat-value">{r.gpg.toFixed(2)}</td><td className="col-stat player-stat-value record-win">{r.wins}</td><td className="col-stat player-stat-value record-draw">{r.draws}</td><td className="col-stat player-stat-value record-loss">{r.losses}</td><td className="col-metric"><div className="metric-cell"><span className="metric-value">{r.winPct.toFixed(1)}%</span><span className="metric-track"><span className="metric-fill win-pct-fill" style={{width:`${r.winPct}%`}}/></span></div></td></tr>)}</tbody></table></div>}</section>
}
