import React,{useEffect,useState}from'react';
import ClubCrest from'./ClubCrest';
import{supabase,supabaseConfigError}from'./supabase';
import'./PlayerCareerMilestones.css';

type PlayerRow={date_of_birth:string|null;birth_date_precision:string|null};
type PlayerMatchRow={match_id:number};
type MatchRow={match_id:number;match_date:string;season_id:number|null;opponent_id:number;competition_id:number|null;competition_name_id:number|null;manager_spell_id:number|null;venue_type:string;leeds_score:number;opponent_score:number;result:string;stadium:string|null};
type GoalRow={match_id:number};
type ClubRow={club_id:number;display_name:string;crest_url:string|null};
type SeasonRow={season_id:number;display_name:string};
type CompetitionRow={competition_id:number;canonical_name:string};
type CompetitionNameRow={competition_name_id:number;display_name:string};
type ManagerSpellRow={manager_spell_id:number;manager_id:number};
type ManagerRow={manager_id:number;canonical_name:string};
type MilestoneRow={kind:string;matchId:number;date:string;season:string;opponent:string;crest:string|null;venue:string;competition:string;result:'W'|'D'|'L';score:string;stadium:string;manager:string;age:string};
type MilestoneSection={title:string;rows:MilestoneRow[]};

const appearanceTargets=[50,100,150,200,250,300,350,400,450,500,550,600,650,700,750];
const goalTargets=[25,50,75,100,125,150,175,200,225];
const formatDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00Z`));
const venueLabel=(v:string)=>v==='H'?'Home':v==='A'?'Away':v==='N'?'Neutral':v;
const resultCode=(result:string):'W'|'D'|'L'=>result==='Won'?'W':result==='Draw'?'D':'L';
function ageAt(dob:string|null,precision:string|null,date:string){if(!dob||precision!=='exact')return'—';const birth=new Date(`${dob}T12:00:00Z`),match=new Date(`${date}T12:00:00Z`);let years=match.getUTCFullYear()-birth.getUTCFullYear();let anniversary=new Date(Date.UTC(match.getUTCFullYear(),birth.getUTCMonth(),birth.getUTCDate(),12));if(match<anniversary){years--;anniversary=new Date(Date.UTC(match.getUTCFullYear()-1,birth.getUTCMonth(),birth.getUTCDate(),12))}const days=Math.floor((match.getTime()-anniversary.getTime())/86400000);return`${years}y ${days}d`}
function ordinal(n:number){const mod100=n%100;if(mod100>=11&&mod100<=13)return`${n}th`;switch(n%10){case 1:return`${n}st`;case 2:return`${n}nd`;case 3:return`${n}rd`;default:return`${n}th`}}

export default function PlayerCareerMilestones({playerId}:{playerId:number}){
 const[sections,setSections]=useState<MilestoneSection[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);
  const[{data:pm,error:pmError},{data:player,error:playerError}]=await Promise.all([supabase.from('player_matches').select('match_id').eq('player_id',playerId),supabase.from('players').select('date_of_birth,birth_date_precision').eq('player_id',playerId).maybeSingle()]);
  if(pmError||playerError){if(!cancelled){setError((pmError??playerError)?.message??'Unable to load career milestones');setLoading(false)}return}
  const matchIds=((pm??[])as PlayerMatchRow[]).map(r=>r.match_id);if(!matchIds.length){if(!cancelled){setSections([]);setLoading(false)}return}
  const[{data:matches,error:matchError},{data:goals,error:goalError}]=await Promise.all([supabase.from('matches').select('match_id,match_date,season_id,opponent_id,competition_id,competition_name_id,manager_spell_id,venue_type,leeds_score,opponent_score,result,stadium').in('match_id',matchIds),supabase.from('goals').select('match_id').eq('leeds_player_id',playerId).eq('is_own_goal',false).in('match_id',matchIds)]);
  if(matchError||goalError){if(!cancelled){setError((matchError??goalError)?.message??'Unable to load milestone matches');setLoading(false)}return}
  const matchRows=(matches??[])as MatchRow[];const ordered=[...matchRows].sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id);const matchMap=new Map(ordered.map(m=>[m.match_id,m]));const goalCounts=new Map<number,number>();for(const g of (goals??[])as GoalRow[])goalCounts.set(g.match_id,(goalCounts.get(g.match_id)??0)+1);const orderedGoalMatches:MatchRow[]=[];for(const m of ordered){const count=goalCounts.get(m.match_id)??0;for(let i=0;i<count;i++)orderedGoalMatches.push(m)}
  const appearanceSelected:[string,MatchRow|undefined][]=[['Leeds Debut',ordered[0]],...appearanceTargets.map(n=>[`${ordinal(n)} App`,ordered[n-1]] as [string,MatchRow|undefined]),['Last App',ordered[ordered.length-1]]];
  const goalSelected:[string,MatchRow|undefined][]=[['First Goal',orderedGoalMatches[0]],...goalTargets.map(n=>[`${ordinal(n)} Goal`,orderedGoalMatches[n-1]] as [string,MatchRow|undefined]),['Last Goal',orderedGoalMatches[orderedGoalMatches.length-1]]];
  const selected=[...appearanceSelected,...goalSelected];const selectedMatches=selected.map(([,m])=>m).filter((m):m is MatchRow=>Boolean(m));const opponentIds=Array.from(new Set(selectedMatches.map(m=>m.opponent_id))),seasonIds=Array.from(new Set(selectedMatches.map(m=>m.season_id).filter((v):v is number=>v!=null))),competitionIds=Array.from(new Set(selectedMatches.map(m=>m.competition_id).filter((v):v is number=>v!=null))),competitionNameIds=Array.from(new Set(selectedMatches.map(m=>m.competition_name_id).filter((v):v is number=>v!=null))),spellIds=Array.from(new Set(selectedMatches.map(m=>m.manager_spell_id).filter((v):v is number=>v!=null)));
  const[{data:clubs,error:clubError},{data:seasons,error:seasonError},{data:competitions,error:competitionError},{data:competitionNames,error:competitionNameError},{data:spells,error:spellError}]=await Promise.all([supabase.from('clubs').select('club_id,display_name,crest_url').in('club_id',opponentIds),seasonIds.length?supabase.from('seasons').select('season_id,display_name').in('season_id',seasonIds):Promise.resolve({data:[],error:null}),competitionIds.length?supabase.from('competitions').select('competition_id,canonical_name').in('competition_id',competitionIds):Promise.resolve({data:[],error:null}),competitionNameIds.length?supabase.from('competition_names').select('competition_name_id,display_name').in('competition_name_id',competitionNameIds):Promise.resolve({data:[],error:null}),spellIds.length?supabase.from('manager_spells').select('manager_spell_id,manager_id').in('manager_spell_id',spellIds):Promise.resolve({data:[],error:null})]);
  if(clubError||seasonError||competitionError||competitionNameError||spellError){if(!cancelled){setError((clubError??seasonError??competitionError??competitionNameError??spellError)?.message??'Unable to load milestone metadata');setLoading(false)}return}
  const managerIds=Array.from(new Set(((spells??[])as ManagerSpellRow[]).map(s=>s.manager_id)));const{data:managers,error:managerError}=managerIds.length?await supabase.from('managers').select('manager_id,canonical_name').in('manager_id',managerIds):{data:[],error:null};if(managerError){if(!cancelled){setError(managerError.message);setLoading(false)}return}
  const clubMap=new Map(((clubs??[])as ClubRow[]).map(r=>[r.club_id,r])),seasonMap=new Map(((seasons??[])as SeasonRow[]).map(r=>[r.season_id,r.display_name])),competitionMap=new Map(((competitions??[])as CompetitionRow[]).map(r=>[r.competition_id,r.canonical_name])),competitionNameMap=new Map(((competitionNames??[])as CompetitionNameRow[]).map(r=>[r.competition_name_id,r.display_name])),spellMap=new Map(((spells??[])as ManagerSpellRow[]).map(r=>[r.manager_spell_id,r.manager_id])),managerMap=new Map(((managers??[])as ManagerRow[]).map(r=>[r.manager_id,r.canonical_name]));const p=(player??null)as PlayerRow|null;
  const build=(items:[string,MatchRow|undefined][])=>items.filter(([,m])=>Boolean(m)).map(([kind,m])=>{const match=matchMap.get((m as MatchRow).match_id)??m as MatchRow,club=clubMap.get(match.opponent_id),managerId=match.manager_spell_id!=null?spellMap.get(match.manager_spell_id):undefined;return{kind,matchId:match.match_id,date:match.match_date,season:match.season_id!=null?(seasonMap.get(match.season_id)??'—'):'—',opponent:club?.display_name??`Club ${match.opponent_id}`,crest:club?.crest_url??null,venue:venueLabel(match.venue_type),competition:(match.competition_name_id!=null?competitionNameMap.get(match.competition_name_id):undefined)??(match.competition_id!=null?competitionMap.get(match.competition_id):undefined)??'—',result:resultCode(match.result),score:`${match.leeds_score}–${match.opponent_score}`,stadium:match.stadium??'—',manager:managerId!=null?(managerMap.get(managerId)??'—'):'—',age:ageAt(p?.date_of_birth??null,p?.birth_date_precision??null,match.match_date)}});
  if(!cancelled){setSections([{title:'Appearances',rows:build(appearanceSelected)},{title:'Goals',rows:build(goalSelected)}]);setLoading(false)}})();return()=>{cancelled=true}},[playerId]);
 const table=(rows:MilestoneRow[])=><div className="lb-table-wrap"><table className="lb-table player-career-milestones-table"><thead><tr><th>Milestone</th><th>Season</th><th>Date</th><th>Opponent</th><th>Venue</th><th>Competition</th><th>Result</th><th>Score</th><th>Stadium</th><th>Leeds Manager</th><th>Player Age</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.kind}-${r.matchId}-${i}`}><td><strong className="player-career-milestone-name">{r.kind}</strong></td><td>{r.season}</td><td className="metric-value">{formatDate(r.date)}</td><td><div className="team-cell"><ClubCrest crestUrl={r.crest} name={r.opponent}/><span className="team-name">{r.opponent}</span></div></td><td>{r.venue}</td><td>{r.competition}</td><td className="player-career-milestone-result-cell"><span className={`player-career-milestone-result result-${r.result.toLowerCase()}`}>{r.result}</span></td><td className="metric-value player-career-milestone-score">{r.score}</td><td>{r.stadium}</td><td>{r.manager}</td><td className="metric-value">{r.age}</td></tr>)}</tbody></table></div>;
 return <section className="card player-career-milestones"><div className="player-career-milestones-head"><span className="section-kicker">Key career matches</span><h2>Leeds United Career Milestones</h2></div>{loading?<div className="lb-loading">Loading career milestones…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:sections.some(s=>s.rows.length)?<div className="player-career-milestone-sections">{sections.map(section=><section className="player-career-milestone-section" key={section.title}><h3>{section.title}</h3>{section.rows.length?table(section.rows):<div className="lb-empty">No {section.title.toLowerCase()} milestones available.</div>}</section>)}</div>:<div className="lb-empty">No career milestone matches available.</div>}</section>
}
