import React from'react';
import{ArrowLeft}from'lucide-react';
import PlayerIcon from'./PlayerIcon';
import NationalityFlag from'./NationalityFlag';
import ClubCrest from'./ClubCrest';
import PlayerCareerMetrics from'./PlayerCareerMetrics';
import PlayerCompetitionBreakdown from'./PlayerCompetitionBreakdown';
import PlayerManagerWidget from'./PlayerManagerWidget';
import PlayerInformation from'./PlayerInformation';
import PlayerOpponentWidgets from'./PlayerOpponentWidgets';
import'./PlayerPage.css';
const stats=[['Apps','772'],['Starts','771'],['Sub Apps','1'],['Sub Off','10'],['Goals','115'],['GPG','0.15'],['Wins','406'],['Win %','52.6%'],['Captain','489'],['Red Cards','3']];
const seasons=[['1959/60',11,11,0,2,4,2,5,36.4],['1960/61',34,34,0,10,10,7,17,29.4],['1961/62',45,45,0,12,14,14,17,31.1],['1962/63',24,24,0,10,10,4,10,41.7],['1963/64',43,43,0,3,24,16,3,55.8],['1964/65',49,49,0,8,31,11,7,63.3],['1965/66',54,54,0,11,29,13,12,53.7],['1966/67',55,54,1,3,31,14,10,56.4],['1967/68',58,58,0,4,34,14,10,58.6],['1968/69',56,56,0,7,34,16,6,60.7],['1969/70',55,55,0,8,30,18,7,54.5],['1970/71',38,38,0,7,23,10,5,60.5],['1971/72',54,54,0,5,32,11,11,59.3],['1972/73',57,57,0,5,30,17,10,52.6],['1973/74',52,52,0,11,28,18,6,53.8],['1974/75',44,44,0,4,20,16,8,45.5],['1975/76',38,38,0,5,21,6,11,55.3],['1976/77',5,5,0,0,1,1,3,20.0]] as const;
const opponents=[['Liverpool','/Liverpool.png',33,5,10,9,14,30.3],['Stoke City','/Stoke City.png',30,6,16,6,8,53.3],['Everton','/Everton.png',29,6,16,8,5,55.2],['Chelsea','/Chelsea.png',28,3,13,8,7,46.4],['Derby County','/Derby.png',26,4,14,9,3,53.8],['Tottenham Hotspur','/Tottenham Hotspur.png',26,5,10,9,7,38.5],['Arsenal','/Arsenal.png',25,3,18,4,3,72.0],['Manchester United','/Manchester United.png',25,5,10,11,4,40.0],['Newcastle United','/Newcastle United.png',25,0,14,5,6,56.0],['Sunderland','/Sunderland.png',23,3,9,8,6,39.1]] as const;
const goalOpponents=[['Stoke City','/Stoke City.png',30,6],['Everton','/Everton.png',29,6],['Liverpool','/Liverpool.png',33,5],['Tottenham Hotspur','/Tottenham Hotspur.png',26,5],['Manchester United','/Manchester United.png',25,5]] as const;
function TeamRecord(){const wins=406,draws=208,losses=158,total=772;const pct=(n:number)=>n/total*100;return <div className="player-team-record"><div className="player-career-panelhead"><div><span className="section-kicker">Team record w/ player</span><h2>Results in Appearances</h2></div><span className="metric-value">772 games</span></div><div className="player-record-bar"><span className="win" style={{width:`${pct(wins)}%`}}/><span className="draw" style={{width:`${pct(draws)}%`}}/><span className="loss" style={{width:`${pct(losses)}%`}}/></div><div className="player-record-stats"><div><span className="player-record-key win"/> <small>Win</small><strong>{wins}</strong><b>{pct(wins).toFixed(1)}%</b></div><div><span className="player-record-key draw"/> <small>Draw</small><strong>{draws}</strong><b>{pct(draws).toFixed(1)}%</b></div><div><span className="player-record-key loss"/> <small>Loss</small><strong>{losses}</strong><b>{pct(losses).toFixed(1)}%</b></div></div></div>}
function OpponentWidget(){return <section className="card player-opponent-widget" style={{width:'100%'}}><div className="player-opponent-widget-head"><div><span className="section-kicker">Opposition analysis</span><h2>Most Appearances vs Clubs</h2></div><span className="section-kicker">Top 5</span></div><div className="player-opponent-widget-list">{opponents.slice(0,5).map(([club,crest,apps,,w,,,winPct])=><div className="player-opponent-widget-row" key={club}><div className="player-opponent-widget-club"><ClubCrest crestUrl={crest} name={club}/><div><strong>{club}</strong><span><b>{w}</b> wins / {apps} appearances</span></div></div><div className="player-opponent-widget-value"><strong>{winPct.toFixed(1)}%</strong><span>Win rate</span></div><div className="player-opponent-widget-track"><i style={{width:`${winPct}%`}}/></div></div>)}</div></section>}
function GoalOpponentWidget(){const maxGoals=Math.max(...goalOpponents.map(([, , ,goals])=>goals));return <section className="card player-opponent-widget" style={{width:'100%'}}><div className="player-opponent-widget-head"><div><span className="section-kicker">Opposition analysis</span><h2>Most Goals vs Clubs</h2></div><span className="section-kicker">Top 5</span></div><div className="player-opponent-widget-list">{goalOpponents.map(([club,crest,apps,goals])=>{const gpg=goals/apps;return <div className="player-opponent-widget-row" key={club}><div className="player-opponent-widget-club"><ClubCrest crestUrl={crest} name={club}/><div><strong>{club}</strong><span><b>{goals}</b> goals / {apps} appearances</span></div></div><div className="player-opponent-widget-value"><strong>{gpg.toFixed(2)}</strong><span>Goals / app</span></div><div className="player-opponent-widget-track"><i style={{width:`${goals/maxGoals*100}%`}}/></div></div>})}</div></section>}
export default function PlayerPage({onBack}:{onBack?:()=>void}){return <div className="player-profile-page"><button className="player-profile-back" onClick={onBack}><ArrowLeft size={13}/> Back to Players</button><section className="card player-profile-hero"><div className="player-profile-portrait"><PlayerIcon name="Billy Bremner" src="/playericons/Billy Bremner Icon.png"/></div><div className="player-profile-identity"><span className="section-kicker">Leeds United player profile · #276</span><h1>Billy Bremner</h1><div className="player-profile-tags"><span className="manager-status-pill former">Former</span><span className="player-profile-position">CM</span><span className="player-profile-nation"><NationalityFlag nation="Scotland"/> Scotland</span></div><p className="player-profile-fullname">William John Bremner</p></div></section><section className="player-profile-statgrid">{stats.map(([label,value])=><div className="card player-profile-stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><PlayerInformation playerId={276}/><div className="player-career-summary-grid"><PlayerCareerMetrics/><PlayerCompetitionBreakdown/></div><div className="player-career-summary-grid player-career-secondary-grid"><PlayerOpponentWidgets playerId={276}/></div><div className="player-career-summary-grid player-career-secondary-grid"><PlayerManagerWidget playerId={276} playerName="Billy Bremner"/><div className="card player-results-card"><TeamRecord/></div></div><section className="card player-profile-panel"><div className="player-profile-panelhead"><div><span className="section-kicker">Leeds United Career Chronology</span><h2>Season Log</h2></div><select className="lb-filter-select"><option>All Competitions</option></select></div><div className="lb-table-wrap"><table className="lb-table player-season-table"><thead><tr><th>Season</th><th className="col-stat">Apps</th><th className="col-stat">Starts</th><th className="col-stat">Sub Apps</th><th className="col-stat">Goals</th><th className="col-stat">W</th><th className="col-stat">D</th><th className="col-stat">L</th><th className="col-metric">Win %</th></tr></thead><tbody>{[...seasons].reverse().map(([season,apps,starts,subs,goals,w,d,l,winPct])=><tr key={season}><td><span className="team-name">{season}</span></td><td className="col-stat player-stat-value">{apps}</td><td className="col-stat player-stat-value">{starts}</td><td className="col-stat player-stat-value">{subs}</td><td className="col-stat player-stat-value">{goals}</td><td className="col-stat player-stat-value record-win">{w}</td><td className="col-stat player-stat-value record-draw">{d}</td><td className="col-stat player-stat-value record-loss">{l}</td><td className="col-metric"><div className="metric-cell"><span className="metric-value">{winPct.toFixed(1)}%</span><span className="metric-track"><span className="metric-fill win-pct-fill" style={{width:`${winPct}%`}}/></span></div></td></tr>)}</tbody></table></div></section></div>}
