import React,{useEffect,useState}from'react';
import{CheckCircle2,LockKeyhole,ShieldCheck,TriangleAlert}from'lucide-react';
import{supabase,supabaseConfigError}from'./supabase';
import'./PlayerAdmin.css';

type Draft={draft_id:number;draft_status:string;display_name:string;full_name:string|null;date_of_birth:string|null;birth_date_precision:string;place_of_birth:string|null;declared_nation:string|null;position_group:string|null;position_detail:string|null;joined_from:string|null;transfer_type:string|null;date_joined_or_turned_pro:string|null;date_joined_or_turned_pro_raw:string|null;date_joined_precision:string|null;profile_image_url:string|null;senior_career_clubs:string|null;start_year:number;source_note:string|null;validation_result:{valid?:boolean;issues?:string[];warnings?:string[]}|null};
const empty={display_name:'',full_name:'',date_of_birth:'',birth_date_precision:'exact',place_of_birth:'',declared_nation:'',position_group:'',position_detail:'',joined_from:'',transfer_type:'Permanent',date_joined_or_turned_pro:'',date_joined_or_turned_pro_raw:'',date_joined_precision:'exact',profile_image_url:'',senior_career_clubs:'',start_year:String(new Date().getFullYear()),source_note:''};
export default function PlayerAdmin(){
 const[session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[form,setForm]=useState({...empty}),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(supabaseConfigError);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const set=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 const signIn=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError(null);const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href}});setBusy(false);if(error)setError(error.message);else setMessage('Secure sign-in link sent. Check your email.')};
 const saveDraft=async()=>{if(!supabase||!session)return;setBusy(true);setError(null);setMessage('');const payload={...form,date_of_birth:form.date_of_birth||null,date_joined_or_turned_pro:form.date_joined_or_turned_pro||null,start_year:Number(form.start_year),full_name:form.full_name||null,place_of_birth:form.place_of_birth||null,declared_nation:form.declared_nation||null,position_group:form.position_group||null,position_detail:form.position_detail||null,joined_from:form.joined_from||null,transfer_type:form.transfer_type||null,date_joined_or_turned_pro_raw:form.date_joined_or_turned_pro_raw||null,date_joined_precision:form.date_joined_precision||null,profile_image_url:form.profile_image_url||null,senior_career_clubs:form.senior_career_clubs||null,source_note:form.source_note||null};const q=draft?supabase.from('player_intake_drafts').update(payload).eq('draft_id',draft.draft_id):supabase.from('player_intake_drafts').insert(payload);const{data,error}=await q.select('*').single();setBusy(false);if(error)setError(error.message);else{setDraft(data as Draft);setMessage('Draft saved safely. Canonical player data has not been touched.')}};
 const validate=async()=>{if(!supabase||!draft)return;setBusy(true);setError(null);const{data,error}=await supabase.rpc('validate_player_intake_draft',{p_draft_id:draft.draft_id});if(!error){const{data:row}=await supabase.from('player_intake_drafts').select('*').eq('draft_id',draft.draft_id).single();setDraft(row as Draft);setMessage(data?.valid?'Validation passed. Review carefully before committing.':'Validation found blocking issues.')}else setError(error.message);setBusy(false)};
 const commit=async()=>{if(!supabase||!draft||draft.draft_status!=='validated')return;if(!window.confirm(`FINAL CONFIRMATION\n\nCreate ${draft.display_name} in the canonical players database and create their active Leeds spell?\n\nThis is the only step that writes to canonical player data.`))return;setBusy(true);setError(null);const{data,error}=await supabase.rpc('commit_player_intake_draft',{p_draft_id:draft.draft_id});setBusy(false);if(error)setError(error.message);else{setDraft(d=>d?{...d,draft_status:'committed'}:d);setMessage(`Player committed successfully. Player ID ${data.player_id} · Legacy ID ${data.legacy_player_id}.`)}};
 if(!session)return <section className="pa-shell"><div className="pa-lock card"><LockKeyhole size={28}/><span>LUFC DATA ADMIN</span><h1>Authorised access only</h1><p>This area is isolated from the public player database. Sign in before any staging data can be created.</p><form onSubmit={signIn}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Authorised email address"/><button disabled={busy}>{busy?'Sending…':'Send secure sign-in link'}</button></form>{message&&<div className="pa-note ok">{message}</div>}{error&&<div className="pa-note bad">{error}</div>}</div></section>;
 const v=draft?.validation_result;
 return <section className="pa-shell"><header className="pa-top"><div><span>LUFC DATA ADMIN</span><h1>Add New Player</h1><p>Staged intake · validation · review · transactional commit</p></div><div className="pa-secure"><ShieldCheck size={17}/>Authenticated</div></header><div className="pa-safety"><LockKeyhole size={16}/><strong>Safe staging mode</strong><span>Saving this form does not write to <code>players</code> or <code>player_spells</code>.</span></div><div className="pa-grid"><div className="card pa-form"><h2>Player details</h2><div className="pa-fields">
 {([['Display Name','display_name','text',true],['Full Name','full_name','text',false],['Date of Birth','date_of_birth','date',false],['Place of Birth','place_of_birth','text',false],['Declared Nation','declared_nation','text',false],['Position Detail','position_detail','text',false],['Joined From','joined_from','text',false],['Joined Date','date_joined_or_turned_pro','date',false],['Joined Date (display)','date_joined_or_turned_pro_raw','text',false],['Profile Image URL','profile_image_url','url',false],['Senior Career Clubs','senior_career_clubs','text',false],['Leeds Start Year','start_year','number',true]] as const).map(([label,key,type,req])=><label key={key}><span>{label}{req?' *':''}</span><input type={type} required={req} value={(form as any)[key]} onChange={e=>set(key,e.target.value)} disabled={draft?.draft_status==='committed'}/></label>)}
 <label><span>Birth Date Precision</span><select value={form.birth_date_precision} onChange={e=>set('birth_date_precision',e.target.value)}><option value="exact">Exact</option><option value="year">Year only</option><option value="unknown">Unknown</option></select></label><label><span>Position Group</span><select value={form.position_group} onChange={e=>set('position_group',e.target.value)}><option value="">Select…</option><option>GK</option><option>DF</option><option>MD</option><option>ST</option></select></label><label><span>Transfer Type</span><select value={form.transfer_type} onChange={e=>set('transfer_type',e.target.value)}><option>Permanent</option><option>Loan</option><option>Loan to Permanent</option><option>Free Transfer</option><option>Academy</option><option>Apprentice</option></select></label><label><span>Joined Date Precision</span><select value={form.date_joined_precision} onChange={e=>set('date_joined_precision',e.target.value)}><option value="exact">Exact</option><option value="month">Month</option><option value="year">Year</option><option value="unknown">Unknown</option></select></label><label className="wide"><span>Source / provenance note</span><textarea value={form.source_note} onChange={e=>set('source_note',e.target.value)} placeholder="Where was this information verified?"/></label></div><button className="pa-primary" onClick={saveDraft} disabled={busy||draft?.draft_status==='committed'}>{draft?'Save Draft Changes':'Save Safe Draft'}</button></div>
 <aside className="card pa-review"><h2>Review & Commit</h2><div className="pa-step"><b>1</b><div><strong>Draft</strong><span>{draft?`#${draft.draft_id} · ${draft.draft_status}`:'Not saved yet'}</span></div></div><div className="pa-step"><b>2</b><div><strong>Validate</strong><span>Checks identity and duplicate risk.</span></div></div><button onClick={validate} disabled={!draft||busy||draft.draft_status==='committed'}>Run Validation</button>{v&&<div className={`pa-validation ${v.valid?'ok':'bad'}`}>{v.valid?<><CheckCircle2 size={16}/><strong>Validation passed</strong></>:<><TriangleAlert size={16}/><strong>Blocking issues</strong></>}{v.issues?.map(x=><p key={x}>{x}</p>)}{v.warnings?.map(x=><p className="warning" key={x}>Warning: {x}</p>)}</div>}<div className="pa-step danger"><b>3</b><div><strong>Final Commit</strong><span>Only this action writes canonical records.</span></div></div><button className="pa-commit" onClick={commit} disabled={!draft||draft.draft_status!=='validated'||busy}>Commit New Player</button>{message&&<div className="pa-note ok">{message}</div>}{error&&<div className="pa-note bad">{error}</div>}<small>Signed in as {session.user.email}</small></aside></div></section>;
}
