import React,{useEffect,useMemo,useState}from'react';
import{supabase,supabaseConfigError}from'./supabase';
import'./PlayerShirtNumberHistory.css';

type ShirtHistoryRow={fact_type:'match_worn'|'official_squad';season_id:number;season:string;match_id:number|null;match_date:string|null;shirt_number:number|null;assignment_status:string|null;notes:string|null};
type SeasonHistory={seasonId:number;season:string;factType:'match_worn'|'official_squad';numbers:number[];records:number;status:string|null;notes:string[]};

function statusLabel(value:string|null){if(!value)return'—';return value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}

export default function PlayerShirtNumberHistory({playerId}:{playerId:number}){
 const[rows,setRows]=useState<ShirtHistoryRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);const{data,error:rpcError}=await supabase.rpc('get_player_shirt_number_history',{p_player_id:playerId});if(cancelled)return;if(rpcError){setError(rpcError.message);setLoading(false);return}setRows((data??[])as ShirtHistoryRow[]);setLoading(false)})();return()=>{cancelled=true}},[playerId]);
 const seasons=useMemo(()=>{const grouped=new Map<string,SeasonHistory>();for(const row of rows){const key=`${row.season_id}:${row.fact_type}`,current=grouped.get(key)??{seasonId:row.season_id,season:row.season,factType:row.fact_type,numbers:[],records:0,status:row.assignment_status,notes:[]};current.records+=1;if(row.shirt_number!=null&&!current.numbers.includes(row.shirt_number))current.numbers.push(row.shirt_number);if(row.notes&&!current.notes.includes(row.notes))current.notes.push(row.notes);if(!current.status&&row.assignment_status)current.status=row.assignment_status;grouped.set(key,current)}return Array.from(grouped.values()).map(r=>({...r,numbers:r.numbers.sort((a,b)=>a-b)})).sort((a,b)=>b.seasonId-a.seasonId)},[rows]);
 if(loading)return <section className="card player-profile-panel player-shirt-history"><div className="player-profile-panelhead"><div><span className="section-kicker">Leeds United Shirt Numbers</span><h2>Shirt Number History</h2></div></div><div className="lb-loading">Loading shirt numbers…</div></section>;
 if(error)return <section className="card player-profile-panel player-shirt-history"><div className="player-profile-panelhead"><div><span className="section-kicker">Leeds United Shirt Numbers</span><h2>Shirt Number History</h2></div></div><div className="lb-loading"><strong>Data connection error:</strong> {error}</div></section>;
 if(!seasons.length)return null;
 return <section className="card player-profile-panel player-shirt-history"><div className="player-profile-panelhead"><div><span className="section-kicker">Leeds United Shirt Numbers</span><h2>Shirt Number History</h2><p className="player-shirt-history-note">1991/92–1992/93 shows match-by-match numbers. From 1993/94, numbers are official seasonal squad assignments.</p></div></div><div className="lb-table-wrap"><table className="lb-table player-shirt-history-table"><thead><tr><th>Season</th><th>Number</th><th>Type</th><th className="col-stat">Selections</th><th>Status</th></tr></thead><tbody>{seasons.map(row=><tr key={`${row.seasonId}:${row.factType}`}><td><span className="team-name">{row.season}</span></td><td><div className="player-shirt-number-list">{row.numbers.length?row.numbers.map(n=><span className="player-shirt-number" key={n}>#{n}</span>):<span className="player-shirt-number unknown">TBC</span>}</div></td><td><span className={`player-shirt-type ${row.factType==='official_squad'?'official':'match'}`}>{row.factType==='official_squad'?'Official Squad':'Match-by-Match'}</span></td><td className="col-stat player-stat-value">{row.factType==='match_worn'?row.records:'—'}</td><td><span className="player-shirt-status">{row.factType==='official_squad'?statusLabel(row.status):'—'}</span></td></tr>)}</tbody></table></div></section>
}
