import React,{useEffect,useMemo,useState}from'react';
import{Search}from'lucide-react';
import{supabase,supabaseConfigError}from'./supabase';
import ClubCrest from'./ClubCrest';

type Side='Leeds'|'Opponent';
type VenueFilter='All'|'Home'|'Away'|'Neutral';
type RedCardRow={
 red_card_event_id:string;side:Side;source_order:number;match_id:number;recipient_name:string;recipient_type:string;player_id:number|null;manager_id:number|null;minute_raw:string|null;issued:string|null;additional_information:string|null;source_file:string;match_date:string;season:string|null;opponent:string;opponent_crest_url:string|null;competition:string;venue_type:string;leeds_score:number;opponent_score:number;result:string;stadium:string|null;leeds_manager:string|null;referee:string|null;
};
const PAGE_SIZE=1000;
const ROWS_PER_PAGE=50;
const venueLabel=(v:string)=>v==='H'?'Home':v==='A'?'Away':'Neutral';
const resultCode=(r:string)=>r==='Won'?'W':r==='Draw'?'D':'L';
const prettyDate=(d:string)=>new Date(`${d}T00:00:00Z`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});
const displayScore=(r:RedCardRow)=>r.venue_type==='A'?`${r.opponent_score}–${r.leeds_score}`:`${r.leeds_score}–${r.opponent_score}`;
async function loadAll(){if(!supabase)return[] as RedCardRow[];const out:RedCardRow[]=[];for(let start=0;;start+=PAGE_SIZE){const{data,error}=await supabase.from('red_card_events').select('*').order('match_date',{ascending:false}).order('source_order',{ascending:false}).range(start,start+PAGE_SIZE-1);if(error)throw error;out.push(...((data??[])as RedCardRow[]));if((data??[]).length<PAGE_SIZE)break}return out}
function topValue(rows:readonly RedCardRow[],value:(r:RedCardRow)=>string){const counts=new Map<string,number>();for(const r of rows){const key=value(r);if(key)counts.set(key,(counts.get(key)??0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]??null}

export default function RedCards({onSelectMatch,onSelectPlayer,onSelectManager}:{onSelectMatch:(matchId:number)=>void;onSelectPlayer:(playerId:number,playerName:string)=>void;onSelectManager:(managerId:number)=>void}){
 const[rows,setRows]=useState<RedCardRow[]>([]),[side,setSide]=useState<Side>('Leeds'),[search,setSearch]=useState(''),[competition,setCompetition]=useState('All Comps'),[venue,setVenue]=useState<VenueFilter>('All'),[opponent,setOpponent]=useState('All Opponents'),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let dead=false;(async()=>{try{const data=await loadAll();if(!dead)setRows(data)}catch(e){if(!dead)setError(e instanceof Error?e.message:String(e))}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[]);
 const competitions=useMemo(()=>Array.from(new Set(rows.map(r=>r.competition))).sort(),[rows]);
 const opponents=useMemo(()=>Array.from(new Set(rows.map(r=>r.opponent))).sort(),[rows]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>r.side===side&&(competition==='All Comps'||r.competition===competition)&&(venue==='All'||venueLabel(r.venue_type)===venue)&&(opponent==='All Opponents'||r.opponent===opponent)&&(!q||r.recipient_name.toLowerCase().includes(q)||r.opponent.toLowerCase().includes(q)||(r.leeds_manager??'').toLowerCase().includes(q)||(r.referee??'').toLowerCase().includes(q)||(r.season??'').toLowerCase().includes(q)))},[rows,side,competition,venue,opponent,search]);
 const summary=useMemo(()=>{const matchMap=new Map<number,RedCardRow>();for(const r of visible)matchMap.set(r.match_id,r);const matches=[...matchMap.values()],w=matches.filter(r=>r.result==='Won').length,d=matches.filter(r=>r.result==='Draw').length,l=matches.filter(r=>r.result==='Lost').length;const perMatch=new Map<number,number>();for(const r of visible)perMatch.set(r.match_id,(perMatch.get(r.match_id)??0)+1);const multiple=[...perMatch.values()].filter(n=>n>1).length;return{matches:matches.length,w,d,l,multiple,recipient:topValue(visible,r=>`${r.recipient_name}|||${r.recipient_type}`),opponent:topValue(visible,r=>r.opponent),competition:topValue(visible,r=>r.competition)}} ,[visible]);
 useEffect(()=>setPage(1),[side,competition,venue,opponent,search]);
 const pageCount=Math.max(1,Math.ceil(visible.length/ROWS_PER_PAGE)),safePage=Math.min(page,pageCount),pageRows=visible.slice((safePage-1)*ROWS_PER_PAGE,safePage*ROWS_PER_PAGE),pageStart=visible.length?(safePage-1)*ROWS_PER_PAGE+1:0,pageEnd=Math.min(safePage*ROWS_PER_PAGE,visible.length);
 const recipient=(r:RedCardRow)=>r.player_id?<button className="rc-link" onClick={()=>onSelectPlayer(r.player_id!,r.recipient_name)}>{r.recipient_name}</button>:r.manager_id?<button className="rc-link" onClick={()=>onSelectManager(r.manager_id!)}>{r.recipient_name}</button>:<span>{r.recipient_name}</span>;
 const topRecipient=summary.recipient?summary.recipient[0].split('|||')[0]:'—';
 return <div className="card lb-table-card rc-card">
  <div className="lb-table-header rc-header"><div className="lb-title-group"><span className="section-kicker">Leeds United history</span><h2>Red Cards</h2><p>Canonical Leeds United and opposition dismissal archive</p></div><div className="rc-segment" role="group" aria-label="Red card side"><button className={side==='Leeds'?'active':''} onClick={()=>setSide('Leeds')}>Leeds Red Cards</button><button className={side==='Opponent'?'active':''} onClick={()=>setSide('Opponent')}>Opponent Red Cards</button></div></div>
  <div className="lb-filterbar rc-filterbar"><div className="lb-filter-section"><span className="lb-filter-label">Competition</span><select className="lb-filter-select" value={competition} onChange={e=>setCompetition(e.target.value)}><option>All Comps</option>{competitions.map(c=><option key={c}>{c}</option>)}</select></div><div className="lb-filter-section lb-venue-section"><span className="lb-filter-label">Venue</span><div className="lb-filter-pills"><button className={`lb-filter-pill ${venue==='All'?'active':''}`} onClick={()=>setVenue('All')}>All</button>{(['Home','Away','Neutral']as VenueFilter[]).map(v=><button key={v} className={`lb-filter-pill ${venue===v?'active':''}`} onClick={()=>setVenue(v)}>{v}</button>)}</div></div><div className="lb-filter-section"><span className="lb-filter-label">Opponent</span><select className="lb-filter-select" value={opponent} onChange={e=>setOpponent(e.target.value)}><option>All Opponents</option>{opponents.map(x=><option key={x}>{x}</option>)}</select></div><label className="rc-search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search recipient, manager, referee…"/></label><span className="section-kicker rc-count">{loading?'…':visible.length} shown</span></div>
  {!loading&&!error&&<div className="rc-summary" aria-label={`${side} red card summary`}><div className="rc-summary-card"><span>Red Cards</span><strong>{visible.length}</strong><small>{side==='Leeds'?'Leeds dismissals':'Opposition dismissals'}</small></div><div className="rc-summary-card"><span>Matches</span><strong>{summary.matches}</strong><small>{summary.multiple} with multiple dismissals</small></div><div className="rc-summary-card"><span>Match Record</span><strong>W{summary.w} D{summary.d} L{summary.l}</strong><small>Distinct matches containing a red card</small></div><div className="rc-summary-card"><span>Most Cards</span><strong>{topRecipient}</strong><small>{summary.recipient?`${summary.recipient[1]} red card${summary.recipient[1]===1?'':'s'}`:'—'}</small></div><div className="rc-summary-card"><span>Most vs Club</span><strong>{summary.opponent?.[0]??'—'}</strong><small>{summary.opponent?`${summary.opponent[1]} red card${summary.opponent[1]===1?'':'s'}`:'—'}</small></div><div className="rc-summary-card"><span>Most in Competition</span><strong>{summary.competition?.[0]??'—'}</strong><small>{summary.competition?`${summary.competition[1]} red card${summary.competition[1]===1?'':'s'}`:'—'}</small></div></div>}
  {error?<div className="rc-state">{error}</div>:loading?<div className="rc-state">Loading red cards…</div>:<div className="lb-table-wrap"><table className="lb-table rc-table"><thead><tr><th>#</th><th>Date</th><th>Recipient</th><th>Type</th><th>Min</th><th>Opponent</th><th>W/D/L</th><th>Score</th><th>Venue</th><th>Competition</th><th>Leeds Manager</th><th>Referee</th></tr></thead><tbody>{pageRows.map(r=><tr key={r.red_card_event_id}><td className="rc-order">{r.source_order}</td><td><button className="rc-link rc-date" onClick={()=>onSelectMatch(r.match_id)}>{prettyDate(r.match_date)}</button></td><td className="rc-recipient">{recipient(r)}</td><td><span className={`rc-type ${r.recipient_type==='Manager'?'manager':''}`}>{r.recipient_type==='Opponent Player'?'Player':r.recipient_type}</span></td><td className="rc-minute">{r.minute_raw||'—'}</td><td><button className="rc-opponent" onClick={()=>onSelectMatch(r.match_id)}><ClubCrest opponent={r.opponent} crestUrl={r.opponent_crest_url}/><span>{r.opponent}</span></button></td><td><span className={`form-pill form-${resultCode(r.result).toLowerCase()}`}>{resultCode(r.result)}</span></td><td className="rc-score">{displayScore(r)}</td><td>{venueLabel(r.venue_type)}</td><td>{r.competition}</td><td>{r.leeds_manager||'—'}</td><td>{r.referee||'—'}</td></tr>)}</tbody></table></div>}
  {!loading&&!error&&<div className="rc-footer"><span>{pageStart}–{pageEnd} of {visible.length}</span><div><button disabled={safePage<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>Previous</button><span>Page {safePage} of {pageCount}</span><button disabled={safePage>=pageCount} onClick={()=>setPage(p=>Math.min(pageCount,p+1))}>Next</button></div></div>}
 </div>;
}
