import React,{useEffect,useMemo,useState}from'react';
import{Search}from'lucide-react';
import{supabase,supabaseConfigError}from'./supabase';
import ClubCrest from'./ClubCrest';
import TimeRangeFilter,{AFT_VALUE,eventMinuteValue}from'./TimeRangeFilter';

type Side='Leeds'|'Opponent';
type VenueFilter='All'|'Home'|'Away'|'Neutral';
type ResultFilter='All Results'|'Won'|'Draw'|'Lost';
type SortKey='order'|'date'|'recipient'|'type'|'age'|'minute'|'opponent'|'wdl'|'score'|'venue'|'competition'|'manager'|'referee';
type SortDirection='asc'|'desc';
type PlayerAgeRow={player_id:number;date_of_birth:string|null;birth_date_precision:string|null};
type RedCardRow={
 red_card_event_id:string;side:Side;source_order:number;match_id:number;recipient_name:string;recipient_type:string;player_id:number|null;manager_id:number|null;minute_raw:string|null;issued:string|null;additional_information:string|null;source_file:string;match_date:string;season:string|null;opponent:string;opponent_crest_url:string|null;competition:string;venue_type:string;leeds_score:number;opponent_score:number;result:string;stadium:string|null;leeds_manager:string|null;referee:string|null;
};
const PAGE_SIZE=1000;
const venueLabel=(v:string)=>v==='H'?'Home':v==='A'?'Away':'Neutral';
const resultCode=(r:string):'W'|'D'|'L'=>r==='Won'?'W':r==='Draw'?'D':'L';
const prettyDate=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('en-GB');
const displayScore=(r:RedCardRow)=>r.venue_type==='A'?`${r.opponent_score}–${r.leeds_score}`:`${r.leeds_score}–${r.opponent_score}`;
const minuteSortValue=(raw:string|null)=>eventMinuteValue(raw);
function ageAt(dob:string|null|undefined,precision:string|null|undefined,matchDate:string){if(!dob||precision==='year'||precision==='approximate')return'—';const birth=new Date(`${dob}T00:00:00Z`),match=new Date(`${matchDate}T00:00:00Z`);if(Number.isNaN(birth.getTime())||Number.isNaN(match.getTime())||match<birth)return'—';let years=match.getUTCFullYear()-birth.getUTCFullYear();let birthday=new Date(Date.UTC(match.getUTCFullYear(),birth.getUTCMonth(),birth.getUTCDate()));if(match<birthday){years--;birthday=new Date(Date.UTC(match.getUTCFullYear()-1,birth.getUTCMonth(),birth.getUTCDate()))}const days=Math.floor((match.getTime()-birthday.getTime())/86400000);return`${years}y ${days}d`}
function ageSortValue(age:string){const m=/^(\d+)y\s+(\d+)d$/.exec(age);return m?Number(m[1])*366+Number(m[2]):null}
function compareNullable(a:string|number|null,b:string|number|null,direction:SortDirection){if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return-1;const base=typeof a==='number'&&typeof b==='number'?a-b:String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:'base'});return direction==='asc'?base:-base}
function DismissalIcon({issued}:{issued:string|null}){const value=(issued??'').trim().toLowerCase();if(value==='second yellow')return <img src="/appicons/YellowRedCard.png" alt="Second yellow" title="Second Yellow" style={{width:18,height:18,objectFit:'contain',display:'block',margin:'0 auto'}}/>;if(value==='straight red'||value==='straight red card')return <img src="/appicons/RedCard.png" alt="Straight red" title="Straight Red" style={{width:18,height:18,objectFit:'contain',display:'block',margin:'0 auto'}}/>;return <span aria-label="Card type unavailable">—</span>}
async function loadAll(){if(!supabase)return[] as RedCardRow[];const out:RedCardRow[]=[];for(let start=0;;start+=PAGE_SIZE){const{data,error}=await supabase.from('red_card_events').select('*').order('match_date',{ascending:false}).order('source_order',{ascending:false}).range(start,start+PAGE_SIZE-1);if(error)throw error;out.push(...((data??[])as RedCardRow[]));if((data??[]).length<PAGE_SIZE)break}return out}
function topValue(rows:readonly RedCardRow[],value:(r:RedCardRow)=>string){const counts=new Map<string,number>();for(const r of rows){const key=value(r);if(key)counts.set(key,(counts.get(key)??0)+1)}return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]??null}

export default function RedCards({onSelectMatch,onSelectPlayer,onSelectManager}:{onSelectMatch:(matchId:number)=>void;onSelectPlayer:(playerId:number,playerName:string)=>void;onSelectManager:(managerId:number)=>void}){
 const[rows,setRows]=useState<RedCardRow[]>([]),[playerAges,setPlayerAges]=useState<Map<number,PlayerAgeRow>>(new Map()),[side,setSide]=useState<Side>('Leeds'),[search,setSearch]=useState(''),[competition,setCompetition]=useState('All Comps'),[venue,setVenue]=useState<VenueFilter>('All'),[opponent,setOpponent]=useState('All Opponents'),[result,setResult]=useState<ResultFilter>('All Results'),[timeStart,setTimeStart]=useState(0),[timeEnd,setTimeEnd]=useState(AFT_VALUE),[sortKey,setSortKey]=useState<SortKey>('date'),[sortDirection,setSortDirection]=useState<SortDirection>('desc'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let dead=false;(async()=>{try{const data=await loadAll();const ids=Array.from(new Set(data.filter(r=>r.side==='Leeds'&&r.player_id!=null).map(r=>Number(r.player_id))));let ages:PlayerAgeRow[]=[];if(ids.length){const{data:ageData,error:ageError}=await supabase!.from('players').select('player_id,date_of_birth,birth_date_precision').in('player_id',ids);if(ageError)throw ageError;ages=(ageData??[])as PlayerAgeRow[]}if(!dead){setRows(data);setPlayerAges(new Map(ages.map(r=>[Number(r.player_id),r])))}}catch(e){if(!dead)setError(e instanceof Error?e.message:String(e))}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[]);
 const competitions=useMemo(()=>Array.from(new Set(rows.map(r=>r.competition))).sort(),[rows]);
 const opponents=useMemo(()=>Array.from(new Set(rows.map(r=>r.opponent))).sort(),[rows]);
 const ageFor=(r:RedCardRow)=>{if(r.side!=='Leeds'||r.player_id==null)return'—';const p=playerAges.get(Number(r.player_id));return ageAt(p?.date_of_birth,p?.birth_date_precision,r.match_date)};
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>{const t=eventMinuteValue(r.minute_raw);return r.side===side&&(competition==='All Comps'||r.competition===competition)&&(venue==='All'||venueLabel(r.venue_type)===venue)&&(opponent==='All Opponents'||r.opponent===opponent)&&(result==='All Results'||r.result===result)&&(t!=null&&t>=timeStart&&t<=timeEnd)&&(!q||r.recipient_name.toLowerCase().includes(q)||r.opponent.toLowerCase().includes(q)||(r.leeds_manager??'').toLowerCase().includes(q)||(r.referee??'').toLowerCase().includes(q)||(r.season??'').toLowerCase().includes(q))});},[rows,side,competition,venue,opponent,result,timeStart,timeEnd,search]);
 const sortedVisible=useMemo(()=>[...visible].sort((a,b)=>{const value=(r:RedCardRow):string|number|null=>{switch(sortKey){case'order':return r.source_order;case'date':return Date.parse(`${r.match_date}T00:00:00Z`);case'recipient':return r.recipient_name;case'type':return r.recipient_type;case'age':return ageSortValue(ageFor(r));case'minute':return minuteSortValue(r.minute_raw);case'opponent':return r.opponent;case'wdl':return resultCode(r.result);case'score':return displayScore(r);case'venue':return venueLabel(r.venue_type);case'competition':return r.competition;case'manager':return r.leeds_manager;case'referee':return r.referee;default:return null}};const compared=compareNullable(value(a),value(b),sortDirection);return compared!==0?compared:b.source_order-a.source_order}),[visible,sortKey,sortDirection,playerAges]);
 const summary=useMemo(()=>{const matchMap=new Map<number,RedCardRow>();for(const r of visible)matchMap.set(r.match_id,r);const matches=[...matchMap.values()],w=matches.filter(r=>r.result==='Won').length,d=matches.filter(r=>r.result==='Draw').length,l=matches.filter(r=>r.result==='Lost').length;const perMatch=new Map<number,number>();for(const r of visible)perMatch.set(r.match_id,(perMatch.get(r.match_id)??0)+1);const multiple=[...perMatch.values()].filter(n=>n>1).length;return{matches:matches.length,w,d,l,multiple,recipient:topValue(visible,r=>`${r.recipient_name}|||${r.recipient_type}`),opponent:topValue(visible,r=>r.opponent),competition:topValue(visible,r=>r.competition)}} ,[visible]);
 function toggleSort(key:SortKey){if(sortKey===key)setSortDirection(d=>d==='asc'?'desc':'asc');else{setSortKey(key);setSortDirection(key==='order'||key==='date'?'desc':'asc')}}
 function SortHeader({sort,label}:{sort:SortKey;label:React.ReactNode}){const active=sortKey===sort;return <button className={`col-sort ${active?'active':''}`} onClick={()=>toggleSort(sort)}>{label}<span className={active?'':'col-sort-idle'} aria-hidden="true">{active?(sortDirection==='asc'?'▲':'▼'):'↕'}</span></button>}
 const recipient=(r:RedCardRow)=>r.player_id?<button className="rc-link team-name rc-recipient-name" onClick={()=>onSelectPlayer(r.player_id!,r.recipient_name)}>{r.recipient_name}</button>:r.manager_id?<button className="rc-link team-name rc-recipient-name" onClick={()=>onSelectManager(r.manager_id!)}>{r.recipient_name}</button>:<span className="team-name rc-recipient-name">{r.recipient_name}</span>;
 const topRecipient=summary.recipient?summary.recipient[0].split('|||')[0]:'—';
 return <div className="card lb-table-card rc-card">
  <div className="lb-table-header rc-header"><div className="lb-title-group"><span className="section-kicker">Leeds United history</span><h2>Red Cards</h2><p>Canonical Leeds United and opposition dismissal archive</p></div><div className="rc-segment" role="group" aria-label="Red card side"><button className={side==='Leeds'?'active':''} onClick={()=>setSide('Leeds')}>Leeds Red Cards</button><button className={side==='Opponent'?'active':''} onClick={()=>setSide('Opponent')}>Opponent Red Cards</button></div></div>
  <div className="lb-filterbar rc-filterbar"><div className="lb-filter-section"><span className="lb-filter-label">Competition</span><select className="lb-filter-select" value={competition} onChange={e=>setCompetition(e.target.value)}><option>All Comps</option>{competitions.map(c=><option key={c}>{c}</option>)}</select></div><div className="lb-filter-section lb-venue-section"><span className="lb-filter-label">Venue</span><div className="lb-filter-pills"><button className={`lb-filter-pill ${venue==='All'?'active':''}`} onClick={()=>setVenue('All')}>All</button>{(['Home','Away','Neutral']as VenueFilter[]).map(v=><button key={v} className={`lb-filter-pill ${venue===v?'active':''}`} onClick={()=>setVenue(v)}>{v}</button>)}</div></div><div className="lb-filter-section"><span className="lb-filter-label">Opponent</span><select className="lb-filter-select" value={opponent} onChange={e=>setOpponent(e.target.value)}><option>All Opponents</option>{opponents.map(x=><option key={x}>{x}</option>)}</select></div><div className="lb-filter-section"><span className="lb-filter-label">Result</span><select className="lb-filter-select" value={result} onChange={e=>setResult(e.target.value as ResultFilter)}><option value="All Results">All Results</option><option value="Won">Won</option><option value="Draw">Drawn</option><option value="Lost">Lost</option></select></div><label className="lb-search matches-search" style={{height:30,minWidth:180,width:180,maxWidth:180,marginLeft:'auto'}}><Search size={13}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></label><span className="section-kicker rc-count">{loading?'…':sortedVisible.length.toLocaleString('en-GB')} shown</span></div>
  <TimeRangeFilter start={timeStart} end={timeEnd} onChange={(start,end)=>{setTimeStart(start);setTimeEnd(end)}} includeAfterFullTime/>
  {!loading&&!error&&<div className="rc-summary" aria-label={`${side} red card summary`}><div className="rc-summary-card"><span>Red Cards</span><strong>{visible.length}</strong><small>{side==='Leeds'?'Leeds dismissals':'Opposition dismissals'}</small></div><div className="rc-summary-card"><span>Matches</span><strong>{summary.matches}</strong><small>{summary.multiple} with multiple dismissals</small></div><div className="rc-summary-card"><span>Match Record</span><strong>W{summary.w} D{summary.d} L{summary.l}</strong><small>Distinct matches containing a red card</small></div><div className="rc-summary-card"><span>Most Cards</span><strong>{topRecipient}</strong><small>{summary.recipient?`${summary.recipient[1]} red card${summary.recipient[1]===1?'':'s'}`:'—'}</small></div><div className="rc-summary-card"><span>Most vs Club</span><strong>{summary.opponent?.[0]??'—'}</strong><small>{summary.opponent?`${summary.opponent[1]} red card${summary.opponent[1]===1?'':'s'}`:'—'}</small></div><div className="rc-summary-card"><span>Most in Competition</span><strong>{summary.competition?.[0]??'—'}</strong><small>{summary.competition?`${summary.competition[1]} red card${summary.competition[1]===1?'':'s'}`:'—'}</small></div></div>}
  {error?<div className="rc-state">{error}</div>:loading?<div className="rc-state">Loading red cards…</div>:<div className="lb-table-wrap"><table className="lb-table matches-table goals-table rc-table"><thead><tr><th><SortHeader sort="order" label="#"/></th><th><SortHeader sort="date" label="Date"/></th><th style={{textAlign:'center'}}>Card</th><th><SortHeader sort="recipient" label="Recipient"/></th><th><SortHeader sort="type" label="Type"/></th>{side==='Leeds'&&<th><SortHeader sort="age" label="Age"/></th>}<th><SortHeader sort="minute" label="Min"/></th><th style={{minWidth:190}}><SortHeader sort="opponent" label="Opponent"/></th><th><SortHeader sort="wdl" label="W/D/L"/></th><th><SortHeader sort="score" label="Score"/></th><th><SortHeader sort="venue" label="Venue"/></th><th style={{minWidth:155,whiteSpace:'nowrap'}}><SortHeader sort="competition" label="Competition"/></th><th><SortHeader sort="manager" label="Leeds Manager"/></th><th><SortHeader sort="referee" label="Referee"/></th></tr></thead><tbody>{sortedVisible.map(r=><tr key={r.red_card_event_id} style={{height:44}}><td className="metric-value rc-order">{r.source_order}</td><td><button className="rc-link metric-value rc-date" onClick={()=>onSelectMatch(r.match_id)}>{prettyDate(r.match_date)}</button></td><td style={{textAlign:'center',minWidth:52}}><DismissalIcon issued={r.issued}/></td><td>{recipient(r)}</td><td>{r.recipient_type==='Opponent Player'?'Player':r.recipient_type}</td>{side==='Leeds'&&<td className="metric-value">{ageFor(r)}</td>}<td className="metric-value">{r.minute_raw||'—'}</td><td style={{minWidth:190}}><button className="rc-opponent team-cell" onClick={()=>onSelectMatch(r.match_id)}><ClubCrest opponent={r.opponent} crestUrl={r.opponent_crest_url}/><span className="team-name">{r.opponent}</span></button></td><td><span className={`form-pill form-${resultCode(r.result).toLowerCase()}`}>{resultCode(r.result)}</span></td><td className="metric-value">{displayScore(r)}</td><td>{venueLabel(r.venue_type)}</td><td style={{minWidth:155,whiteSpace:'nowrap'}}>{r.competition}</td><td>{r.leeds_manager||'—'}</td><td>{r.referee||'—'}</td></tr>)}</tbody></table>{!sortedVisible.length&&<div className="lb-empty">No red cards match these filters.</div>}</div>}
  {!loading&&!error&&sortedVisible.length>0&&<div className="lb-legend rc-table-legend"><div className="lb-legend-items"><span>Showing all {sortedVisible.length.toLocaleString('en-GB')} red cards</span><span>Yellow/red icon = second yellow; red icon = straight red</span><span>Time range includes extra time, full-time dismissals and AFT (after full-time) events</span><span>Click any column header to sort; click again to reverse the order</span></div></div>}
 </div>;
}
