import React, { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { supabase, supabaseConfigError } from './supabase';

type SeasonRef={season_id:number;display_name:string;start_year:number;end_year:number};
type SeasonMatch={match_id:number;match_date:string;season:string|null;competition:string;round:string|null;venue_type:string;leeds_score:number;opponent_score:number;result:string;leeds_manager:string|null;league_tier:number|null;league_position_after_match:number|null;league_points_after_match:number|null};
type Split={matches:number;won:number;drawn:number;lost:number;goalsFor:number;goalsAgainst:number;goalDifference:number;cleanSheets:number};
type SeasonSummary={season:SeasonRef;tier:number|null;finalTier:number|null;finalPosition:number|null;matchesPlayed:number;won:number;drawn:number;lost:number;goalsFor:number;goalsAgainst:number;goalDifference:number;cleanSheets:number;points:number|null;home:Split;away:Split;managers:string[];statuses:string[];faCup:string;leagueCup:string;europe:string};
type SliderScope='All'|'Home'|'Away';
type SortKey='season'|'tier'|'position'|'matches'|'won'|'drawn'|'lost'|'for'|'against'|'gd'|'cs'|'points'|'hm'|'hw'|'hd'|'hl'|'gh'|'gah'|'hgd'|'hcs'|'am'|'aw'|'ad'|'al'|'ga'|'gaa'|'agd'|'acs'|'managers'|'status'|'faCup'|'leagueCup'|'europe';
type SortDirection='asc'|'desc';

const PAGE_SIZE=1000;
const EUROPEAN_COMPETITIONS=new Set(['Inter-City Fairs Cup','European Cup','UEFA Cup',"European Cup Winners' Cup",'Champions League']);
const ordinal=(v:number|null)=>{if(v==null)return'—';const m100=v%100,m10=v%10,s=m100>=11&&m100<=13?'th':m10===1?'st':m10===2?'nd':m10===3?'rd':'th';return`${v}${s}`};
const normaliseRound=(r:string|null)=>{if(!r)return'—';const c=r.replace(/ \(R\)$/i,'').trim();if(c==='Stage 1')return'GS1';if(c==='Stage 2')return'GS2';return c};
const roundRank=(r:string|null)=>{const c=normaliseRound(r),x:Record<string,number>={'—':0,PR:1,Q:2,PO:3,'R1 PO':4,R1:10,R2:20,R3:30,R4:40,R5:50,GS1:55,GS2:60,QF:70,SF:80,F:90};return x[c]??5};
const furthestRound=(m:SeasonMatch[])=>!m.length?'—':normaliseRound(m.reduce((b,x)=>roundRank(x.round)>roundRank(b.round)?x:b).round);
const europeanLabel=(c:string)=>c==='Inter-City Fairs Cup'?'Fairs':c==='European Cup'?'EC':c==='UEFA Cup'?'UEFA':c==="European Cup Winners' Cup"?'CWC':c==='Champions League'?'UCL':c;
const statusSortRank=(s:string[])=>s.includes('Champions')?4:s.includes('Promoted')?3:s.includes('Relegated')?2:s.includes('Current')?1:0;
const cupSortRank=(v:string)=>v==='—'?0:Math.max(...v.split(' · ').map(p=>roundRank(p.split(' ').at(-1)??null)));
const split=(rows:SeasonMatch[]):Split=>{const gf=rows.reduce((s,m)=>s+Number(m.leeds_score||0),0),ga=rows.reduce((s,m)=>s+Number(m.opponent_score||0),0);return{matches:rows.length,won:rows.filter(m=>m.result==='Won').length,drawn:rows.filter(m=>m.result==='Draw').length,lost:rows.filter(m=>m.result==='Lost').length,goalsFor:gf,goalsAgainst:ga,goalDifference:gf-ga,cleanSheets:rows.filter(m=>Number(m.opponent_score)===0).length}};

const styles=`
.seasons-toolbar{display:flex;align-items:flex-end;gap:18px;flex-wrap:wrap;padding:0 0 16px;border-bottom:1px solid #eceeee}
.season-slider-block{display:flex;flex-direction:column;gap:6px;min-width:330px;flex:1;max-width:560px}.season-slider-row{display:flex;align-items:center;gap:9px}.season-scope-select{min-width:82px;width:82px}.season-slider{width:100%;height:3px;accent-color:#27F5DD;cursor:pointer}.season-slider-value{min-width:34px;text-align:center;font-family:'DM Mono',monospace;font-size:11px;font-weight:700;color:#27F5DD}
.seasons-table{min-width:2260px;table-layout:auto;font-family:'DM Mono',monospace}.seasons-table thead th{text-align:center}.seasons-table thead th:first-child{text-align:left}.seasons-table tbody td{text-align:center;white-space:nowrap;font-family:'DM Mono',monospace;font-size:10px}.seasons-table .season-name-col,.seasons-table .season-name-cell{position:sticky;left:0;z-index:4;background:#fff;text-align:left;min-width:98px}.seasons-table thead .season-name-col{z-index:6}.seasons-table tbody tr:hover .season-name-cell{background:#fafbfb}.season-name-cell{font-weight:700;color:#23292b}.season-tier{font-weight:700}
.season-group-start{border-left:1px solid rgba(125,135,150,.24)!important}.season-home-head{color:#27F5DD!important}.season-away-head{color:#8bbcff!important}.season-manager-cell{min-width:220px;max-width:280px;text-align:left!important;white-space:normal!important;line-height:1.45}.season-status-cell{min-width:170px;white-space:normal!important}.season-statuses{display:flex;justify-content:center;gap:9px;flex-wrap:wrap;align-items:center}.season-status-mark{display:inline-flex;align-items:center;gap:3px;font-family:'DM Mono',monospace;font-size:10px;font-weight:700;white-space:nowrap}.season-status-promoted{color:#50E5E0}.season-status-relegated{color:#F73475}.season-status-champions{color:#F2E01F}.season-status-current{color:#2F91ED}.season-positive{color:#50E5E0!important;font-weight:700}.season-negative{color:#F73475!important;font-weight:700}.season-cup-cell{font-weight:600}
.season-sort-button{display:inline-flex;align-items:center;justify-content:center;gap:3px;border:0;background:transparent;color:inherit;font:inherit;text-transform:inherit;letter-spacing:inherit;padding:0;cursor:pointer}.season-sort-button:hover,.season-sort-button.active{color:#2F91ED}.season-sort-icon{width:11px;height:11px;opacity:.85}.season-deduction-note{margin:12px 4px 0;color:#a8afb3;font-family:'DM Mono',monospace;font-size:8.5px;line-height:1.55;font-weight:400;max-width:1180px}
.theme-dark .seasons-toolbar{border-bottom-color:#2c3752}.theme-dark .seasons-table .season-name-col,.theme-dark .seasons-table .season-name-cell{background:#192031}.theme-dark .seasons-table tbody tr:hover .season-name-cell{background:#222b42}.theme-dark .season-name-cell{color:#F5F5F5}.theme-dark .season-deduction-note{color:#778197}@media(max-width:700px){.season-slider-block{min-width:100%;max-width:none}.seasons-toolbar>.lb-filter-section{width:auto}}
`;

async function loadAllSeasonMatches(){if(!supabase)return[] as SeasonMatch[];const all:SeasonMatch[]=[];for(let start=0;;start+=PAGE_SIZE){const{data,error}=await supabase.from('match_centre_summary').select('match_id,match_date,season,competition,round,venue_type,leeds_score,opponent_score,result,leeds_manager,league_tier,league_position_after_match,league_points_after_match').order('match_date',{ascending:true}).order('match_id',{ascending:true}).range(start,start+PAGE_SIZE-1);if(error)throw error;const batch=(data??[]) as SeasonMatch[];all.push(...batch);if(batch.length<PAGE_SIZE)break}return all}

export default function Seasons(){
  const[seasons,setSeasons]=useState<SeasonRef[]>([]);
  const[matches,setMatches]=useState<SeasonMatch[]>([]);
  const[tierFilter,setTierFilter]=useState('All Tiers');
  const[sliderScope,setSliderScope]=useState<SliderScope>('All');
  const[matchLimit,setMatchLimit]=useState(46);
  const[sortKey,setSortKey]=useState<SortKey>('season');
  const[sortDirection,setSortDirection]=useState<SortDirection>('desc');
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState<string|null>(supabaseConfigError);

  useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;async function load(){setLoading(true);setError(null);try{const[{data:seasonData,error:seasonError},allMatches]=await Promise.all([supabase!.from('seasons').select('season_id,display_name,start_year,end_year').order('start_year',{ascending:false}),loadAllSeasonMatches()]);if(seasonError)throw seasonError;if(!cancelled){setSeasons((seasonData??[]) as SeasonRef[]);setMatches(allMatches)}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e))}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[]);

  const matchesBySeason=useMemo(()=>{const map=new Map<string,SeasonMatch[]>();for(const m of matches){if(!m.season)continue;const list=map.get(m.season)??[];list.push(m);map.set(m.season,list)}for(const list of map.values())list.sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id);return map},[matches]);
  const fullSeasonState=useMemo(()=>seasons.map(season=>{const lm=(matchesBySeason.get(season.display_name)??[]).filter(m=>m.league_tier!=null),final=lm.at(-1)??null;return{season,tier:lm[0]?.league_tier??null,finalPosition:final?.league_position_after_match??null}}),[seasons,matchesBySeason]);

  const sliderMax=useMemo(()=>{let max=1;for(const s of seasons){const state=fullSeasonState.find(x=>x.season.season_id===s.season_id);if(tierFilter!=='All Tiers'&&state?.tier!==Number(tierFilter))continue;const lm=(matchesBySeason.get(s.display_name)??[]).filter(m=>m.league_tier!=null);const n=sliderScope==='All'?lm.length:lm.filter(m=>m.venue_type===(sliderScope==='Home'?'H':'A')).length;max=Math.max(max,n)}return max},[seasons,fullSeasonState,matchesBySeason,tierFilter,sliderScope]);
  useEffect(()=>setMatchLimit(v=>Math.min(v,sliderMax)),[sliderMax]);
  useEffect(()=>setMatchLimit(sliderScope==='All'?Math.min(46,sliderMax):Math.min(23,sliderMax)),[sliderScope]);

  const summaries=useMemo<SeasonSummary[]>(()=>{const stateBySeasonId=new Map(fullSeasonState.map(x=>[x.season.season_id,x])),ascending=[...seasons].sort((a,b)=>a.start_year-b.start_year);const nextTier=(season:SeasonRef)=>{const i=ascending.findIndex(s=>s.season_id===season.season_id);for(let j=i+1;j<ascending.length;j++){const x=stateBySeasonId.get(ascending[j].season_id);if(x?.tier!=null)return x.tier}return null};const newest=Math.max(...seasons.map(s=>s.season_id),0);return seasons.map(season=>{const sm=matchesBySeason.get(season.display_name)??[],lm=sm.filter(m=>m.league_tier!=null);let sampled:SeasonMatch[]=[];if(sliderScope==='All'){sampled=lm.slice(0,Math.min(matchLimit,lm.length))}else{const venue=sliderScope==='Home'?'H':'A',venueMatches=lm.filter(m=>m.venue_type===venue),target=venueMatches[Math.min(matchLimit,venueMatches.length)-1];sampled=target?lm.filter(m=>m.match_date<target.match_date||(m.match_date===target.match_date&&m.match_id<=target.match_id)):[];if(!sampled.length&&lm.length)sampled=lm.slice(0,Math.min(matchLimit,lm.length))}const last=sampled.at(-1)??null,final=lm.at(-1)??null,all=split(sampled),home=split(sampled.filter(m=>m.venue_type==='H')),away=split(sampled.filter(m=>m.venue_type==='A')),managers=Array.from(new Set(sm.map(m=>m.leeds_manager).filter((m):m is string=>Boolean(m)))),tier=lm[0]?.league_tier??null,finalTier=tier,finalPos=final?.league_position_after_match??null,nTier=nextTier(season),statuses:string[]=[];if(finalPos===1)statuses.push('Champions');if(finalTier!=null&&nTier!=null&&nTier<finalTier)statuses.push('Promoted');if(finalTier!=null&&nTier!=null&&nTier>finalTier)statuses.push('Relegated');if(season.season_id===newest)statuses.push('Current');const rawFa=furthestRound(sm.filter(m=>m.competition==='FA Cup')),rawLc=furthestRound(sm.filter(m=>m.competition==='League Cup')),faCup=season.start_year===1971&&rawFa==='F'?'🏆 F':rawFa,leagueCup=season.start_year===1967&&rawLc==='F'?'🏆 F':rawLc,eg=new Map<string,SeasonMatch[]>();for(const m of sm.filter(m=>EUROPEAN_COMPETITIONS.has(m.competition))){const list=eg.get(m.competition)??[];list.push(m);eg.set(m.competition,list)}const europe=eg.size?Array.from(eg.entries()).map(([c,rows])=>{const progress=furthestRound(rows);const wonFairs=c==='Inter-City Fairs Cup'&&progress==='F'&&(season.start_year===1967||season.start_year===1970);return`${wonFairs?'🏆 ':''}${europeanLabel(c)} ${progress}`}).join(' · '):'—';return{season,tier,finalTier,finalPosition:last?.league_position_after_match??null,matchesPlayed:all.matches,won:all.won,drawn:all.drawn,lost:all.lost,goalsFor:all.goalsFor,goalsAgainst:all.goalsAgainst,goalDifference:all.goalDifference,cleanSheets:all.cleanSheets,points:last?.league_points_after_match??null,home,away,managers,statuses,faCup,leagueCup,europe}})},[seasons,matchesBySeason,fullSeasonState,matchLimit,sliderScope]);

  const tiers=useMemo(()=>Array.from(new Set(summaries.map(s=>s.tier).filter((n):n is number=>n!=null))).sort((a,b)=>a-b),[summaries]);
  const filtered=useMemo(()=>summaries.filter(s=>tierFilter==='All Tiers'||s.tier===Number(tierFilter)),[summaries,tierFilter]);
  const sortValue=(r:SeasonSummary,k:SortKey):string|number|null=>{switch(k){case'season':return r.season.start_year;case'tier':return r.tier;case'position':return r.finalPosition;case'matches':return r.matchesPlayed;case'won':return r.won;case'drawn':return r.drawn;case'lost':return r.lost;case'for':return r.goalsFor;case'against':return r.goalsAgainst;case'gd':return r.goalDifference;case'cs':return r.cleanSheets;case'points':return r.points;case'hm':return r.home.matches;case'hw':return r.home.won;case'hd':return r.home.drawn;case'hl':return r.home.lost;case'gh':return r.home.goalsFor;case'gah':return r.home.goalsAgainst;case'hgd':return r.home.goalDifference;case'hcs':return r.home.cleanSheets;case'am':return r.away.matches;case'aw':return r.away.won;case'ad':return r.away.drawn;case'al':return r.away.lost;case'ga':return r.away.goalsFor;case'gaa':return r.away.goalsAgainst;case'agd':return r.away.goalDifference;case'acs':return r.away.cleanSheets;case'managers':return r.managers.join(' / ');case'status':return statusSortRank(r.statuses);case'faCup':return cupSortRank(r.faCup.replace('🏆 ',''));case'leagueCup':return cupSortRank(r.leagueCup.replace('🏆 ',''));case'europe':return cupSortRank(r.europe);default:return null}};
  const visible=useMemo(()=>{const mult=sortDirection==='asc'?1:-1;return[...filtered].sort((a,b)=>{const av=sortValue(a,sortKey),bv=sortValue(b,sortKey);if(av==null&&bv==null)return b.season.start_year-a.season.start_year;if(av==null)return 1;if(bv==null)return-1;if(typeof av==='number'&&typeof bv==='number'){const d=av-bv;return d===0?b.season.start_year-a.season.start_year:d*mult}const d=String(av).localeCompare(String(bv));return d===0?b.season.start_year-a.season.start_year:d*mult})},[filtered,sortKey,sortDirection]);
  const handleSort=(k:SortKey)=>{if(sortKey===k)setSortDirection(c=>c==='asc'?'desc':'asc');else{setSortKey(k);setSortDirection(k==='season'?'desc':'asc')}};
  const SortHeader=({label,sort,className}:{label:string;sort:SortKey;className?:string})=><th className={className}><button type="button" className={`season-sort-button ${sortKey===sort?'active':''}`} onClick={()=>handleSort(sort)} aria-label={`Sort by ${label}`}><span>{label}</span>{sortKey===sort?(sortDirection==='asc'?<ChevronUp className="season-sort-icon"/>:<ChevronDown className="season-sort-icon"/>):null}</button></th>;
  const renderStatus=(s:string)=>s==='Promoted'?<span key={s} className="season-status-mark season-status-promoted">↑ Promoted</span>:s==='Relegated'?<span key={s} className="season-status-mark season-status-relegated">↓ Relegated</span>:s==='Champions'?<span key={s} className="season-status-mark season-status-champions">🏆 Champions</span>:<span key={s} className="season-status-mark season-status-current">Current</span>;
  const gdCell=(v:number,m:number)=><span className={v>0?'season-positive':v<0?'season-negative':''}>{m?(v>0?`+${v}`:v):'—'}</span>;

  return <><style>{styles}</style><div className="card lb-table-card"><div className="lb-table-header"><div className="lb-title-group"><span className="section-kicker">Leeds United history</span><h2>Seasons</h2><p>League record, home/away splits, managers and cup progression across every Leeds United season</p></div><div className="section-kicker lb-match-count">{loading?'…':`${visible.length} Seasons Shown`}</div></div>
  <div className="seasons-toolbar"><div className="lb-filter-section"><span className="lb-filter-label">League Tier</span><select className="lb-filter-select" value={tierFilter} onChange={e=>setTierFilter(e.target.value)}><option value="All Tiers">All Tiers</option>{tiers.map(t=><option key={t} value={t}>Tier {t}</option>)}</select></div><div className="season-slider-block"><span className="lb-filter-label">League record after match</span><div className="season-slider-row"><select className="lb-filter-select season-scope-select" value={sliderScope} onChange={e=>setSliderScope(e.target.value as SliderScope)} aria-label="Slider match type"><option>All</option><option>Home</option><option>Away</option></select><input className="season-slider" type="range" min={1} max={sliderMax} step={1} value={Math.min(matchLimit,sliderMax)} onChange={e=>setMatchLimit(Number(e.target.value))} aria-label={`${sliderScope} league matches elapsed`}/><span className="season-slider-value">{Math.min(matchLimit,sliderMax)}</span></div></div></div>
  {loading?<div className="lb-loading">Building Leeds United season records…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:<div className="lb-table-wrap"><table className="lb-table seasons-table"><thead><tr><SortHeader label="Season" sort="season" className="season-name-col"/><SortHeader label="Tier" sort="tier"/><SortHeader label="Pos" sort="position"/><SortHeader label="M" sort="matches"/><SortHeader label="W" sort="won"/><SortHeader label="D" sort="drawn"/><SortHeader label="L" sort="lost"/><SortHeader label="F" sort="for"/><SortHeader label="A" sort="against"/><SortHeader label="GD" sort="gd"/><SortHeader label="CS" sort="cs"/><SortHeader label="PTS" sort="points"/>
  <SortHeader label="HM" sort="hm" className="season-group-start season-home-head"/><SortHeader label="HW" sort="hw" className="season-home-head"/><SortHeader label="HD" sort="hd" className="season-home-head"/><SortHeader label="HL" sort="hl" className="season-home-head"/><SortHeader label="GH" sort="gh" className="season-home-head"/><SortHeader label="GAH" sort="gah" className="season-home-head"/><SortHeader label="HGD" sort="hgd" className="season-home-head"/><SortHeader label="HCS" sort="hcs" className="season-home-head"/>
  <SortHeader label="AM" sort="am" className="season-group-start season-away-head"/><SortHeader label="AW" sort="aw" className="season-away-head"/><SortHeader label="AD" sort="ad" className="season-away-head"/><SortHeader label="AL" sort="al" className="season-away-head"/><SortHeader label="GA" sort="ga" className="season-away-head"/><SortHeader label="GAA" sort="gaa" className="season-away-head"/><SortHeader label="AGD" sort="agd" className="season-away-head"/><SortHeader label="ACS" sort="acs" className="season-away-head"/>
  <SortHeader label="Leeds Managers" sort="managers" className="season-group-start"/><SortHeader label="Champions / Promotion / Relegation" sort="status"/><SortHeader label="FA Cup" sort="faCup"/><SortHeader label="League Cup" sort="leagueCup"/><SortHeader label="Europe" sort="europe"/></tr></thead><tbody>{visible.map(r=><tr key={r.season.season_id}><td className="season-name-cell">{r.season.display_name}</td><td className="metric-value season-tier">{r.tier==null?'—':`T${r.tier}`}</td><td className="metric-value" style={{fontWeight:700}}>{ordinal(r.finalPosition)}</td><td>{r.matchesPlayed||'—'}</td><td>{r.matchesPlayed?r.won:'—'}</td><td>{r.matchesPlayed?r.drawn:'—'}</td><td>{r.matchesPlayed?r.lost:'—'}</td><td>{r.matchesPlayed?r.goalsFor:'—'}</td><td>{r.matchesPlayed?r.goalsAgainst:'—'}</td><td>{gdCell(r.goalDifference,r.matchesPlayed)}</td><td>{r.matchesPlayed?r.cleanSheets:'—'}</td><td style={{fontWeight:700}}>{r.points??'—'}</td>
  <td className="season-group-start">{r.home.matches||'—'}</td><td>{r.home.matches?r.home.won:'—'}</td><td>{r.home.matches?r.home.drawn:'—'}</td><td>{r.home.matches?r.home.lost:'—'}</td><td>{r.home.matches?r.home.goalsFor:'—'}</td><td>{r.home.matches?r.home.goalsAgainst:'—'}</td><td>{gdCell(r.home.goalDifference,r.home.matches)}</td><td>{r.home.matches?r.home.cleanSheets:'—'}</td>
  <td className="season-group-start">{r.away.matches||'—'}</td><td>{r.away.matches?r.away.won:'—'}</td><td>{r.away.matches?r.away.drawn:'—'}</td><td>{r.away.matches?r.away.lost:'—'}</td><td>{r.away.matches?r.away.goalsFor:'—'}</td><td>{r.away.matches?r.away.goalsAgainst:'—'}</td><td>{gdCell(r.away.goalDifference,r.away.matches)}</td><td>{r.away.matches?r.away.cleanSheets:'—'}</td>
  <td className="season-manager-cell season-group-start">{r.managers.length?r.managers.join(' / '):'—'}</td><td className="season-status-cell">{r.statuses.length?<div className="season-statuses">{r.statuses.map(renderStatus)}</div>:'—'}</td><td className="season-cup-cell">{r.faCup}</td><td className="season-cup-cell">{r.leagueCup}</td><td className="season-cup-cell">{r.europe}</td></tr>)}</tbody></table>{!visible.length&&<div className="lb-empty">No seasons match this tier.</div>}</div>}
  <p className="season-deduction-note">Leeds were given a 10-point deduction by the Football League before for entering administration following the club's relegation during the 2006/07 season. The club also suffered a second points deduction by the authorities as chairman Ken Bates battled HMRC and were handed a 15-point penalty for exiting administration incorrectly ahead of the 2007/08 campaign.</p></div>
  <div className="card lb-legend"><div className="lb-legend-items"><span>Slider: All = overall league matches; Home / Away = the table state through the selected number of home or away league matches.</span><span>Home: HM matches, HW wins, HD draws, HL losses, GH goals scored, GAH goals against, HGD goal difference, HCS clean sheets.</span><span>Away: AM matches, AW wins, AD draws, AL losses, GA goals scored, GAA goals against, AGD goal difference, ACS clean sheets.</span><span>Click any column heading to sort; click again to reverse the order.</span><span>Champions / Promoted / Relegated are season-end outcomes and do not change with the slider.</span><span>Cup columns show the furthest round reached: R1–R5, QF, SF, F; European group stages use GS1 / GS2.</span></div></div></>;
}
