import React, { useEffect, useMemo, useState } from 'react';
import { ChevronDown, ChevronUp } from 'lucide-react';
import { supabase, supabaseConfigError } from './supabase';

type SeasonRef = { season_id:number; display_name:string; start_year:number; end_year:number };
type SeasonMatch = { match_id:number; match_date:string; season:string|null; competition:string; round:string|null; leeds_score:number; opponent_score:number; result:string; leeds_manager:string|null; league_tier:number|null; league_position_after_match:number|null; league_points_after_match:number|null };
type SeasonSummary = { season:SeasonRef; tier:number|null; finalTier:number|null; finalPosition:number|null; matchesPlayed:number; won:number; drawn:number; lost:number; goalsFor:number; goalsAgainst:number; goalDifference:number; cleanSheets:number; points:number|null; managers:string[]; statuses:string[]; faCup:string; leagueCup:string; europe:string };
type SortKey='season'|'tier'|'position'|'matches'|'won'|'drawn'|'lost'|'for'|'against'|'gd'|'cs'|'points'|'managers'|'status'|'faCup'|'leagueCup'|'europe';
type SortDirection='asc'|'desc';
const PAGE_SIZE=1000, LEAGUE_MATCH_MAX=46;
const EUROPEAN_COMPETITIONS=new Set(['Inter-City Fairs Cup','European Cup','UEFA Cup',"European Cup Winners' Cup",'Champions League']);
const ordinal=(value:number|null)=>{if(value==null)return'—';const m100=value%100,m10=value%10,s=m100>=11&&m100<=13?'th':m10===1?'st':m10===2?'nd':m10===3?'rd':'th';return`${value}${s}`};
const normaliseRound=(round:string|null)=>{if(!round)return'—';const clean=round.replace(/ \(R\)$/i,'').trim();if(clean==='Stage 1')return'GS1';if(clean==='Stage 2')return'GS2';return clean};
const roundRank=(round:string|null)=>{const clean=normaliseRound(round);const ranks:Record<string,number>={'—':0,PR:1,Q:2,PO:3,'R1 PO':4,R1:10,R2:20,R3:30,R4:40,R5:50,GS1:55,GS2:60,QF:70,SF:80,F:90};return ranks[clean]??5};
const furthestRound=(matches:SeasonMatch[])=>!matches.length?'—':normaliseRound(matches.reduce((best,m)=>roundRank(m.round)>roundRank(best.round)?m:best).round);
const europeanLabel=(c:string)=>c==='Inter-City Fairs Cup'?'Fairs':c==='European Cup'?'EC':c==='UEFA Cup'?'UEFA':c==="European Cup Winners' Cup"?'CWC':c==='Champions League'?'UCL':c;
const statusSortRank=(s:string[])=>s.includes('Champions')?4:s.includes('Promoted')?3:s.includes('Relegated')?2:s.includes('Current')?1:0;
const cupSortRank=(v:string)=>v==='—'?0:Math.max(...v.split(' · ').map(p=>roundRank(p.split(' ').at(-1)??null)));
const seasonStyles=`
.seasons-toolbar{display:flex;align-items:flex-end;gap:18px;flex-wrap:wrap;padding:0 0 16px;border-bottom:1px solid #eceeee}
.season-slider-block{display:flex;flex-direction:column;gap:6px;min-width:330px;flex:1;max-width:520px}.season-slider-row{display:flex;align-items:center;gap:10px}
.season-slider{width:100%;height:3px;accent-color:#27F5DD;cursor:pointer}.season-slider-value{min-width:34px;text-align:center;font-family:'DM Mono',monospace;font-size:11px;font-weight:700;color:#27F5DD}
.seasons-table{min-width:1540px;table-layout:auto;font-family:'DM Mono',monospace}.seasons-table thead th{text-align:center}.seasons-table thead th:first-child{text-align:left}.seasons-table tbody td{text-align:center;white-space:nowrap;font-family:'DM Mono',monospace;font-size:10px}
.seasons-table .season-name-col,.seasons-table .season-name-cell{position:sticky;left:0;z-index:4;background:#fff;text-align:left;min-width:98px}.seasons-table thead .season-name-col{z-index:6}.seasons-table tbody tr:hover .season-name-cell{background:#fafbfb}.season-name-cell{font-weight:700;color:#23292b}.season-tier{font-weight:700}
.season-manager-cell{min-width:220px;max-width:280px;text-align:left!important;white-space:normal!important;line-height:1.45}.season-status-cell{min-width:170px;white-space:normal!important}.season-statuses{display:flex;justify-content:center;gap:9px;flex-wrap:wrap;align-items:center}.season-status-mark{display:inline-flex;align-items:center;gap:3px;font-family:'DM Mono',monospace;font-size:10px;font-weight:700;white-space:nowrap}.season-status-promoted{color:#50E5E0}.season-status-relegated{color:#F73475}.season-status-champions{color:#F2E01F}.season-status-current{color:#2F91ED}.season-positive{color:#50E5E0!important;font-weight:700}.season-negative{color:#F73475!important;font-weight:700}.season-cup-cell{font-weight:600}
.season-sort-button{display:inline-flex;align-items:center;justify-content:center;gap:3px;border:0;background:transparent;color:inherit;font:inherit;text-transform:inherit;letter-spacing:inherit;padding:0;cursor:pointer}.season-sort-button:hover,.season-sort-button.active{color:#2F91ED}.season-sort-icon{width:11px;height:11px;opacity:.85}
.season-deduction-note{margin:12px 4px 0;color:#a8afb3;font-family:'DM Mono',monospace;font-size:8.5px;line-height:1.55;font-weight:400;max-width:1180px}
.theme-dark .seasons-toolbar{border-bottom-color:#2c3752}.theme-dark .seasons-table .season-name-col,.theme-dark .seasons-table .season-name-cell{background:#192031}.theme-dark .seasons-table tbody tr:hover .season-name-cell{background:#222b42}.theme-dark .season-name-cell{color:#F5F5F5}.theme-dark .season-deduction-note{color:#778197}
@media(max-width:700px){.season-slider-block{min-width:100%;max-width:none}.seasons-toolbar>.lb-filter-section{width:auto}}
`;
async function loadAllSeasonMatches(){if(!supabase)return[] as SeasonMatch[];const all:SeasonMatch[]=[];for(let start=0;;start+=PAGE_SIZE){const{data,error}=await supabase.from('match_centre_summary').select('match_id,match_date,season,competition,round,leeds_score,opponent_score,result,leeds_manager,league_tier,league_position_after_match,league_points_after_match').order('match_date',{ascending:true}).order('match_id',{ascending:true}).range(start,start+PAGE_SIZE-1);if(error)throw error;const batch=(data??[]) as SeasonMatch[];all.push(...batch);if(batch.length<PAGE_SIZE)break}return all}
export default function Seasons(){
const[seasons,setSeasons]=useState<SeasonRef[]>([]),[matches,setMatches]=useState<SeasonMatch[]>([]),[tierFilter,setTierFilter]=useState('All Tiers'),[matchLimit,setMatchLimit]=useState(46),[sortKey,setSortKey]=useState<SortKey>('season'),[sortDirection,setSortDirection]=useState<SortDirection>('desc'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;async function load(){setLoading(true);setError(null);try{const[{data:seasonData,error:seasonError},allMatches]=await Promise.all([supabase!.from('seasons').select('season_id,display_name,start_year,end_year').order('start_year',{ascending:false}),loadAllSeasonMatches()]);if(seasonError)throw seasonError;if(!cancelled){setSeasons((seasonData??[]) as SeasonRef[]);setMatches(allMatches)}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e))}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[]);
const matchesBySeason=useMemo(()=>{const map=new Map<string,SeasonMatch[]>();for(const match of matches){if(!match.season)continue;const list=map.get(match.season)??[];list.push(match);map.set(match.season,list)}for(const list of map.values())list.sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id);return map},[matches]);
const fullSeasonState=useMemo(()=>seasons.map(season=>{const lm=(matchesBySeason.get(season.display_name)??[]).filter(m=>m.league_tier!=null),final=lm.at(-1)??null;return{season,tier:lm[0]?.league_tier??null,finalPosition:final?.league_position_after_match??null}}),[seasons,matchesBySeason]);
const summaries=useMemo<SeasonSummary[]>(()=>{const stateBySeasonId=new Map(fullSeasonState.map(x=>[x.season.season_id,x])),orderedAscending=[...seasons].sort((a,b)=>a.start_year-b.start_year);const nextLeagueTier=(season:SeasonRef)=>{const index=orderedAscending.findIndex(s=>s.season_id===season.season_id);for(let i=index+1;i<orderedAscending.length;i++){const state=stateBySeasonId.get(orderedAscending[i].season_id);if(state?.tier!=null)return state.tier}return null};const newestSeasonId=Math.max(...seasons.map(s=>s.season_id),0);return seasons.map(season=>{const sm=matchesBySeason.get(season.display_name)??[],lm=sm.filter(m=>m.league_tier!=null),sampleCount=Math.min(matchLimit,lm.length),sampled=lm.slice(0,sampleCount),sampledLast=sampled.at(-1)??null,final=lm.at(-1)??null;const won=sampled.filter(m=>m.result==='Won').length,drawn=sampled.filter(m=>m.result==='Draw').length,lost=sampled.filter(m=>m.result==='Lost').length,goalsFor=sampled.reduce((s,m)=>s+Number(m.leeds_score||0),0),goalsAgainst=sampled.reduce((s,m)=>s+Number(m.opponent_score||0),0),cleanSheets=sampled.filter(m=>Number(m.opponent_score)===0).length,managers=Array.from(new Set(sm.map(m=>m.leeds_manager).filter((m):m is string=>Boolean(m)))),tier=lm[0]?.league_tier??null,finalTier=tier,finalPosition=final?.league_position_after_match??null,nextTier=nextLeagueTier(season),statuses:string[]=[];if(finalPosition===1)statuses.push('Champions');if(finalTier!=null&&nextTier!=null&&nextTier<finalTier)statuses.push('Promoted');if(finalTier!=null&&nextTier!=null&&nextTier>finalTier)statuses.push('Relegated');if(season.season_id===newestSeasonId)statuses.push('Current');const rawFaCup=furthestRound(sm.filter(m=>m.competition==='FA Cup')),rawLeagueCup=furthestRound(sm.filter(m=>m.competition==='League Cup')),faCup=season.start_year===1971&&rawFaCup==='F'?'🏆 F':rawFaCup,leagueCup=season.start_year===1967&&rawLeagueCup==='F'?'🏆 F':rawLeagueCup,europeanGroups=new Map<string,SeasonMatch[]>();for(const match of sm.filter(m=>EUROPEAN_COMPETITIONS.has(m.competition))){const list=europeanGroups.get(match.competition)??[];list.push(match);europeanGroups.set(match.competition,list)}const europe=europeanGroups.size?Array.from(europeanGroups.entries()).map(([c,cm])=>`${europeanLabel(c)} ${furthestRound(cm)}`).join(' · '):'—';return{season,tier,finalTier,finalPosition:sampledLast?.league_position_after_match??null,matchesPlayed:sampleCount,won,drawn,lost,goalsFor,goalsAgainst,goalDifference:goalsFor-goalsAgainst,cleanSheets,points:sampledLast?.league_points_after_match??null,managers,statuses,faCup,leagueCup,europe}})},[seasons,matchesBySeason,fullSeasonState,matchLimit]);
const tiers=useMemo(()=>Array.from(new Set(summaries.map(s=>s.tier).filter((n):n is number=>n!=null))).sort((a,b)=>a-b),[summaries]);const filtered=useMemo(()=>summaries.filter(s=>tierFilter==='All Tiers'||s.tier===Number(tierFilter)),[summaries,tierFilter]);
const sortValue=(r:SeasonSummary,k:SortKey):string|number|null=>{switch(k){case'season':return r.season.start_year;case'tier':return r.tier;case'position':return r.finalPosition;case'matches':return r.matchesPlayed;case'won':return r.won;case'drawn':return r.drawn;case'lost':return r.lost;case'for':return r.goalsFor;case'against':return r.goalsAgainst;case'gd':return r.goalDifference;case'cs':return r.cleanSheets;case'points':return r.points;case'managers':return r.managers.join(' / ');case'status':return statusSortRank(r.statuses);case'faCup':return cupSortRank(r.faCup.replace('🏆 ',''));case'leagueCup':return cupSortRank(r.leagueCup.replace('🏆 ',''));case'europe':return cupSortRank(r.europe);default:return null}};
const visible=useMemo(()=>{const multiplier=sortDirection==='asc'?1:-1;return[...filtered].sort((a,b)=>{const av=sortValue(a,sortKey),bv=sortValue(b,sortKey);if(av==null&&bv==null)return b.season.start_year-a.season.start_year;if(av==null)return 1;if(bv==null)return-1;if(typeof av==='number'&&typeof bv==='number'){const d=av-bv;return d===0?b.season.start_year-a.season.start_year:d*multiplier}const d=String(av).localeCompare(String(bv));return d===0?b.season.start_year-a.season.start_year:d*multiplier})},[filtered,sortKey,sortDirection]);
const handleSort=(k:SortKey)=>{if(sortKey===k)setSortDirection(c=>c==='asc'?'desc':'asc');else{setSortKey(k);setSortDirection(k==='season'?'desc':'asc')}};
const SortHeader=({label,sort,className}:{label:string;sort:SortKey;className?:string})=><th className={className}><button type="button" className={`season-sort-button ${sortKey===sort?'active':''}`} onClick={()=>handleSort(sort)} aria-label={`Sort by ${label}`}><span>{label}</span>{sortKey===sort?(sortDirection==='asc'?<ChevronUp className="season-sort-icon"/>:<ChevronDown className="season-sort-icon"/>):null}</button></th>;
const renderStatus=(status:string)=>status==='Promoted'?<span key={status} className="season-status-mark season-status-promoted"><span aria-hidden="true">↑</span><span>Promoted</span></span>:status==='Relegated'?<span key={status} className="season-status-mark season-status-relegated"><span aria-hidden="true">↓</span><span>Relegated</span></span>:status==='Champions'?<span key={status} className="season-status-mark season-status-champions"><span aria-hidden="true">🏆</span><span>Champions</span></span>:<span key={status} className="season-status-mark season-status-current">Current</span>;
return <><style>{seasonStyles}</style><div className="card lb-table-card"><div className="lb-table-header"><div className="lb-title-group"><span className="section-kicker">Leeds United history</span><h2>Seasons</h2><p>League record, managers and cup progression across every Leeds United season</p></div><div className="section-kicker lb-match-count">{loading?'…':`${visible.length} Seasons Shown`}</div></div><div className="seasons-toolbar"><div className="lb-filter-section"><span className="lb-filter-label">League Tier</span><select className="lb-filter-select" value={tierFilter} onChange={e=>setTierFilter(e.target.value)} aria-label="League tier"><option value="All Tiers">All Tiers</option>{tiers.map(t=><option key={t} value={t}>Tier {t}</option>)}</select></div><div className="season-slider-block"><span className="lb-filter-label">League record after match</span><div className="season-slider-row"><input className="season-slider" type="range" min={1} max={LEAGUE_MATCH_MAX} step={1} value={matchLimit} onChange={e=>setMatchLimit(Number(e.target.value))} aria-label="League matches elapsed"/><span className="season-slider-value">{matchLimit}</span></div></div></div>
{loading?<div className="lb-loading">Building Leeds United season records…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:<div className="lb-table-wrap"><table className="lb-table seasons-table"><thead><tr><SortHeader label="Season" sort="season" className="season-name-col"/><SortHeader label="Tier" sort="tier"/><SortHeader label="Pos" sort="position"/><SortHeader label="Matches" sort="matches"/><SortHeader label="Won" sort="won"/><SortHeader label="Draw" sort="drawn"/><SortHeader label="Lost" sort="lost"/><SortHeader label="For" sort="for"/><SortHeader label="Against" sort="against"/><SortHeader label="GD" sort="gd"/><SortHeader label="CS" sort="cs"/><SortHeader label="PTS" sort="points"/><SortHeader label="Leeds Managers" sort="managers"/><SortHeader label="Champions / Promotion / Relegation" sort="status"/><SortHeader label="FA Cup" sort="faCup"/><SortHeader label="League Cup" sort="leagueCup"/><SortHeader label="Europe" sort="europe"/></tr></thead><tbody>{visible.map(r=><tr key={r.season.season_id}><td className="season-name-cell">{r.season.display_name}</td><td className="metric-value season-tier">{r.tier==null?'—':`T${r.tier}`}</td><td className="metric-value" style={{fontWeight:700}}>{ordinal(r.finalPosition)}</td><td className="metric-value">{r.matchesPlayed||'—'}</td><td className="metric-value">{r.matchesPlayed?r.won:'—'}</td><td className="metric-value">{r.matchesPlayed?r.drawn:'—'}</td><td className="metric-value">{r.matchesPlayed?r.lost:'—'}</td><td className="metric-value">{r.matchesPlayed?r.goalsFor:'—'}</td><td className="metric-value">{r.matchesPlayed?r.goalsAgainst:'—'}</td><td className={`metric-value ${r.goalDifference>0?'season-positive':r.goalDifference<0?'season-negative':''}`}>{r.matchesPlayed?(r.goalDifference>0?`+${r.goalDifference}`:r.goalDifference):'—'}</td><td className="metric-value">{r.matchesPlayed?r.cleanSheets:'—'}</td><td className="metric-value" style={{fontWeight:700}}>{r.points??'—'}</td><td className="season-manager-cell">{r.managers.length?r.managers.join(' / '):'—'}</td><td className="season-status-cell">{r.statuses.length?<div className="season-statuses">{r.statuses.map(renderStatus)}</div>:'—'}</td><td className="season-cup-cell">{r.faCup}</td><td className="season-cup-cell">{r.leagueCup}</td><td className="season-cup-cell">{r.europe}</td></tr>)}</tbody></table>{!visible.length&&<div className="lb-empty">No seasons match this tier.</div>}</div>}
<p className="season-deduction-note">Leeds were given a 10-point deduction by the Football League before for entering administration following the club's relegation during the 2006/07 season. The club also suffered a second points deduction by the authorities as chairman Ken Bates battled HMRC and were handed a 15-point penalty for exiting administration incorrectly ahead of the 2007/08 campaign.</p></div><div className="card lb-legend"><div className="lb-legend-items"><span>Click any column heading to sort; click again to reverse the order.</span><span>The slider recalculates Pos, Matches, W/D/L, For/Against, GD, CS and PTS after the selected number of league matches.</span><span>When a season contained fewer league matches than the selected number, its final available league record is shown.</span><span>Champions / Promoted / Relegated are season-end outcomes and do not change with the slider.</span><span>Cup columns show the furthest round reached: R1–R5, QF, SF, F; European group stages use GS1 / GS2.</span><span>Europe includes the Fairs Cup, European Cup, UEFA Cup, Cup Winners' Cup and Champions League.</span></div></div></>;
}
