import React,{useEffect,useMemo,useState}from'react';
import{supabase,supabaseConfigError}from'./supabase';

type Match={match_id:number;match_date:string;season:string|null;opponent:string;competition:string;venue_type:string;leeds_score:number;opponent_score:number;result:string;stadium:string|null;leeds_manager:string|null;first_goal:string|null};
type Goal={goal_id:number;match_id:number;leeds_player_id:number|null;assist_player_id:number|null;is_own_goal:boolean|null};
type Player={player_id:number;display_name:string;active:boolean|null};
type Stat={label:string;text:string};
const PAGE=1000;
async function loadPaged(table:string,columns:string,order:string){if(!supabase)return[] as any[];const out:any[]=[];for(let start=0;;start+=PAGE){const{data,error}=await supabase.from(table).select(columns).order(order,{ascending:true}).range(start,start+PAGE-1);if(error)throw error;out.push(...(data??[]));if((data??[]).length<PAGE)break}return out}
const record=(xs:Match[])=>{let w=0,d=0,l=0;for(const m of xs)m.result==='Won'?w++:m.result==='Draw'?d++:l++;return`W${w} D${d} L${l}`};
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
export default function StatPack(){
 const[matches,setMatches]=useState<Match[]>([]),[goals,setGoals]=useState<Goal[]>([]),[players,setPlayers]=useState<Player[]>([]),[opponent,setOpponent]=useState(''),[generated,setGenerated]=useState<Stat[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;(async()=>{try{const[m,g,p]=await Promise.all([loadPaged('match_centre_summary','match_id,match_date,season,opponent,competition,venue_type,leeds_score,opponent_score,result,stadium,leeds_manager,first_goal','match_id'),loadPaged('goals','goal_id,match_id,leeds_player_id,assist_player_id,is_own_goal','goal_id'),loadPaged('players','player_id,display_name,active','player_id')]);if(!cancelled){setMatches(m as Match[]);setGoals(g as Goal[]);setPlayers(p as Player[])}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
 const opponents=useMemo(()=>Array.from(new Set(matches.map(m=>m.opponent))).sort((a,b)=>a.localeCompare(b)),[matches]);
 const generate=()=>{if(!opponent)return;const chron=[...matches].sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id),recent=chron.slice(-6),h2h=chron.filter(m=>m.opponent===opponent),lastH2H=h2h.slice(-6),home=h2h.filter(m=>m.venue_type==='H'),away=h2h.filter(m=>m.venue_type==='A'),recentHome=home.slice(-6),recentAway=away.slice(-6),playerMap=new Map(players.map(p=>[p.player_id,p.display_name])),h2hIds=new Set(h2h.map(m=>m.match_id)),scorer=new Map<number,number>(),involvements=new Map<number,{g:number;a:number}>();for(const g of goals){if(!h2hIds.has(g.match_id))continue;if(g.leeds_player_id!=null&&!g.is_own_goal){scorer.set(g.leeds_player_id,(scorer.get(g.leeds_player_id)??0)+1);const x=involvements.get(g.leeds_player_id)??{g:0,a:0};x.g++;involvements.set(g.leeds_player_id,x)}if(g.assist_player_id!=null){const x=involvements.get(g.assist_player_id)??{g:0,a:0};x.a++;involvements.set(g.assist_player_id,x)}}const topScorer=[...scorer.entries()].sort((a,b)=>b[1]-a[1])[0],topGI=[...involvements.entries()].sort((a,b)=>(b[1].g+b[1].a)-(a[1].g+a[1].a))[0],opening=chron.filter(m=>m.first_goal==='Scored'),openingWins=opening.filter(m=>m.result==='Won').length,concededFirstVs=h2h.filter(m=>m.first_goal==='Conceded'),blankAfterConceding=concededFirstVs.filter(m=>m.leeds_score===0).length,currentManager=[...chron].reverse().find(m=>m.leeds_manager)?.leeds_manager??null,managerVs=currentManager?h2h.filter(m=>m.leeds_manager===currentManager):[];const stats:Stat[]=[];
 if(recent.length)stats.push({label:'Recent Form',text:`Leeds head into the upcoming match with ${opponent} having recorded ${record(recent)} across their last ${recent.length} competitive matches, scoring ${recent.reduce((s,m)=>s+m.leeds_score,0)} goals and conceding ${recent.reduce((s,m)=>s+m.opponent_score,0)}.`});
 if(lastH2H.length)stats.push({label:'Head-to-Head',text:`Leeds' last ${lastH2H.length} meetings with ${opponent} have produced a record of ${record(lastH2H)} (${lastH2H.reduce((s,m)=>s+m.leeds_score,0)} goals for, ${lastH2H.reduce((s,m)=>s+m.opponent_score,0)} against).`});
 if(recentHome.length)stats.push({label:'Fortress Elland Road',text:`At home to ${opponent}, Leeds have ${record(recentHome)} across the last ${recentHome.length} meetings, scoring ${recentHome.reduce((s,m)=>s+m.leeds_score,0)} and conceding ${recentHome.reduce((s,m)=>s+m.opponent_score,0)}.`});
 if(recentAway.length)stats.push({label:'Shaky On the Road',text:`Away to ${opponent}, Leeds' last ${recentAway.length} visits have returned ${record(recentAway)}, with ${recentAway.reduce((s,m)=>s+m.leeds_score,0)} goals scored and ${recentAway.reduce((s,m)=>s+m.opponent_score,0)} conceded.`});
 if(topScorer)stats.push({label:'Goalscoring Prowess',text:`${playerMap.get(topScorer[0])??'A Leeds player'} has scored ${topScorer[1]} Leeds goal${topScorer[1]===1?'':'s'} against ${opponent}, the leading total among players represented in the goal archive for this fixture.`});
 if(topGI){const x=topGI[1];stats.push({label:'Individual Nemesis',text:`${playerMap.get(topGI[0])??'A Leeds player'} has ${x.g+x.a} recorded direct goal involvement${x.g+x.a===1?'':'s'} against ${opponent} for Leeds (${x.g} goal${x.g===1?'':'s'}, ${x.a} assist${x.a===1?'':'s'}).`})}
 if(opening.length)stats.push({label:'First Goal Winning Record',text:`Leeds have won ${openingWins} of the ${opening.length} matches in the archive in which they scored the opening goal (${pct(openingWins,opening.length)}%).`});
 if(concededFirstVs.length)stats.push({label:'First Goal Conceded Record',text:`Against ${opponent}, Leeds have failed to score in ${blankAfterConceding} of ${concededFirstVs.length} matches in which they conceded the opening goal.`});
 if(managerVs.length&&currentManager)stats.push({label:'Manager v Opponent',text:`${currentManager}'s Leeds record against ${opponent} is ${record(managerVs)} from ${managerVs.length} meeting${managerVs.length===1?'':'s'} (${pct(managerVs.filter(m=>m.result==='Won').length,managerVs.length)}% wins).`});
 setGenerated(stats)};
 return <div className="card lb-table-card"><div className="lb-table-header"><div className="lb-title-group"><span className="section-kicker">Upcoming match intelligence</span><h2>Stat Pack</h2><p>Opponent-led, archive-grounded Leeds United pre-match statistical briefing</p></div></div><div className="lb-filterbar"><div className="lb-filter-section"><span className="lb-filter-label">Opponent</span><select className="lb-filter-select" value={opponent} onChange={e=>{setOpponent(e.target.value);setGenerated([])}} disabled={loading}><option value="">Opponent</option>{opponents.map(o=><option key={o} value={o}>{o}</option>)}</select></div><button className="lb-filter-pill active" style={{height:30,padding:'0 16px'}} disabled={!opponent||loading} onClick={generate}>Generate Stat Pack</button></div>{loading?<div className="lb-loading">Loading the Leeds United archive…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:generated.length?<div style={{padding:'22px 24px 28px'}}>{generated.map((s,i)=><div key={`${s.label}-${i}`} style={{marginBottom:i===generated.length-1?0:24}}><div className="section-kicker" style={{marginBottom:7}}>{s.label}</div><div style={{fontSize:14,lineHeight:1.65,maxWidth:1050}}>{s.text}</div></div>)}</div>:<div className="lb-loading">Select the upcoming opponent, then generate the pre-match Stat Pack.</div>}</div>
}
