import React,{useEffect,useMemo,useState}from'react';
import{supabase,supabaseConfigError}from'./supabase';

type Match={match_id:number;match_date:string;season:string|null;opponent:string;competition:string;venue_type:string;leeds_score:number;opponent_score:number;result:string;stadium:string|null;leeds_manager:string|null;opposition_manager_name:string|null;first_goal:string|null;captain_player_id:number|null;half_time_leeds_score:number|null;half_time_opponent_score:number|null;kickoff_time:string|null};
type Goal={goal_id:number;match_id:number;leeds_player_id:number|null;assist_player_id:number|null;is_own_goal:boolean|null;minute_normalised:number|null};
type Player={player_id:number;display_name:string;active:boolean|null;position_group:string|null};
type PlayerMatch={player_match_id:number;match_id:number;player_id:number;started:boolean;substitute:boolean};
type Stat={label:string;text:string;grade:'A'|'B';priority:number};
const PAGE=1000;
const LEAGUE_COMPS=new Set(['Premier League','Championship','Division One','Division Two','League One']);
const MILESTONES=[10,25,50,75,100,150,200,250,300,400,500];
async function loadPaged(table:string,columns:string,order:string){if(!supabase)return[] as any[];const out:any[]=[];for(let start=0;;start+=PAGE){const{data,error}=await supabase.from(table).select(columns).order(order,{ascending:true}).range(start,start+PAGE-1);if(error)throw error;out.push(...(data??[]));if((data??[]).length<PAGE)break}return out}
const record=(xs:Match[])=>{let w=0,d=0,l=0;for(const m of xs)m.result==='Won'?w++:m.result==='Draw'?d++:l++;return`W${w} D${d} L${l}`};
const pct=(n:number,d:number)=>d?Math.round(n/d*100):0;
const year=(d:string)=>new Date(`${d}T00:00:00`).getFullYear();
const monthName=(d:string)=>new Date(`${d}T00:00:00`).toLocaleDateString('en-GB',{month:'long'});
const trailing=(xs:Match[],test:(m:Match)=>boolean)=>{let n=0;for(let i=xs.length-1;i>=0;i--){if(!test(xs[i]))break;n++}return n};
const league=(m:Match)=>LEAGUE_COMPS.has(m.competition);
const nextMilestone=(n:number)=>MILESTONES.find(x=>x===n+1)??null;
export default function StatPack(){
 const[matches,setMatches]=useState<Match[]>([]),[goals,setGoals]=useState<Goal[]>([]),[players,setPlayers]=useState<Player[]>([]),[playerMatches,setPlayerMatches]=useState<PlayerMatch[]>([]),[opponent,setOpponent]=useState(''),[generated,setGenerated]=useState<Stat[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{if(!supabase){setLoading(false);return}let cancelled=false;(async()=>{try{const[m,g,p,pm]=await Promise.all([loadPaged('match_centre_summary','match_id,match_date,season,opponent,competition,venue_type,leeds_score,opponent_score,result,stadium,leeds_manager,opposition_manager_name,first_goal,captain_player_id,half_time_leeds_score,half_time_opponent_score,kickoff_time','match_id'),loadPaged('goals','goal_id,match_id,leeds_player_id,assist_player_id,is_own_goal,minute_normalised','goal_id'),loadPaged('players','player_id,display_name,active,position_group','player_id'),loadPaged('player_matches','player_match_id,match_id,player_id,started,substitute','player_match_id')]);if(!cancelled){setMatches(m as Match[]);setGoals(g as Goal[]);setPlayers(p as Player[]);setPlayerMatches(pm as PlayerMatch[])}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:String(e))}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[]);
 const opponents=useMemo(()=>Array.from(new Set(matches.map(m=>m.opponent))).sort((a,b)=>a.localeCompare(b)),[matches]);
 const generate=()=>{if(!opponent)return;const chron=[...matches].sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id),matchMap=new Map(chron.map(m=>[m.match_id,m])),playerMap=new Map(players.map(p=>[p.player_id,p.display_name])),activeIds=new Set(players.filter(p=>p.active).map(p=>p.player_id)),recent=chron.slice(-6),h2h=chron.filter(m=>m.opponent===opponent),leagueH2H=h2h.filter(league),lastH2H=h2h.slice(-6),home=h2h.filter(m=>m.venue_type==='H'),away=h2h.filter(m=>m.venue_type==='A'),recentHome=home.slice(-6),recentAway=away.slice(-6),currentManager=[...chron].reverse().find(m=>m.leeds_manager)?.leeds_manager??null,currentYear=year(chron[chron.length-1]?.match_date??new Date().toISOString().slice(0,10)),currentMonth=monthName(chron[chron.length-1]?.match_date??new Date().toISOString().slice(0,10));const stats:Stat[]=[];
 const push=(label:string,text:string,grade:'A'|'B'='B',priority=50)=>stats.push({label,text,grade,priority});
 if(recent.length)push('Recent Form',`Leeds head into the upcoming match with ${opponent} having recorded ${record(recent)} across their last ${recent.length} competitive matches, scoring ${recent.reduce((s,m)=>s+m.leeds_score,0)} goals and conceding ${recent.reduce((s,m)=>s+m.opponent_score,0)}.`,`B`,40);
 if(lastH2H.length)push('Head-to-Head',`Leeds' last ${lastH2H.length} meetings with ${opponent} have produced a record of ${record(lastH2H)} (${lastH2H.reduce((s,m)=>s+m.leeds_score,0)} goals for, ${lastH2H.reduce((s,m)=>s+m.opponent_score,0)} against).`,`B`,45);
 if(recentHome.length)push('Fortress Elland Road',`At home to ${opponent}, Leeds have ${record(recentHome)} across the last ${recentHome.length} meetings, scoring ${recentHome.reduce((s,m)=>s+m.leeds_score,0)} and conceding ${recentHome.reduce((s,m)=>s+m.opponent_score,0)}.`,`B`,35);
 if(recentAway.length)push('Shaky On the Road',`Away to ${opponent}, Leeds' last ${recentAway.length} visits have returned ${record(recentAway)}, with ${recentAway.reduce((s,m)=>s+m.leeds_score,0)} goals scored and ${recentAway.reduce((s,m)=>s+m.opponent_score,0)} conceded.`,`B`,35);
 const awayWins=away.filter(m=>m.result==='Won');if(away.length&&!awayWins.length){const stadium=away[away.length-1]?.stadium;push('Long-Awaited Landmark',`Leeds are looking for their first victory away to ${opponent}${stadium?` at ${stadium}`:''} in the recorded competitive archive.`,`A`,100)}else if(leagueH2H.length){const leagueAway=leagueH2H.filter(m=>m.venue_type==='A'),lastLeagueAwayWin=[...leagueAway].reverse().find(m=>m.result==='Won');if(lastLeagueAwayWin&&leagueAway[leagueAway.length-1]?.match_id!==lastLeagueAwayWin.match_id){const since=leagueAway.filter(m=>m.match_date>lastLeagueAwayWin.match_date);if(since.length>=3)push('Long-Awaited League Landmark',`Leeds are looking for their first league win away to ${opponent} since ${new Date(`${lastLeagueAwayWin.match_date}T00:00:00`).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}, having gone ${since.length} league visit${since.length===1?'':'s'} without victory since then.`,`A`,98)}}
 const h2hIds=new Set(h2h.map(m=>m.match_id)),scorer=new Map<number,number>(),involvements=new Map<number,{g:number;a:number}>(),playerOpponentMatches=new Map<number,Match[]>();for(const pm of playerMatches){const m=matchMap.get(pm.match_id);if(m&&m.opponent===opponent){const a=playerOpponentMatches.get(pm.player_id)??[];a.push(m);playerOpponentMatches.set(pm.player_id,a)}}for(const g of goals){if(!h2hIds.has(g.match_id))continue;if(g.leeds_player_id!=null&&!g.is_own_goal){scorer.set(g.leeds_player_id,(scorer.get(g.leeds_player_id)??0)+1);const x=involvements.get(g.leeds_player_id)??{g:0,a:0};x.g++;involvements.set(g.leeds_player_id,x)}if(g.assist_player_id!=null){const x=involvements.get(g.assist_player_id)??{g:0,a:0};x.a++;involvements.set(g.assist_player_id,x)}}
 const topScorer=[...scorer.entries()].sort((a,b)=>b[1]-a[1])[0],topGI=[...involvements.entries()].sort((a,b)=>(b[1].g+b[1].a)-(a[1].g+a[1].a))[0];if(topScorer)push('Goalscoring Prowess',`${playerMap.get(topScorer[0])??'A Leeds player'} has scored ${topScorer[1]} Leeds goal${topScorer[1]===1?'':'s'} against ${opponent}, the leading total represented in the archive for this fixture.`,`B`,55);if(topGI){const x=topGI[1];push('Individual Nemesis',`${playerMap.get(topGI[0])??'A Leeds player'} has ${x.g+x.a} recorded direct goal involvement${x.g+x.a===1?'':'s'} against ${opponent} for Leeds (${x.g} goals, ${x.a} assists).`,`B`,65)}
 for(const pid of activeIds){const appearances=[...(playerOpponentMatches.get(pid)??[])].sort((a,b)=>a.match_date.localeCompare(b.match_date)||a.match_id-b.match_id);if(!appearances.length)continue;const scoredMatches=new Set(goals.filter(g=>g.leeds_player_id===pid&&!g.is_own_goal&&h2hIds.has(g.match_id)).map(g=>g.match_id));let streak=0;for(let i=appearances.length-1;i>=0;i--){if(!scoredMatches.has(appearances[i].match_id))break;streak++}if(streak>=2){let previous:{pid:number;date:string;streak:number}|null=null;for(const [otherId,otherApps] of playerOpponentMatches){if(otherId===pid)continue;const oa=[...otherApps].sort((a,b)=>a.match_date.localeCompare(b.match_date));const os=new Set(goals.filter(g=>g.leeds_player_id===otherId&&!g.is_own_goal&&h2hIds.has(g.match_id)).map(g=>g.match_id));let best=0,run=0,end='';for(const m of oa){if(os.has(m.match_id)){run++;if(run>best){best=run;end=m.match_date}}else run=0}if(best>=streak+1&&(!previous||end>previous.date))previous={pid:otherId,date:end,streak:best}}push('Player Landmark Scoring Streak',`${playerMap.get(pid)??'A Leeds player'} could score in ${streak+1} consecutive appearances against ${opponent}${previous?`, a run not matched by a Leeds player since ${playerMap.get(previous.pid)??'another Leeds player'} in ${new Date(`${previous.date}T00:00:00`).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}`:''}.`,`A`,96)}
 const apps=playerMatches.filter(pm=>pm.player_id===pid).map(pm=>matchMap.get(pm.match_id)).filter((m):m is Match=>Boolean(m));const wins=apps.filter(m=>m.result==='Won').length,milestone=nextMilestone(wins);if(milestone&&apps.length){const captained=apps.filter(m=>m.captain_player_id===pid).length;if(captained>0)push('Captain Milestone',`${playerMap.get(pid)??'A Leeds player'} is one win away from ${milestone} victories in his Leeds appearances; ${captained} of those appearances have come as captain.`,`A`,88)}
 const monthGoals=goals.filter(g=>g.leeds_player_id===pid&&!g.is_own_goal).filter(g=>{const m=matchMap.get(g.match_id);return m&&m.competition==='Premier League'&&monthName(m.match_date)===currentMonth}).length;if(monthGoals>=3){push('Calendar Goal Milestone',`${playerMap.get(pid)??'A Leeds player'} has ${monthGoals} Premier League goals in ${currentMonth} across the archive and is approaching a notable monthly scoring landmark.`,`A`,82)}
 }
 const opening=chron.filter(m=>m.first_goal==='Scored'),openingWins=opening.filter(m=>m.result==='Won').length,concededFirstVs=h2h.filter(m=>m.first_goal==='Conceded'),blankAfterConceding=concededFirstVs.filter(m=>m.leeds_score===0).length;if(opening.length)push('First Goal Winning Record',`Leeds have won ${openingWins} of the ${opening.length} matches in the archive in which they scored the opening goal (${pct(openingWins,opening.length)}%).`,`B`,60);if(concededFirstVs.length)push('First Goal Conceded Record',`Against ${opponent}, Leeds have failed to score in ${blankAfterConceding} of ${concededFirstVs.length} matches in which they conceded the opening goal.`,`B`,58);
 if(currentManager){const managerMatches=chron.filter(m=>m.leeds_manager===currentManager),managerVs=h2h.filter(m=>m.leeds_manager===currentManager),leagueManager=managerMatches.filter(league),leagueWins=trailing(leagueManager,m=>m.result==='Won'),leagueLosses=trailing(leagueManager,m=>m.result==='Lost'),leagueUnbeaten=trailing(leagueManager,m=>m.result!=='Lost'),yearLeague=leagueManager.filter(m=>year(m.match_date)===currentYear),yearUnbeaten=trailing(yearLeague,m=>m.result!=='Lost');if(managerVs.length)push('Manager v Opponent',`${currentManager}'s Leeds record against ${opponent} is ${record(managerVs)} from ${managerVs.length} meeting${managerVs.length===1?'':'s'} (${pct(managerVs.filter(m=>m.result==='Won').length,managerVs.length)}% wins).`,`B`,70);if(leagueWins>=2)push('Manager Winning Streak',`${currentManager} is looking to make it ${leagueWins+1} consecutive league wins as Leeds manager.`,`A`,93);if(leagueLosses>=2)push('Manager Avoiding Landmark Losing Streak',`${currentManager} is looking to avoid a ${leagueLosses+1}th consecutive league defeat as Leeds manager.`,`A`,95);if(leagueUnbeaten>=5)push('Manager Unbeaten Run',`${currentManager} is one match away from extending Leeds' current league unbeaten run under him to ${leagueUnbeaten+1} matches.`,`A`,91);if(yearUnbeaten>=5)push('Manager Calendar-Year Run',`${currentManager} is looking to extend his unbeaten league run in ${currentYear} to ${yearUnbeaten+1} matches.`,`A`,92);const vsWins=trailing(managerVs,m=>m.result==='Won'),vsUnbeaten=trailing(managerVs,m=>m.result!=='Lost');if(vsWins>=2)push('Manager v Opponent Winning Streak',`${currentManager} could record a ${vsWins+1}th consecutive victory as Leeds manager against ${opponent}.`,`A`,90);if(vsUnbeaten>=3)push('Manager v Opponent Unbeaten Streak',`${currentManager} is unbeaten in his last ${vsUnbeaten} Leeds matches against ${opponent} and could extend that run to ${vsUnbeaten+1}.`,`A`,89)}
 const leagueRecent=chron.filter(league),teamLeagueWinStreak=trailing(leagueRecent,m=>m.result==='Won'),teamLeagueUnbeaten=trailing(leagueRecent,m=>m.result!=='Lost');if(teamLeagueWinStreak>=3)push('Landmark Winning Streak',`Leeds are looking to make it ${teamLeagueWinStreak+1} consecutive league victories.`,`A`,90);if(teamLeagueUnbeaten>=8)push('Unbeaten League Run',`Leeds are unbeaten in ${teamLeagueUnbeaten} consecutive league matches and can extend the run to ${teamLeagueUnbeaten+1} against ${opponent}.`,`A`,92);
 const early=chron.slice(-20).reduce((n,m)=>n+goals.filter(g=>g.match_id===m.match_id&&!g.is_own_goal&&g.minute_normalised!=null&&g.minute_normalised<=15).length,0),late=chron.slice(-20).reduce((n,m)=>n+goals.filter(g=>g.match_id===m.match_id&&!g.is_own_goal&&g.minute_normalised!=null&&g.minute_normalised>=76).length,0);if(early||late)push('Early / Late Surge',`Across Leeds' last 20 matches in the archive, ${early} Leeds goals arrived in the opening 15 minutes and ${late} after the 75th minute.`,`B`,42);
 stats.sort((a,b)=>b.priority-a.priority||a.label.localeCompare(b.label));setGenerated(stats.slice(0,30))};
 return <div className="card lb-table-card"><div className="lb-table-header"><div className="lb-title-group"><span className="section-kicker">Upcoming match intelligence</span><h2>Stat Pack</h2><p>Grade A milestone-led, opponent-specific Leeds United pre-match statistical briefing</p></div></div><div className="lb-filterbar"><div className="lb-filter-section"><span className="lb-filter-label">Opponent</span><select className="lb-filter-select" value={opponent} onChange={e=>{setOpponent(e.target.value);setGenerated([])}} disabled={loading}><option value="">Opponent</option>{opponents.map(o=><option key={o} value={o}>{o}</option>)}</select></div><button className="lb-filter-pill active" style={{height:30,padding:'0 16px'}} disabled={!opponent||loading} onClick={generate}>Generate Stat Pack</button></div>{loading?<div className="lb-loading">Loading the Leeds United archive…</div>:error?<div className="lb-loading"><strong>Data connection error:</strong> {error}</div>:generated.length?<div style={{padding:'22px 24px 28px'}}>{generated.map((s,i)=><div key={`${s.label}-${i}`} style={{marginBottom:i===generated.length-1?0:26,paddingBottom:i===generated.length-1?0:2}}><div className="section-kicker" style={{marginBottom:7}}>{s.grade==='A'?'GRADE A · ':''}{s.label}</div><div style={{fontSize:14,lineHeight:1.7,maxWidth:1050}}>{s.text}</div></div>)}</div>:<div className="lb-loading">Select the upcoming opponent, then generate the pre-match Stat Pack.</div>}</div>
}
