import React,{useEffect,useMemo,useState}from'react';
import{ChevronRight}from'lucide-react';
import PlayerIcon from'./PlayerIcon';
import NationalityFlag from'./NationalityFlag';
import ClubCrest from'./ClubCrest';
import{supabase,supabaseConfigError}from'./supabase';
import'./TestA1.css';

type Player={player_id:number;legacy_player_id:number;display_name:string;full_name:string|null;declared_nation:string|null;date_of_birth:string|null;birth_date_precision:string|null;position_group:string|null;position_detail:string|null;profile_image_url:string|null};
type Leader={player_id:number;player:string;appearances:number;starts:number;sub_apps:number;sub_off:number;won:number;win_pct:number|string;goals:number;captain:number;profile_image_url:string|null};
type PM={match_id:number};
type Match={match_id:number;match_date:string;season:string|null;opponent:string;opponent_crest_url:string|null;competition:string;round:string|null;venue_type:string;leeds_score:number;opponent_score:number;result:string};
type Spell={spell_sequence:number;start_year:number;end_year:number|null;is_current:boolean};
const PLAYER_ID=276;
const dob=(v:string|null,p:string|null)=>!v||p==='unknown'?'—':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00Z`));
const spell=(s:Spell)=>s.is_current||s.end_year==null?`${s.start_year}–present`:s.start_year===s.end_year?String(s.start_year):`${s.start_year}–${s.end_year}`;
const venue=(v:string)=>v==='H'?'H':v==='A'?'A':'N';
const form=(r:string)=>r==='Won'?'W':r==='Lost'?'L':'D';
export default function TestA1(){
 const[player,setPlayer]=useState<Player|null>(null),[leaders,setLeaders]=useState<Leader[]>([]),[matches,setMatches]=useState<Match[]>([]),[career,setCareer]=useState('—'),[status,setStatus]=useState<'Active'|'Former'>('Former'),[seasons,setSeasons]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);const[{data:p,error:pe},{data:lb,error:le},{data:pm,error:pme},{data:sp,error:se}]=await Promise.all([supabase.from('players').select('player_id,legacy_player_id,display_name,full_name,declared_nation,date_of_birth,birth_date_precision,position_group,position_detail,profile_image_url').eq('player_id',PLAYER_ID).maybeSingle(),supabase.rpc('filtered_player_leaderboard',{p_filter:'All',p_venue:'All'}),supabase.from('player_matches').select('match_id').eq('player_id',PLAYER_ID),supabase.from('player_spells').select('spell_sequence,start_year,end_year,is_current').eq('player_id',PLAYER_ID).order('spell_sequence',{ascending:true})]);const e=pe??le??pme??se;if(e){if(!cancelled){setError(e.message);setLoading(false)}return}const ids=((pm??[])as PM[]).map(x=>x.match_id),batches=[] as PromiseLike<any>[];for(let i=0;i<ids.length;i+=200)batches.push(supabase.from('match_centre_summary').select('match_id,match_date,season,opponent,opponent_crest_url,competition,round,venue_type,leeds_score,opponent_score,result').in('match_id',ids.slice(i,i+200)));const batchResults=ids.length?await Promise.all(batches):[];const me=batchResults.find(x=>x.error)?.error;if(me){if(!cancelled){setError(me.message);setLoading(false)}return}const allMatches=batchResults.flatMap(x=>(x.data??[])as Match[]),latest=[...allMatches].sort((a,b)=>b.match_date.localeCompare(a.match_date)||b.match_id-a.match_id).slice(0,10);if(!cancelled){setPlayer(p as Player);setLeaders(((lb??[])as Leader[]).sort((a,b)=>Number(b.appearances)-Number(a.appearances)||a.player_id-b.player_id));setMatches(latest);setSeasons(new Set(allMatches.map(m=>m.season).filter((s):s is string=>Boolean(s))).size);const ss=(sp??[])as Spell[];setCareer(ss.length?ss.map(spell).join(' · '):'—');setStatus(ss.some(s=>s.is_current)?'Active':'Former');setLoading(false)}})();return()=>{cancelled=true}},[]);
 const current=useMemo(()=>leaders.find(x=>x.player_id===PLAYER_ID),[leaders]);const top=useMemo(()=>leaders.slice(0,5),[leaders]);const rank=current?1+leaders.filter(x=>Number(x.appearances)>Number(current.appearances)).length:0;
 if(loading)return <div className="test-a1-shell"><div className="card lb-loading">Loading Test A1…</div></div>;if(error||!player||!current)return <div className="test-a1-shell"><div className="card lb-loading">Test A1 unavailable: {error??'Player data unavailable'}</div></div>;
 const positions=[player.position_detail,player.position_group].filter(Boolean).join(' · '),playerStats:[string,string|number][]=[['Appearances',current.appearances],['Starts',current.starts],['Sub On',current.sub_apps],['Sub Off',current.sub_off],['Goals',current.goals],['Wins',current.won],['Win Rate',`${Number(current.win_pct).toFixed(1)}%`],['Seasons',seasons||'—']];
 return <div className="test-a1-shell"><div className="test-a1-label"><span>Experimental UI</span><strong>Test A1</strong><small>Billy Bremner profile concept · isolated from signed-off Player Page</small></div><div className="test-a1-grid">
  <section className="card test-a1-hero"><div className="test-a1-hero-copy"><span className="section-kicker">Leeds United · Player Profile</span><div className="test-a1-name-row"><div className="test-a1-mini-icon"><PlayerIcon name={player.display_name} src={player.profile_image_url}/></div><div><h1>{player.display_name}</h1><p>{player.full_name??player.display_name}</p></div></div><div className="test-a1-facts"><div><span>Declared Nation</span><strong>{player.declared_nation?<><NationalityFlag nation={player.declared_nation}/>{player.declared_nation}</>:<>—</>}</strong></div><div><span>Born</span><strong>{dob(player.date_of_birth,player.birth_date_precision)}</strong></div><div><span>Career</span><strong>{career}</strong></div><div><span>Positions</span><strong>{positions||'—'}</strong></div><div><span>Legacy Number</span><strong>#{player.legacy_player_id}</strong></div><div className="test-a1-status-fact"><span>Player Status</span><strong className={`test-a1-status ${status.toLowerCase()}`}>{status}</strong></div></div></div></section>
  <section className="card test-a1-matchlog"><header><div><span className="section-kicker">Career chronology</span><h2>Match Log <ChevronRight size={15}/></h2></div><b>{current.appearances} apps</b></header><div className="test-a1-match-list">{matches.map(m=><div className="test-a1-match" key={m.match_id}><div className="test-a1-match-meta"><span>{m.competition}{m.round?` · ${m.round}`:''}</span><small>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${m.match_date}T12:00:00Z`))}</small></div><div className="test-a1-opponent"><ClubCrest crestUrl={m.opponent_crest_url} name={m.opponent}/><strong>{m.opponent} <em>({venue(m.venue_type)})</em></strong></div><div className="test-a1-score"><span className={`test-a1-form ${form(m.result).toLowerCase()}`}>{form(m.result)}</span><b>{m.leeds_score}–{m.opponent_score}</b></div></div>)}</div></section>
  <section className="card test-a1-stats"><header><h2>Player Stats <ChevronRight size={17}/></h2></header><div className="test-a1-stat-list">{playerStats.map(([k,v])=><div className="test-a1-stat" key={k}><span>{k}</span><strong className="test-a1-stat-value">{v}</strong></div>)}</div></section>
  <section className="card test-a1-standing"><header><div><span className="section-kicker">All-time Leeds United</span><h2>Appearance Ranking <ChevronRight size={15}/></h2></div><b>#{rank}</b></header><div className="test-a1-standing-head"><span>#</span><span>Player</span><span>Apps</span></div>{top.map((r,i)=><div className={`test-a1-standing-row ${r.player_id===PLAYER_ID?'you':''}`} key={r.player_id}><span>{i+1}</span><div><div className="test-a1-rank-icon"><PlayerIcon name={r.player} src={r.profile_image_url}/></div><strong>{r.player}</strong>{r.player_id===PLAYER_ID?<small>You</small>:null}</div><b>{r.appearances}</b></div>)}</section>
  <section className="card test-a1-summary"><header><h2>Career Record <ChevronRight size={15}/></h2></header><div className="test-a1-summary-grid"><div><span>Starts</span><strong>{current.starts}</strong></div><div><span>Wins</span><strong>{current.won}</strong></div><div><span>Win Rate</span><strong>{Number(current.win_pct).toFixed(1)}%</strong></div><div><span>Goals</span><strong>{current.goals}</strong></div></div><div className="test-a1-spark"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></section>
  <section className="card test-a1-timeline"><header><h2>Leeds Career <ChevronRight size={15}/></h2></header><div className="test-a1-timeline-main"><strong>{career}</strong><span>772 competitive appearances across Billy Bremner's Leeds United career.</span><div className="test-a1-line"><i/></div><div className="test-a1-years"><span>1959</span><span>1965</span><span>1970</span><span>1976</span></div></div></section>
 </div></div>;
}
