import React,{useEffect,useMemo,useState}from'react';
import{ChevronRight,TrendingDown,TrendingUp}from'lucide-react';
import PlayerIcon from'./PlayerIcon';
import NationalityFlag from'./NationalityFlag';
import ClubCrest from'./ClubCrest';
import{supabase,supabaseConfigError}from'./supabase';
import'./TestA1.css';

type Player={player_id:number;legacy_player_id:number;display_name:string;full_name:string|null;declared_nation:string|null;date_of_birth:string|null;birth_date_precision:string|null;position_group:string|null;position_detail:string|null;profile_image_url:string|null};
type Leader={player_id:number;player:string;appearances:number;starts:number;won:number;win_pct:number|string;goals:number;captain:number;profile_image_url:string|null};
type PM={match_id:number};
type Match={match_id:number;match_date:string;season:string|null;opponent:string;opponent_crest_url:string|null;competition:string;round:string|null;venue_type:string;leeds_score:number;opponent_score:number;result:string;captain_player_id:number|null};
type Spell={spell_sequence:number;start_year:number;end_year:number|null;is_current:boolean};
type Goal={goal_id:number;match_id:number;minute_raw:string|null;minute_normalised:number|null};
type Sub={substitution_id:number;match_id:number;minute_raw:string|null;minute_base:number|null;stoppage_minute:number|null;timing_known:boolean;player_on_id:number|null;player_off_id:number|null};
type Red={match_id:number;minute_raw:string|null;issued:string|null};
type MatchEvents={goals:Goal[];captain:boolean;red:Red|null;subOn:Sub|null;subOff:Sub|null};
const PLAYER_ID=276;
const dob=(v:string|null,p:string|null)=>!v||p==='unknown'?'—':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00Z`));
const spell=(s:Spell)=>s.is_current||s.end_year==null?`${s.start_year}–present`:s.start_year===s.end_year?String(s.start_year):`${s.start_year}–${s.end_year}`;
const venue=(v:string)=>v==='H'?'H':v==='A'?'A':'N';
const form=(r:string)=>r==='Won'?'W':r==='Lost'?'L':'D';
const appIcon=(name:string)=>`/appicons/${encodeURIComponent(name)}`;
const subMinute=(s:Sub|null)=>{if(!s||!s.timing_known)return'—';if(s.minute_raw)return s.minute_raw.replace(/'+$/,'');if(s.minute_base==null)return'—';return s.stoppage_minute?`${s.minute_base}+${s.stoppage_minute}`:String(s.minute_base)};
export default function TestA1(){
 const[player,setPlayer]=useState<Player|null>(null),[leaders,setLeaders]=useState<Leader[]>([]),[matches,setMatches]=useState<Match[]>([]),[events,setEvents]=useState<Map<number,MatchEvents>>(new Map()),[career,setCareer]=useState('—'),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(supabaseConfigError);
 useEffect(()=>{let cancelled=false;(async()=>{if(!supabase){setLoading(false);return}setLoading(true);setError(null);const[{data:p,error:pe},{data:lb,error:le},{data:pm,error:pme},{data:sp,error:se}]=await Promise.all([supabase.from('players').select('player_id,legacy_player_id,display_name,full_name,declared_nation,date_of_birth,birth_date_precision,position_group,position_detail,profile_image_url').eq('player_id',PLAYER_ID).maybeSingle(),supabase.rpc('filtered_player_leaderboard',{p_filter:'All',p_venue:'All'}),supabase.from('player_matches').select('match_id').eq('player_id',PLAYER_ID),supabase.from('player_spells').select('spell_sequence,start_year,end_year,is_current').eq('player_id',PLAYER_ID).order('spell_sequence',{ascending:true})]);const e=pe??le??pme??se;if(e){if(!cancelled){setError(e.message);setLoading(false)}return}const ids=((pm??[])as PM[]).map(x=>x.match_id);const{data:ms,error:me}=ids.length?await supabase.from('match_centre_summary').select('match_id,match_date,season,opponent,opponent_crest_url,competition,round,venue_type,leeds_score,opponent_score,result,captain_player_id').in('match_id',ids).order('match_date',{ascending:false}).order('match_id',{ascending:false}).limit(10):{data:[],error:null};if(me){if(!cancelled){setError(me.message);setLoading(false)}return}const matchRows=(ms??[])as Match[],matchIds=matchRows.map(m=>m.match_id);const[{data:g,error:ge},{data:subs,error:sue},{data:reds,error:re}]=matchIds.length?await Promise.all([supabase.from('goals').select('goal_id,match_id,minute_raw,minute_normalised').eq('leeds_player_id',PLAYER_ID).in('match_id',matchIds),supabase.from('match_substitutions').select('substitution_id,match_id,minute_raw,minute_base,stoppage_minute,timing_known,player_on_id,player_off_id').in('match_id',matchIds).or(`player_on_id.eq.${PLAYER_ID},player_off_id.eq.${PLAYER_ID}`),supabase.from('player_red_cards').select('match_id,minute_raw,issued').eq('player_id',PLAYER_ID).in('match_id',matchIds)]):[{data:[],error:null},{data:[],error:null},{data:[],error:null}];const eventError=ge??sue??re;if(eventError){if(!cancelled){setError(eventError.message);setLoading(false)}return}const goalRows=(g??[])as Goal[],subRows=(subs??[])as Sub[],redRows=(reds??[])as Red[],map=new Map<number,MatchEvents>();for(const m of matchRows){map.set(m.match_id,{goals:goalRows.filter(x=>x.match_id===m.match_id),captain:Number(m.captain_player_id)===PLAYER_ID,red:redRows.find(x=>x.match_id===m.match_id)??null,subOn:subRows.find(x=>x.match_id===m.match_id&&Number(x.player_on_id)===PLAYER_ID)??null,subOff:subRows.find(x=>x.match_id===m.match_id&&Number(x.player_off_id)===PLAYER_ID)??null})}if(!cancelled){setPlayer(p as Player);setLeaders(((lb??[])as Leader[]).sort((a,b)=>Number(b.appearances)-Number(a.appearances)||a.player_id-b.player_id));setMatches(matchRows);setEvents(map);const ss=(sp??[])as Spell[];setCareer(ss.length?ss.map(spell).join(' · '):'—');setLoading(false)}})();return()=>{cancelled=true}},[]);
 const current=useMemo(()=>leaders.find(x=>x.player_id===PLAYER_ID),[leaders]);const top=useMemo(()=>leaders.slice(0,5),[leaders]);const rank=current?1+leaders.filter(x=>Number(x.appearances)>Number(current.appearances)).length:0;
 if(loading)return <div className="test-a1-shell"><div className="card lb-loading">Loading Test A1…</div></div>;if(error||!player||!current)return <div className="test-a1-shell"><div className="card lb-loading">Test A1 unavailable: {error??'Player data unavailable'}</div></div>;
 const positions=[player.position_detail,player.position_group].filter(Boolean).join(' · ');
 return <div className="test-a1-shell"><div className="test-a1-label"><span>Experimental UI</span><strong>Test A1</strong><small>Billy Bremner profile concept · isolated from signed-off Player Page</small></div><div className="test-a1-grid">
  <section className="card test-a1-hero"><div className="test-a1-hero-copy"><span className="section-kicker">Leeds United · Player Profile</span><div className="test-a1-name-row"><div className="test-a1-mini-icon"><PlayerIcon name={player.display_name} src={player.profile_image_url}/></div><div><h1>{player.display_name}</h1><p>{player.full_name??player.display_name}</p></div></div><div className="test-a1-facts"><div><span>Declared Nation</span><strong>{player.declared_nation?<><NationalityFlag nation={player.declared_nation}/>{player.declared_nation}</>:<>—</>}</strong></div><div><span>Born</span><strong>{dob(player.date_of_birth,player.birth_date_precision)}</strong></div><div><span>Career</span><strong>{career}</strong></div><div><span>Positions</span><strong>{positions||'—'}</strong></div><div><span>Legacy Number</span><strong>#{player.legacy_player_id}</strong></div></div></div></section>
  <section className="card test-a1-matchlog"><header><div><span className="section-kicker">Career chronology</span><h2>Match Log <ChevronRight size={15}/></h2></div><b>{current.appearances} apps</b></header><div className="test-a1-match-list">{matches.map(m=>{const ev=events.get(m.match_id);return <div className="test-a1-match" key={m.match_id}><div className="test-a1-match-meta"><span>{m.competition}{m.round?` · ${m.round}`:''}</span><small>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${m.match_date}T12:00:00Z`))}</small></div><div className="test-a1-opponent"><ClubCrest crestUrl={m.opponent_crest_url} name={m.opponent}/><strong>{m.opponent} <em>({venue(m.venue_type)})</em></strong></div><div className="test-a1-match-bottom"><div className="test-a1-events">{ev?.goals.length?<span className="test-a1-event" title={`${ev.goals.length} goal${ev.goals.length===1?'':'s'}`}><img src={appIcon('Goal2.png')} alt="Goal"/>{ev.goals.length>1?<b>×{ev.goals.length}</b>:null}</span>:null}{ev?.captain?<span className="test-a1-event" title="Captain"><img src={appIcon('Captain Icon3.png')} alt="Captain"/></span>:null}{ev?.red?<span className="test-a1-event" title={`${ev.red.issued??'Red card'}${ev.red.minute_raw?` · ${ev.red.minute_raw}'`:''}`}><img src={appIcon('Red Card Icon2.png')} alt="Red card"/></span>:null}{ev?.subOn?<span className="test-a1-sub on" title={ev.subOn.timing_known?'Subbed on':'Subbed on · exact minute unavailable'}><TrendingUp size={12}/><b>{subMinute(ev.subOn)}</b></span>:null}{ev?.subOff?<span className="test-a1-sub off" title={ev.subOff.timing_known?'Subbed off':'Subbed off · exact minute unavailable'}><TrendingDown size={12}/><b>{subMinute(ev.subOff)}</b></span>:null}</div><div className="test-a1-score"><span className={`test-a1-form ${form(m.result).toLowerCase()}`}>{form(m.result)}</span><b>{m.leeds_score}–{m.opponent_score}</b></div></div></div>})}</div></section>
  <section className="card test-a1-stats"><header><h2>Player Stats <ChevronRight size={15}/></h2></header>{[['Appearances',current.appearances],['Goals',current.goals],['Wins',current.won],['Starts as Captain',current.captain]].map(([k,v])=><div className="test-a1-stat" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</section>
  <section className="card test-a1-standing"><header><div><span className="section-kicker">All-time Leeds United</span><h2>Appearance Ranking <ChevronRight size={15}/></h2></div><b>#{rank}</b></header><div className="test-a1-standing-head"><span>#</span><span>Player</span><span>Apps</span></div>{top.map((r,i)=><div className={`test-a1-standing-row ${r.player_id===PLAYER_ID?'you':''}`} key={r.player_id}><span>{i+1}</span><div><div className="test-a1-rank-icon"><PlayerIcon name={r.player} src={r.profile_image_url}/></div><strong>{r.player}</strong>{r.player_id===PLAYER_ID?<small>You</small>:null}</div><b>{r.appearances}</b></div>)}</section>
  <section className="card test-a1-summary"><header><h2>Career Record <ChevronRight size={15}/></h2></header><div className="test-a1-summary-grid"><div><span>Starts</span><strong>{current.starts}</strong></div><div><span>Wins</span><strong>{current.won}</strong></div><div><span>Win Rate</span><strong>{Number(current.win_pct).toFixed(1)}%</strong></div><div><span>Goals</span><strong>{current.goals}</strong></div></div><div className="test-a1-spark"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div></section>
  <section className="card test-a1-timeline"><header><h2>Leeds Career <ChevronRight size={15}/></h2></header><div className="test-a1-timeline-main"><strong>{career}</strong><span>772 competitive appearances across Billy Bremner's Leeds United career.</span><div className="test-a1-line"><i/></div><div className="test-a1-years"><span>1959</span><span>1965</span><span>1970</span><span>1976</span></div></div></section>
 </div></div>;
}
