-- LUFC Data V2: initial relational schema
-- Source exports remain immutable. Transformations/corrections are applied in staging/import code.

create table if not exists seasons (
  season_id bigint generated by default as identity primary key,
  display_name text not null unique,
  start_year smallint,
  end_year smallint,
  check (start_year is null or end_year is null or end_year >= start_year)
);

create table if not exists clubs (
  club_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  display_name text not null,
  crest_url text,
  created_at timestamptz not null default now()
);

create table if not exists competitions (
  competition_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  lineage_name text,
  created_at timestamptz not null default now()
);

create table if not exists competition_names (
  competition_name_id bigint generated by default as identity primary key,
  competition_id bigint not null references competitions(competition_id),
  display_name text not null,
  valid_from date,
  valid_to date,
  unique (competition_id, display_name, valid_from),
  check (valid_from is null or valid_to is null or valid_to >= valid_from)
);

create table if not exists players (
  player_id bigint generated by default as identity primary key,
  legacy_player_id integer not null unique,
  display_name text not null,
  full_name text,
  sortable_name text,
  date_of_birth date,
  birth_date_precision text not null default 'exact' check (birth_date_precision in ('exact','year','unknown')),
  place_of_birth text,
  declared_nation text,
  position_group text,
  position_detail text,
  joined_from text,
  transfer_type text,
  date_joined_or_turned_pro date,
  profile_image_url text,
  profile_text text,
  status text,
  active boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists player_aliases (
  player_alias_id bigint generated by default as identity primary key,
  player_id bigint not null references players(player_id) on delete cascade,
  alias text not null,
  alias_type text not null default 'source',
  unique (player_id, alias)
);

create table if not exists managers (
  manager_id bigint generated by default as identity primary key,
  canonical_name text not null,
  full_name text,
  date_of_birth date,
  place_of_birth text,
  date_of_death date,
  declared_nation text,
  profile_image_url text,
  did_you_know text,
  awards text,
  created_at timestamptz not null default now()
);

create unique index if not exists managers_identity_idx
  on managers (canonical_name, coalesce(date_of_birth, date '0001-01-01'));

create table if not exists manager_spells (
  manager_spell_id bigint generated by default as identity primary key,
  manager_id bigint not null references managers(manager_id),
  legacy_manager_order integer unique,
  role text,
  date_joined date,
  date_left date,
  caretaker boolean not null default false,
  status text,
  source_manager_name text,
  check (date_joined is null or date_left is null or date_left >= date_joined)
);

create table if not exists matches (
  match_id integer primary key,
  match_date date not null,
  season_id bigint references seasons(season_id),
  opponent_id bigint not null references clubs(club_id),
  competition_id bigint references competitions(competition_id),
  competition_name_id bigint references competition_names(competition_name_id),
  manager_spell_id bigint references manager_spells(manager_spell_id),
  venue_type text check (venue_type in ('H','A','N')),
  leeds_score smallint,
  opponent_score smallint,
  result text,
  stadium text,
  attendance integer,
  referee text,
  kickoff_time text,
  round text,
  formation text,
  captain_player_id bigint references players(player_id),
  neutral boolean not null default false,
  match_info text,
  milestones_events text,
  source_comp text,
  source_opponent text,
  created_at timestamptz not null default now()
);

create index if not exists matches_date_idx on matches(match_date);
create index if not exists matches_opponent_idx on matches(opponent_id);
create index if not exists matches_season_idx on matches(season_id);
create index if not exists matches_competition_idx on matches(competition_id);

create table if not exists player_matches (
  player_match_id bigint generated by default as identity primary key,
  match_id integer not null references matches(match_id) on delete cascade,
  player_id bigint not null references players(player_id),
  started boolean not null,
  substitute boolean not null,
  lineup_order smallint,
  source_slot text,
  unique (match_id, player_id),
  check (started <> substitute),
  check (lineup_order is null or lineup_order between 1 and 17)
);

create index if not exists player_matches_player_idx on player_matches(player_id);

create table if not exists goals (
  goal_id bigint generated by default as identity primary key,
  legacy_goal_number integer,
  match_id integer not null references matches(match_id),
  leeds_player_id bigint references players(player_id),
  scorer_name_raw text not null,
  minute_raw text,
  minute_normalised smallint,
  goal_number_for_player_match smallint,
  is_own_goal boolean not null default false,
  assist_player_id bigint references players(player_id),
  assisted_by_raw text,
  goal_type text,
  location text,
  body_part text,
  goal_state text,
  game_state text,
  kit_note text,
  source_row_number integer,
  created_at timestamptz not null default now()
);

create index if not exists goals_match_idx on goals(match_id);
create index if not exists goals_player_idx on goals(leeds_player_id);

create table if not exists migration_corrections (
  correction_id bigint generated by default as identity primary key,
  source_table text not null,
  source_locator text not null,
  field_name text not null,
  source_value text,
  corrected_value text,
  reason text not null,
  status text not null default 'confirmed' check (status in ('confirmed','proposed','rejected')),
  confirmed_by text,
  confirmed_at date,
  unique (source_table, source_locator, field_name, corrected_value)
);
