-- Opposition Managers relational migration
-- Applied to live Supabase as create_relational_opposition_manager_assignments.
--
-- Golden rule: matches.opposition_manager_raw remains immutable provenance.
-- This migration mirrors the live relational schema and bootstraps fixture
-- authority without destroying the canonical/provenance columns on matches.

create table if not exists public.managerial_people (
  managerial_person_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  full_name text,
  date_of_birth date,
  date_of_death date,
  provenance_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.managerial_person_nationalities (
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id) on delete cascade,
  nationality text not null,
  is_primary boolean not null default false,
  provenance_note text,
  primary key (managerial_person_id, nationality)
);

create table if not exists public.managerial_committees (
  managerial_committee_id bigint generated by default as identity primary key,
  club_id bigint not null references public.clubs(club_id),
  canonical_name text not null,
  provenance_note text,
  created_at timestamptz not null default now(),
  unique (club_id, canonical_name)
);

create table if not exists public.managerial_assignments (
  managerial_assignment_id bigint generated by default as identity primary key,
  match_id bigint not null unique references public.matches(match_id) on delete cascade,
  authority_type text not null check (authority_type in ('individual','joint','committee')),
  managerial_committee_id bigint references public.managerial_committees(managerial_committee_id),
  assignment_certainty text,
  raw_source text,
  canonical_source_name text,
  nationality_display text,
  provenance_status text not null default 'migrated_canonical',
  provenance_note text,
  created_at timestamptz not null default now(),
  check (authority_type = 'committee' or managerial_committee_id is null)
);

create table if not exists public.managerial_assignment_people (
  managerial_assignment_id bigint not null references public.managerial_assignments(managerial_assignment_id) on delete cascade,
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id),
  member_role text not null default 'manager',
  role_certainty text,
  provenance_note text,
  primary key (managerial_assignment_id, managerial_person_id)
);

create table if not exists public.opposition_manager_spells (
  opposition_manager_spell_id bigint generated by default as identity primary key,
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id),
  club_id bigint not null references public.clubs(club_id),
  spell_sequence integer,
  start_date date,
  end_date date,
  date_certainty text,
  provenance_note text,
  created_at timestamptz not null default now(),
  unique (managerial_person_id, club_id, spell_sequence)
);

create table if not exists public.opposition_manager_role_periods (
  opposition_manager_role_period_id bigint generated by default as identity primary key,
  opposition_manager_spell_id bigint not null references public.opposition_manager_spells(opposition_manager_spell_id) on delete cascade,
  role text not null,
  start_date date,
  end_date date,
  role_certainty text,
  provenance_note text,
  created_at timestamptz not null default now()
);

alter table public.managerial_people enable row level security;
alter table public.managerial_person_nationalities enable row level security;
alter table public.managerial_committees enable row level security;
alter table public.managerial_assignments enable row level security;
alter table public.managerial_assignment_people enable row level security;
alter table public.opposition_manager_spells enable row level security;
alter table public.opposition_manager_role_periods enable row level security;

-- Bootstrap canonical people from the existing canonical fixture assignment.
insert into public.managerial_people (canonical_name)
select distinct opposition_manager_name
from public.matches
where opposition_manager_authority_type <> 'committee'
  and opposition_manager_name is not null
on conflict (canonical_name) do nothing;

-- Committees remain authority entities, never fake people.
insert into public.managerial_committees (club_id, canonical_name)
select distinct m.opponent_id, m.opposition_manager_name
from public.matches m
where m.opposition_manager_authority_type = 'committee'
  and m.opposition_manager_name is not null
on conflict (club_id, canonical_name) do nothing;

-- Exactly one relational authority assignment per fixture.
insert into public.managerial_assignments
  (match_id, authority_type, managerial_committee_id, raw_source,
   canonical_source_name, nationality_display, provenance_status)
select m.match_id,
       m.opposition_manager_authority_type,
       mc.managerial_committee_id,
       m.opposition_manager_raw,
       m.opposition_manager_name,
       m.opposition_manager_nationality_display,
       'migrated_canonical'
from public.matches m
left join public.managerial_committees mc
  on m.opposition_manager_authority_type = 'committee'
 and mc.club_id = m.opponent_id
 and mc.canonical_name = m.opposition_manager_name
on conflict (match_id) do nothing;

-- Ordinary individual assignments bootstrap directly from canonical identity.
insert into public.managerial_assignment_people
  (managerial_assignment_id, managerial_person_id, member_role)
select ma.managerial_assignment_id, mp.managerial_person_id, 'manager'
from public.managerial_assignments ma
join public.matches m on m.match_id = ma.match_id
join public.managerial_people mp on mp.canonical_name = m.opposition_manager_name
where ma.authority_type = 'individual'
on conflict do nothing;

-- Explicitly proven shared-authority fixtures are represented relationally.
insert into public.managerial_people (canonical_name) values
  ('Arthur Turner'), ('Pat Beasley'), ('Jimmy Quinn'), ('Mick Gooding'),
  ('George Curtis (born 1939)'), ('John Sillett'),
  ('Alan Curbishley'), ('Steve Gritt'), ('David Pleat'), ('Chris Hughton'),
  ('Doug Livermore'), ('Ray Clemence'), ('Terry Venables'), ('Bryan Robson'),
  ('Iffy Onuora'), ('Mick Docherty'), ('Richard Shaw'), ('Colin West'),
  ('Mike Stowell'), ('Jon Rudkin'), ('Wayne Carlisle'), ('Scott Brown'),
  ('Dan Green'), ('John Pemberton'), ('Wade Elliott'), ('Albert Alexander')
on conflict (canonical_name) do nothing;

-- Proven committee lead metadata for Manchester City, match 240.
insert into public.managerial_assignment_people
  (managerial_assignment_id, managerial_person_id, member_role, role_certainty, provenance_note)
select ma.managerial_assignment_id, mp.managerial_person_id, 'lead', 'confirmed',
       'Albert Alexander identified as lead figure within Manchester City selection committee authority.'
from public.managerial_assignments ma
join public.managerial_people mp on mp.canonical_name='Albert Alexander'
where ma.match_id=240
on conflict (managerial_assignment_id, managerial_person_id) do nothing;
