-- Opposition Managers relational migration
-- Applied to live Supabase as create_relational_opposition_manager_assignments.
--
-- Golden rule: matches.opposition_manager_raw remains immutable provenance.
-- This layer models fixture authority relationally without destroying the
-- canonical/provenance columns already present on public.matches.

create table if not exists public.managerial_people (
  managerial_person_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.managerial_person_nationalities (
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id) on delete cascade,
  nationality_code text not null,
  nationality_display text,
  is_primary boolean not null default false,
  primary key (managerial_person_id, nationality_code)
);

create table if not exists public.managerial_committees (
  managerial_committee_id bigint generated by default as identity primary key,
  canonical_name text not null unique,
  club_id bigint references public.clubs(club_id),
  created_at timestamptz not null default now()
);

create table if not exists public.managerial_assignments (
  managerial_assignment_id bigint generated by default as identity primary key,
  match_id bigint not null unique references public.matches(match_id) on delete cascade,
  authority_type text not null check (authority_type in ('individual','joint','committee')),
  managerial_committee_id bigint references public.managerial_committees(managerial_committee_id),
  source_raw text,
  canonical_display text,
  audit_status text not null default 'provisional',
  notes text,
  created_at timestamptz not null default now(),
  check ((authority_type = 'committee' and managerial_committee_id is not null) or
         (authority_type <> 'committee' and managerial_committee_id is null))
);

create table if not exists public.managerial_assignment_people (
  managerial_assignment_id bigint not null references public.managerial_assignments(managerial_assignment_id) on delete cascade,
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id),
  assignment_role text not null default 'manager',
  display_order integer not null default 1,
  primary key (managerial_assignment_id, managerial_person_id)
);

create table if not exists public.opposition_manager_spells (
  opposition_manager_spell_id bigint generated by default as identity primary key,
  managerial_person_id bigint not null references public.managerial_people(managerial_person_id),
  club_id bigint not null references public.clubs(club_id),
  date_joined date,
  date_left date,
  status text,
  source_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.opposition_manager_role_periods (
  opposition_manager_role_period_id bigint generated by default as identity primary key,
  opposition_manager_spell_id bigint not null references public.opposition_manager_spells(opposition_manager_spell_id) on delete cascade,
  role text not null,
  date_from date,
  date_to date,
  source_note text,
  created_at timestamptz not null default now()
);

alter table public.managerial_people enable row level security;
alter table public.managerial_person_nationalities enable row level security;
alter table public.managerial_committees enable row level security;
alter table public.managerial_assignments enable row level security;
alter table public.managerial_assignment_people enable row level security;
alter table public.opposition_manager_spells enable row level security;
alter table public.opposition_manager_role_periods enable row level security;

-- Bootstrap canonical people from the existing canonical match column.
insert into public.managerial_people (canonical_name)
select distinct opposition_manager_name
from public.matches
where opposition_manager_authority_type <> 'committee'
  and opposition_manager_name is not null
on conflict (canonical_name) do nothing;

-- Committees remain separate authority entities rather than fake people.
insert into public.managerial_committees (canonical_name, club_id)
select distinct m.opposition_manager_name, m.opponent_id
from public.matches m
where m.opposition_manager_authority_type = 'committee'
on conflict (canonical_name) do nothing;

-- Exactly one relational authority assignment per historical fixture.
insert into public.managerial_assignments
  (match_id, authority_type, managerial_committee_id, source_raw, canonical_display, audit_status)
select m.match_id,
       m.opposition_manager_authority_type,
       mc.managerial_committee_id,
       m.opposition_manager_raw,
       m.opposition_manager_name,
       'provisional'
from public.matches m
left join public.managerial_committees mc
  on m.opposition_manager_authority_type = 'committee'
 and mc.canonical_name = m.opposition_manager_name
on conflict (match_id) do nothing;

-- Ordinary individual assignments bootstrap directly from the canonical name.
insert into public.managerial_assignment_people
  (managerial_assignment_id, managerial_person_id, assignment_role, display_order)
select ma.managerial_assignment_id, mp.managerial_person_id, 'manager', 1
from public.managerial_assignments ma
join public.matches m on m.match_id = ma.match_id
join public.managerial_people mp on mp.canonical_name = m.opposition_manager_name
where ma.authority_type = 'individual'
on conflict do nothing;

-- Explicitly proven joint/co-manager fixtures are represented by separate people.
insert into public.managerial_people (canonical_name) values
  ('Arthur Turner'), ('Pat Beasley'), ('Jimmy Quinn'), ('Mick Gooding'),
  ('George Curtis (born 1939)'), ('John Sillett'),
  ('Alan Curbishley'), ('Steve Gritt'), ('David Pleat'), ('Chris Hughton'),
  ('Albert Alexander')
on conflict (canonical_name) do nothing;

insert into public.managerial_assignment_people
  (managerial_assignment_id, managerial_person_id, assignment_role, display_order)
select ma.managerial_assignment_id, mp.managerial_person_id, v.role, v.display_order
from (values
  (1346,'Arthur Turner','joint',1),(1346,'Pat Beasley','joint',2),
  (1367,'Arthur Turner','joint',1),(1367,'Pat Beasley','joint',2),
  (2870,'George Curtis (born 1939)','joint',1),(2870,'John Sillett','joint',2),
  (3177,'Alan Curbishley','joint',1),(3177,'Steve Gritt','joint',2),
  (3179,'Alan Curbishley','joint',1),(3179,'Steve Gritt','joint',2),
  (3326,'Jimmy Quinn','joint',1),(3326,'Mick Gooding','joint',2),
  (3450,'David Pleat','joint',1),(3450,'Chris Hughton','joint',2),
  (240,'Albert Alexander','lead',1)
) as v(match_id, canonical_name, role, display_order)
join public.managerial_assignments ma on ma.match_id = v.match_id
join public.managerial_people mp on mp.canonical_name = v.canonical_name
on conflict do nothing;
