create table if not exists public.shirt_number_source_rows (
  source_row_id bigint generated by default as identity primary key,
  era text not null check (era in ('match_by_match','fixed_squad')),
  source_season text not null,
  source_match_date date,
  source_competition text,
  source_competition_match_number integer,
  source_opponent text,
  source_venue text,
  source_result_leeds_first text,
  shirt_number smallint,
  shirt_number_raw text,
  source_player_name text not null,
  source_role text,
  source_substitute_status text,
  source_status text,
  source_notes text,
  source_name text,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists shirt_number_source_rows_season_idx on public.shirt_number_source_rows(source_season);
create index if not exists shirt_number_source_rows_player_idx on public.shirt_number_source_rows(source_player_name);
create index if not exists shirt_number_source_rows_date_idx on public.shirt_number_source_rows(source_match_date);

create table if not exists public.player_source_aliases (
  player_source_alias_id bigint generated by default as identity primary key,
  source_name text not null,
  source_player_name text not null,
  player_id bigint not null references public.players(player_id) on delete restrict,
  notes text,
  created_at timestamptz not null default now(),
  unique(source_name, source_player_name)
);

create table if not exists public.player_match_shirt_numbers (
  player_match_shirt_number_id bigint generated by default as identity primary key,
  match_id integer not null references public.matches(match_id) on delete restrict,
  player_id bigint not null references public.players(player_id) on delete restrict,
  shirt_number smallint not null check (shirt_number > 0),
  source_row_id bigint references public.shirt_number_source_rows(source_row_id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(match_id, player_id),
  unique(match_id, shirt_number)
);
create index if not exists player_match_shirt_numbers_player_idx on public.player_match_shirt_numbers(player_id);

create table if not exists public.player_season_squad_numbers (
  player_season_squad_number_id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(season_id) on delete restrict,
  player_id bigint not null references public.players(player_id) on delete restrict,
  squad_number smallint check (squad_number > 0),
  assignment_status text,
  notes text,
  source_row_id bigint references public.shirt_number_source_rows(source_row_id) on delete restrict,
  created_at timestamptz not null default now(),
  unique(season_id, player_id, squad_number, source_row_id)
);
create index if not exists player_season_squad_numbers_player_idx on public.player_season_squad_numbers(player_id);
create index if not exists player_season_squad_numbers_season_number_idx on public.player_season_squad_numbers(season_id, squad_number);

comment on table public.player_match_shirt_numbers is 'Canonical actual match shirt numbers for the pre-fixed squad-number era, currently sourced for 1991/92 and 1992/93.';
comment on table public.player_season_squad_numbers is 'Canonical fixed squad-number assignments from 1993/94 onward. Number reuse within a season is intentionally allowed.';